### ISSUE TITLE
[Blueprint] Frasier

### ISSUE THREAD

**Issue by lorissimo** [TitleCardMaker/Blueprints#103]
### Series Name

Frasier

### Series Year

2023

### Series Database IDs

imdb:tt14124236,tmdb:195241,tvdb:425711

### Creator Username

GrazedNutsack

### Blueprint Description

Simple "Standard" card type with a 'Blue' (#87CEFA) "Florentine Bold" Font as the title text.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "template_ids": [],
    "font_id": 0,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Frasier",
      "color": "#87CEFA",
      "delete_missing": true,
      "file": "Florentine Bold.ttf",
      "size": 1.3,
      "title_case": "title"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![Frasier (2023) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/80125655/aa0ac17e-2d07-44d1-9eca-d6196ac54f96)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13628962/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks for submitting this! I assigned the Font directly to the Series, and removed the Template (since it wasn't necessary). Looks good!

/create-blueprint
