### ISSUE TITLE
[Blueprint] Letterkenny

### ISSUE THREAD

**Issue by BEisem** [TitleCardMaker/Blueprints#147]
### Series Name

Letterkenny

### Series Year

2016

### Series Database IDs

imdb:tt4647692,tmdb:65798,tvdb:302938

### Creator Username

Departed69

### Blueprint Description

Overline card type with the Letterkenny title font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Letterkenny",
      "delete_missing": true,
      "file": "futura-pt-extrabold.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/34734248/bd08a74e-1b34-4c57-8eff-f902ae9b15c0)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13757066/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good. /create-blueprint
