### ISSUE TITLE
[Blueprint] Baki

### ISSUE THREAD

**Issue by Letixari** [TitleCardMaker/Blueprints#152]
### Series Name

Baki

### Series Year

2018

### Series Database IDs

imdb:tt6357658,tmdb:80623,tvdb:348742

### Creator Username

BenevolentNPC

### Blueprint Description

Anime card type with kanji, absolute episode numbering, and custom story arcs for season titles.

### Blueprint

```json
{
  "series": {
    "card_type": "anime",
    "episode_text_format": "Episode {absolute_episode_number}",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "season_title_ranges": [
      "s1e1-s1e24",
      "s1e25-s1e26",
      "s2e1-s2e8",
      "s2e9-s2e12"
    ],
    "season_title_values": [
      "Most Evil Death Row Convicts",
      "Great Chinese Challenge",
      "Great Chinese Challenge",
      "Godlike Clash of the Kids"
    ]
  },
  "episodes": {
    "s2e13": {
      "hide_season_text": true
    },
    "s0e1": {
      "hide_season_text": true,
      "hide_episode_text": true
    }
  }
}
```

### Preview Title Cards

![preview-2](https://github.com/TitleCardMaker/Blueprints/assets/6104138/c4e2e8b0-5bf5-4c4b-bc82-e2893ce6898d)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
