### ISSUE TITLE
[Blueprint] Baki Hanma

### ISSUE THREAD

**Issue by Letixari** [TitleCardMaker/Blueprints#153]
### Series Name

Baki Hanma

### Series Year

2021

### Series Database IDs

imdb:tt13357140,tmdb:129600,tvdb:406152

### Creator Username

BenevolentNPC

### Blueprint Description

Anime card type with kanji, absolute episode numbering, custom story arcs for season titles.

### Blueprint

```json
{
  "series": {
    "card_type": "anime",
    "episode_text_format": "Episode {absolute_episode_number}",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "season_title_ranges": [
      "s1e1-s1e2",
      "s1e3-s1e12",
      "s2e1-s2e13",
      "s2e14-s2e20",
      "s2e21-s2e27"
    ],
    "season_title_values": [
      "Combat Shadow Fighting",
      "Great Prison Battle Saga",
      "Pickle Wars",
      "Warrior's Struggle",
      "Strongest Father and Child Quarrel"
    ]
  }
}
```

### Preview Title Cards

![preview-4](https://github.com/TitleCardMaker/Blueprints/assets/6104138/066bdf12-c1b6-4c3f-91ac-b01a774dd369)

**Comment by CollinHeist** [comment]
Thanks again /create-blueprint
