### ISSUE TITLE
[Blueprint] BLUELOCK

### ISSUE THREAD

**Issue by Letixari** [TitleCardMaker/Blueprints#154]
### Series Name

BLUELOCK

### Series Year

2022

### Series Database IDs

imdb:tt15222080,tmdb:131041,tvdb:408629

### Creator Username

BenevolentNPC

### Blueprint Description

Anime card type with kanji, absolute episode numbering, custom story arcs for season titles.

### Blueprint

```json
{
  "series": {
    "card_type": "anime",
    "episode_text_format": "Episode {absolute_episode_number}",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "season_title_ranges": [
      "s1e1-s1e2",
      "s1e3-s1e11",
      "s1e12-s1e24"
    ],
    "season_title_values": [
      "Introduction",
      "First Selection",
      "Second Selection"
    ]
  }
}
```

### Preview Title Cards

![preview-5](https://github.com/TitleCardMaker/Blueprints/assets/6104138/16b82826-90cc-441e-be5b-4136e4356c45)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
