### ISSUE TITLE
[Blueprint] The Rising of the Shield Hero

### ISSUE THREAD

**Issue by Letixari** [TitleCardMaker/Blueprints#156]
### Series Name

The Rising of the Shield Hero

### Series Year

2019

### Series Database IDs

imdb:tt9529546,tmdb:83095,tvdb:353712

### Creator Username

BenevolentNPC

### Blueprint Description

Anime card type with kanji, absolute episode numbering and custom story arcs for the season titles.

### Blueprint

```json
{
  "series": {
    "card_type": "anime",
    "episode_text_format": "Episode {absolute_episode_number}",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "season_title_ranges": [
      "s1e1-s1e1",
      "s1e2-s1e2",
      "s1e3-s1e4",
      "s1e5-s1e6",
      "s1e7-s1e8",
      "s1e9-s1e12",
      "s1e13-s1e20",
      "s1e21-s1e21",
      "s1e22-s1e25",
      "s2e1-s2e6",
      "s2e7-s2e13",
      "s3e1-s3e3",
      "s3e4-s3e6",
      "s3e7-s3e9",
      "s3e10-s3e11",
      "s3e12-s3e12"
    ],
    "season_title_values": [
      "Summoning",
      "Slave",
      "Second Wave",
      "Filo Rial",
      "Peddling",
      "Third Wave",
      "Devil of the Shield",
      "Punishment",
      "Cal Mira Island",
      "Spirit Turtle",
      "New World",
      "Rebuilding",
      "Fallen Heroes",
      "Wrath Dragon",
      "JUSTICE",
      "Siltvelt Succession"
    ]
  },
  "episodes": {
    "s0e5": {
      "template_ids": [],
      "title": "Raphtalia and Filo"
    }
  }
}
```

### Preview Title Cards

![preview-6](https://github.com/TitleCardMaker/Blueprints/assets/6104138/d7078d43-ba58-4344-997d-4b4d06859d69)

**Comment by CollinHeist** [comment]
@Letixari I don't see a custom Font, did you mean to include one?

**Comment by Letixari** [comment]
> @Letixari I don't see a custom Font, did you mean to include one?

Oh sorry. I was thinking of including one, but realised it wasn't actually the show font. Just named after a character in the show. 

Ill edit the description.

**Comment by CollinHeist** [comment]
Great - thanks for doing that! /create-blueprint
