### ISSUE TITLE
[Blueprint] Food Wars! Shokugeki no Soma

### ISSUE THREAD

**Issue by Letixari** [TitleCardMaker/Blueprints#176]
### Series Name

Food Wars! Shokugeki no Soma

### Series Year

2015

### Series Database IDs

imdb:tt4731072,tmdb:62273,tvdb:289909

### Creator Username

BenevolentNPC

### Blueprint Description

Anime card type with kanji, absolute episode numbering, "The (season number) plate" for the season titles, and a custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "episode_text_format": "Episode {absolute_episode_number}",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "season_title_ranges": [
      "s1e1-s5e13"
    ],
    "season_title_values": [
      "The {season_number_ordinal} Plate"
    ],
    "extra_keys": [
      "stroke_color",
      "kanji_vertical_shift"
    ],
    "extra_values": [
      "#ed040a",
      "0"
    ]
  },
  "fonts": [
    {
      "name": "Food Wars",
      "color": "#f8a413",
      "delete_missing": true,
      "file": "SedonaScriptFLF.ttf",
      "size": 1.3
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/6104138/11b116fc-b0b6-4b7c-b69b-656ef07f5815)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13828869/fonts.zip)

**Comment by CollinHeist** [comment]
@Letixari You might try adjusting the Kanji vertical shift extra so there is not so much space between the kanji and the title text. If not, let me know!

And just for future reference (in case you didn't know) you can also do a season text format of `The {season_number_ordinal} Plate` to avoid having to type those season titles (although that's not too onerous in this case).

**Comment by Letixari** [comment]
> @Letixari You might try adjusting the Kanji vertical shift extra so there is not so much space between the kanji and the title text. If not, let me know!

I think vertical shift -80 looks about right except on multi-line episode titles. Im not too sure how to work it in this case. Thanks for the hint. Ill pay more attention to that in the future.

> And just for future reference (in case you didn't know) you can also do a season text format of `The {season_number_ordinal} Plate` to avoid having to type those season titles (although that's not too onerous in this case).

Good tip. I didnt even know I could do that. Doing s1e1-s5e13 with `The {season_number_ordinal} Plate` seems to work fine. It would also be possible to make the range longer for future season support, but you never know if the pull the `Final Season` out of nowhere like they tend to do.

Ill edit the blueprint for now and you can upload that, but what about the kanji on multi-line episode names?

**Comment by CollinHeist** [comment]
@Letixari I had been meaning to revise the Kanji vertical placement code for a little, so I went ahead and did that in `webui543` on the multi-connections branch. Do you want to check if that helps the weird kanji placement for multi-line titles?

**Comment by Letixari** [comment]
> @Letixari I had been meaning to revise the Kanji vertical placement code for a little, so I went ahead and did that in `webui543` on the multi-connections branch. Do you want to check if that helps the weird kanji placement for multi-line titles?

The changes help a lot. Honestly with the new placement, the offset is not needed at all in my opinion. Ill leave it in the blueprint as 0 value so that its easy to change if someone wishes to.

**Comment by CollinHeist** [comment]
@Letixari Perfect - alright thanks for making / updating this! /create-blueprint
