### ISSUE TITLE
[Blueprint] Fear the Walking Dead

### ISSUE THREAD

**Issue by codyburg** [TitleCardMaker/Blueprints#186]
### Series Name

Fear the Walking Dead

### Series Year

2015

### Series Database IDs

imdb:tt3743822,tmdb:62286,tvdb:290853

### Creator Username

codyburg

### Blueprint Description

A simple title card for Fear The Walking Dead.

### Blueprint

```json
Unable to paste
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/118586335/15eac88a-8130-4acc-8e83-460608873b3d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13873288/fonts.zip)

### Zip of Source Files

[Fear the Walking Dead (2015) Blueprint.zip](https://github.com/TitleCardMaker/Blueprints/files/13873290/Fear.the.Walking.Dead.2015.Blueprint.zip)

**Comment by CollinHeist** [comment]
@codyburg Hey, thanks for submitting these. Please follow the instructions on the [docs](https://titlecardmaker.com/blueprints/#sharing-your-own-blueprint). You'll need to paste the blueprint.json file itself in the form where it asks you to,  not upload the entire .zip into the source file section.

**Comment by CollinHeist** [comment]
I'm going to close this for now, if you are able to fix this let me know! Thanks.
