### ISSUE TITLE
[Blueprint] The Walking Dead

### ISSUE THREAD

**Issue by codyburg** [TitleCardMaker/Blueprints#187]
### Series Name

The Walking Dead

### Series Year

2010

### Series Database IDs

imdb:tt1520211,tmdb:1402,tvdb:153021

### Creator Username

codyburg

### Blueprint Description

A simple title card for The Walking Dead

### Blueprint

```json
Unable to paste
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/118586335/b9326ed6-8964-4b3c-80e3-af563c3e16f1)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13873311/fonts.zip)

### Zip of Source Files

[The Walking Dead (2010) Blueprint.zip](https://github.com/TitleCardMaker/Blueprints/files/13873314/The.Walking.Dead.2010.Blueprint.zip)

**Comment by CollinHeist** [comment]
@codyburg Hey - same comments as the other Blueprint, if you want to fix those. Thanks!

**Comment by CollinHeist** [comment]
(same as the other one, again) I'm going to close this for now, if you are able to fix this let me know! Thanks.
