### ISSUE TITLE
[Blueprint] Alone

### ISSUE THREAD

**Issue by azuravian** [TitleCardMaker/Blueprints#188]
### Series Name

Alone

### Series Year

2015

### Series Database IDs

imdb:tt4803766,tmdb:63726,tvdb:295936

### Creator Username

Azuravian

### Blueprint Description

Simple Blueprint using the Divider card, with a custom-made Font in the style of the show's logo.

### Blueprint

```json
{
  "series": {
    "card_type": "divider",
    "font_id": 0
  },
  "fonts": [
    {
      "name": "Alone_Custom",
      "color": "White",
      "delete_missing": true,
      "file": "Alone_Custom.ttf",
      "size": 1.5,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/7379812/3392a6ae-47ce-45fe-bd44-3557869a39c7)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13885424/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks for making this! Looks good. /create-blueprint
