### ISSUE TITLE
[Blueprint] Hijack

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#19]
### Series Name

Hijack

### Series Year

2023

### Series Database IDs

imdb:tt19854762,tmdb:198102,tvdb:419254

### Creator Username

PJ

### Blueprint Description

Font to match HIJACK font

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "font_id": 0,
      "name": "hijack",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Hijack",
      "delete_missing": true,
      "file": "Rajdhani-Bold.ttf",
      "replacements_in": [
        "'i'",
        "'I'"
      ],
      "replacements_out": [
        "'/'",
        "'/'"
      ],
      "size": 1.2
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![image](https://github.com/TitleCardMaker/Blueprints/assets/45070803/0b0c7c2a-16b9-47d1-8e99-37fc11c1f9b7)
![image](https://github.com/TitleCardMaker/Blueprints/assets/45070803/39e27952-cf2f-4c89-8868-c0d01bf93c92)

**Comment by CollinHeist** [comment]
@PJGitHub9 Hey, thanks for submitting this. Looks like you did not include the Font file, and the preview images seem to be using the default Font. After that's fixed I'll get this merged.

**Comment by CollinHeist** [comment]
Hey @PJGitHub9 I'll close this for now, please re-open it if you are able to make those changes. Thanks!
