### ISSUE TITLE
[Blueprint] Arcane

### ISSUE THREAD

**Issue by MMFQDEATH** [TitleCardMaker/Blueprints#190]
### Series Name

Arcane

### Series Year

2021

### Series Database IDs

imdb:tt11126994,tmdb:94605,tvdb:371028

### Creator Username

DeepDaddyTTV

### Blueprint Description

A simple set of cards featuring the logo and using the Series Font in white.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "calligraphy",
    "extra_keys": [
      "logo_size"
    ],
    "extra_values": [
      ".9"
    ],
    "font_color": "White"
  },
  "fonts": [
    {
      "name": "Arcane",
      "color": "rgb(166,114,50)",
      "delete_missing": true,
      "file": "Arcane Nine.otf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32502468/6c7c04d8-e1c7-4b85-96c3-cfd33a26d381)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13911223/fonts.zip)

### Zip of Source Files

[logo.zip](https://github.com/TitleCardMaker/Blueprints/files/13915605/logo.png.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks for submitting this. /create-blueprint
