### ISSUE TITLE
[Blueprint] Pokémon Chronicles

### ISSUE THREAD

**Issue by MMFQDEATH** [TitleCardMaker/Blueprints#214]
### Series Name

Pokémon Chronicles

### Series Year

2001

### Series Database IDs

imdb:tt1294022,tmdb:13230,tvdb:72975

### Creator Username

DeepDaddyTTV

### Blueprint Description

This is a continuation of my Pokémon Complete Series Collection. It will match the sets I've released for the main Series. It uses episode ordering by TVDB (as the spinoff series are correctly ordered there). 

Standard season title as the spinoff's don't have defined arcs. Uses the Pokémon font and includes a colored drop shadow to match the series color scheme.

The Series' episode text Font should be changed to match your specific folder structure (defaults to /config/fonts/Pokemon.ttf).

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "episode_text_format": "Episode {episode_number}",
    "extra_keys": [
      "middle_element",
      "frame_color",
      "episode_text_color",
      "logo_size",
      "logo_vertical_shift",
      "frame_width",
      "episode_text_font",
      "episode_text_font_size",
      "shadow_color"
    ],
    "extra_values": [
      "logo",
      "rgba(255,203,5,1)",
      "rgba(255,203,5,1)",
      "1.5",
      "400",
      "15",
      "/config/fonts/Pokemon.ttf",
      "2",
      "rgba(60,90,166,1)"
    ],
    "font_color": "rgba(255,203,5,1)",
    "font_size": 1.75,
    "font_stroke_width": 3.5
  },
  "fonts": [
    {
      "name": "Pok\u00e9mon",
      "color": "rgba(255,203,5,1)",
      "delete_missing": true,
      "file": "Pokemon.ttf",
      "replacements_in": [
        "`",
        "\u00e9",
        "{",
        "\u2026",
        "@",
        "}",
        "^",
        "\u00c9"
      ],
      "replacements_out": [
        "'",
        "e",
        "",
        "...",
        "",
        "",
        "",
        "E"
      ],
      "stroke_width": 3.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32502468/38869412-0fd5-41fc-a44c-c37d17205503)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13952805/fonts.zip)

### Zip of Source Files

[Pokemon Chronicles.zip](https://github.com/TitleCardMaker/Blueprints/files/13952811/Pokemon.Chronicles.zip)

**Comment by CollinHeist** [comment]
Looks great - thanks again. /create-blueprint
