### ISSUE TITLE
[Blueprint] Pokémon Concierge

### ISSUE THREAD

**Issue by MMFQDEATH** [TitleCardMaker/Blueprints#215]
### Series Name

Pokémon Concierge

### Series Year

2023

### Series Database IDs

imdb:tt26916286,tmdb:221301,tvdb:431703

### Creator Username

DeepDaddyTTV

### Blueprint Description

This is a continuation of my Pokémon Complete Series Collection. It will match the sets I've released for the main series. It uses episode ordering by TVDB as the spinoff series are correctly ordered there.

It uses standard episode ordering as the spinoff's don't have pre-defined arcs. It uses the Pokémon font and includes a colored drop shadow to match the series color scheme.

The Series' episode text Font should be changed to match your specific folder structure (defaults to /config/fonts/Pokemon.ttf).

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "episode_text_format": "Episode {episode_number}",
    "extra_keys": [
      "middle_element",
      "episode_text_color",
      "frame_color",
      "logo_size",
      "logo_vertical_shift",
      "frame_width",
      "episode_text_font",
      "episode_text_font_size",
      "shadow_color"
    ],
    "extra_values": [
      "logo",
      "rgba(255,203,5,1)",
      "rgba(255,203,5,1)",
      "2",
      "475",
      "15",
      "/config/fonts/Pokemon.ttf",
      "2",
      "rgba(60,90,166,1)"
    ],
    "template_ids": [],
    "font_color": "rgba(255,203,5,1)",
    "font_size": 1.75,
    "font_stroke_width": 3.5,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Pok\u00e9mon",
      "color": "rgba(255,203,5,1)",
      "delete_missing": true,
      "file": "Pokemon.ttf",
      "replacements_in": [
        "`",
        "\u00e9",
        "{",
        "\u2026",
        "@",
        "}",
        "^",
        "\u00c9"
      ],
      "replacements_out": [
        "'",
        "e",
        "",
        "...",
        "",
        "",
        "",
        "E"
      ],
      "stroke_width": 3.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32502468/78d40dbc-0d9e-44a8-b56c-a3c54b788da9)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13953392/fonts.zip)

### Zip of Source Files

[logo.zip](https://github.com/TitleCardMaker/Blueprints/files/13953395/logo.zip)

**Comment by CollinHeist** [comment]
Thanks! I've never heard of this Series. /create-blueprint
