### ISSUE TITLE
[Blueprint] Pokémon: Origins

### ISSUE THREAD

**Issue by MMFQDEATH** [TitleCardMaker/Blueprints#220]
### Series Name

Pokémon: Origins

### Series Year

2013

### Series Database IDs

imdb:tt3218680,tmdb:61295,tvdb:273616

### Creator Username

DeepDaddyTTV

### Blueprint Description

This is a continuation of my Pokémon Complete Series Collection. It will match the sets I've released for the main series. It uses episode ordering by TVDB as the spinoff series are correctly ordered there.

For the season specific variants, there will also be alternative forms without season text.

It uses standard episode ordering as the spinoff's don't have pre-defined arcs. It uses the Pokémon font and includes a colored drop shadow to match the series color scheme.

The Series' episode text Font should be changed to match your specific folder structure (defaults to /config/fonts/Pokemon.ttf).

### Blueprint

```json
{
  "series": {
    "extra_keys": [
      "logo_size",
      "logo_vertical_shift"
    ],
    "extra_values": [
      "1.5",
      "375"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "tinted frame",
      "episode_text_format": "Episode {episode_number}",
      "extra_keys": [
        "middle_element",
        "episode_text_color",
        "frame_color",
        "shadow_color",
        "episode_text_font",
        "logo_vertical_shift",
        "frame_width",
        "logo_size",
        "episode_text_font_size"
      ],
      "extra_values": [
        "logo",
        "rgba(255,203,5,1)",
        "rgba(255,203,5,1)",
        "rgba(60,90,166,1)",
        "/config/fonts/Pokemon.ttf",
        "350",
        "15",
        "1.5",
        "2"
      ],
      "name": "Pok\u00e9mon",
      "filters": [
        {
          "argument": "Series Name",
          "operation": "contains",
          "reference": "Pok\u00e9mon"
        }
      ]
    }
  ],
  "fonts": [
    {
      "name": "Pok\u00e9mon",
      "color": "rgba(255,203,5,1)",
      "delete_missing": true,
      "file": "Pokemon.ttf",
      "replacements_in": [
        "`",
        "\u00e9",
        "{",
        "\u2026",
        "@",
        "}",
        "^",
        "\u00c9"
      ],
      "replacements_out": [
        "'",
        "e",
        "",
        "...",
        "",
        "",
        "",
        "E"
      ],
      "size": 1.75,
      "stroke_width": 3.5,
      "title_case": "source"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32502468/fa47fcf2-70a9-43e7-a9e0-e182037eb7cb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13955348/fonts.zip)

### Zip of Source Files

[logo.zip](https://github.com/TitleCardMaker/Blueprints/files/13955349/logo.zip)

**Comment by CollinHeist** [comment]
I just realized I probably should have recommended we put all of these into a single Template, so that they're easily edited en-masse..

**Comment by MMFQDEATH** [comment]
Yeah I saw that button but didn't understand how I make one. That would be super useful for this and the arrowverse I plan on doing.

**Comment by CollinHeist** [comment]
Rather than putting all these configuration options and the Font into each Series, you just add them to a single Template and then add that Template to the Series. I will edit the ones we already created to do that.

**Comment by MMFQDEATH** [comment]
So if I needed to make a template, how would I do that from my end? And do you need to pre-assign the shows or does it apply globally? Also, does the template still choose custom logos?

**Comment by CollinHeist** [comment]
> So if I needed to make a template, how would I do that from my end?
Go to the Templates page, click create, and then just add your settings there. There's a page on it in the docs.
> And do you need to pre-assign the shows or does it apply globally?
You need to assign the Templates to the shows manually.
> Also, does the template still choose custom logos?
Templates act identically to as if you entered these settings into the Series itself

**Comment by MMFQDEATH** [comment]
I feel so stupid. I completely bypassed that option. Man that would've made my life so much easier. So when making a template and using it for a show, do I still submit the blueprint for ease of others?

**Comment by CollinHeist** [comment]
Yes, TCM will automatically include any assigned Templates in the export. For an example you can see how I did it with the Scooby-Doo franchise
