### ISSUE TITLE
[Blueprint] Pokémon: Paldean Winds

### ISSUE THREAD

**Issue by MMFQDEATH** [TitleCardMaker/Blueprints#222]
### Series Name

Pokémon: Paldean Winds

### Series Year

2023

### Series Database IDs

imdb:tt29140863,tmdb:232214,tvdb:438096

### Creator Username

DeepDaddyTTV

### Blueprint Description

This is a continuation of my Pokémon Complete Series Collection. It will match the sets I've released for the main series. It uses episode ordering by TVDB as the spinoff series are correctly ordered there.

For the season specific variants, there will also be alternative forms without season text.

It uses standard episode ordering as the spinoff's don't have pre-defined arcs. It uses the Pokémon font and includes a colored drop shadow to match the series color scheme.

The Series' episode text Font should be changed to match your specific folder structure (defaults to /config/fonts/Pokemon.ttf).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "logo_size",
      "logo_vertical_shift"
    ],
    "extra_values": [
      "1",
      "500"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "font_id": 0,
      "card_type": "tinted frame",
      "episode_text_format": "Episode {episode_number}",
      "extra_keys": [
        "middle_element",
        "episode_text_color",
        "frame_color",
        "shadow_color",
        "episode_text_font",
        "logo_vertical_shift",
        "frame_width",
        "logo_size",
        "episode_text_font_size"
      ],
      "extra_values": [
        "logo",
        "rgba(255,203,5,1)",
        "rgba(255,203,5,1)",
        "rgba(60,90,166,1)",
        "/config/fonts/Pokemon.ttf",
        "350",
        "15",
        "1.5",
        "2"
      ],
      "name": "Pok\u00e9mon",
      "filters": [
        {
          "argument": "Series Name",
          "operation": "contains",
          "reference": "Pok\u00e9mon"
        }
      ]
    }
  ],
  "fonts": [
    {
      "name": "Pok\u00e9mon",
      "color": "rgba(255,203,5,1)",
      "delete_missing": true,
      "file": "Pokemon.ttf",
      "replacements_in": [
        "`",
        "\u00e9",
        "{",
        "\u2026",
        "@",
        "}",
        "^",
        "\u00c9"
      ],
      "replacements_out": [
        "'",
        "e",
        "",
        "...",
        "",
        "",
        "",
        "E"
      ],
      "size": 1.75,
      "stroke_width": 3.5,
      "title_case": "source"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/17693271/27b62fbc-934d-42a6-9f5d-3a900addeebd)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13958956/fonts.zip)

### Zip of Source Files

[Pokémon - Paldean Winds (2023).zip](https://github.com/TitleCardMaker/Blueprints/files/13958965/Pokemon.-.Paldean.Winds.2023.zip)

**Comment by CollinHeist** [comment]
@MMFQDEATH I noticed that since you added the Template, the font size has changed relative to the other Blueprints you submitted. I assume this was unintentional?

**Comment by CollinHeist** [comment]
Yeah no problem, there are a lot of little details. I think it's because you were overriding the font size in the Series, and not in the Font itself. I updated all your previously submitted Blueprints with a Template / Font that has all of this corrected

**Comment by CollinHeist** [comment]
Okay I have updated all the pending Blueprint JSONs with the corrected Templates / Fonts, would you update the preview images?
