### ISSUE TITLE
[Blueprint] DAVE

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#236]
### Series Name

DAVE

### Series Year

2020

### Series Database IDs

imdb:tt8531222,tmdb:97084,tvdb:354905

### Creator Username

PJ

### Blueprint Description

Dave (AKA Lil Dicky) TV card

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "font_id": 0,
      "name": "Dave",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Dave",
      "color": "#ffbea3",
      "delete_missing": true,
      "file": "Clearface-Serial-Heavy Regular.ttf",
      "size": 1.25,
      "stroke_width": 1.2,
      "vertical_shift": -20
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/45070803/29ac1ccb-40a3-4e2f-9995-127e62eb4217)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14003670/fonts.zip)

**Comment by CollinHeist** [comment]
@PJGitHub9 Looks great! How does it look to use a negative vertical shift? Maybe like -20, but I am just eyeballing it. That way there is less space between the season/episode text and the title.

If not, just let me know I'll get this created as-is 👍🏻

**Comment by PJGitHub9** [comment]
@CollinHeist yes! `-20` seems to work the best. Messed around with a few values, and `-20` seems to be perfect

So yeah, changing it to -20 is perfect :D

**Comment by CollinHeist** [comment]
@PJGitHub9 Would you be able to update the preview Card? I'll update the JSON

**Comment by PJGitHub9** [comment]
![DAVE (2020) - S01E01_TCM](https://github.com/TitleCardMaker/Blueprints/assets/45070803/29ac1ccb-40a3-4e2f-9995-127e62eb4217)

@CollinHeist just posted it here. Want me to update the OP?

**Comment by CollinHeist** [comment]
Nope, looks good! Thanks again /create-blueprint
