### ISSUE TITLE
[Blueprint] Percy Jackson and the Olympians

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#270]
### Series Name

Percy Jackson and the Olympians

### Series Year

2023

### Series Database IDs

imdb:tt12324366,tmdb:103540,tvdb:415151

### Creator Username

Reicha7

### Blueprint Description

Standard card with a custom Font to try and match the series font. The season title is also hidden.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true
  },
  "fonts": [
    {
      "name": "Percy Jackson",
      "color": "#a9b0b4",
      "delete_missing": true,
      "file": "Windlass.ttf",
      "interline_spacing": 75,
      "size": 0.75,
      "vertical_shift": 35
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/7ff65f88-13b0-46c7-8ba0-44dbd7ca98cf)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14044991/fonts.zip)

**Comment by archieyates** [comment]
One thing I didn't clock is that this does risk making what is basically a useless template for TV. I originally was just using that whilst transitioning from the CLI

**Comment by CollinHeist** [comment]
@archieyates That's fine, I usually fix those for people when they submit Blueprints, no big deal. It might be worth trying a negative vertical shift on the Font, so there is less spacing between the season/episode text and the title - how does that look?

**Comment by archieyates** [comment]
Yeah I'll take a look tomorrow and see what I think :)

**Comment by archieyates** [comment]
It was set at 100 before and I think adjusting it to 35 is better. Attached the old preview and an example of a 2-liner
![Percy Jackson and the Olympians - S01E07 - We Find Out the Truth, Sort Of](https://github.com/TitleCardMaker/Blueprints/assets/9253709/7ff65f88-13b0-46c7-8ba0-44dbd7ca98cf)
![Percy Jackson and the Olympians - S01E01 - I Accidentally Vaporize My Pre-Algebra Teacher](https://github.com/TitleCardMaker/Blueprints/assets/9253709/70cf71dc-5757-4b0f-a0dd-4555b5a7112c)

**Comment by CollinHeist** [comment]
@archieyates Yeah I think that looks really good - okay I edited the Blueprint and preview for you, so I think it's all good! /create-blueprint
