### ISSUE TITLE
[Blueprint] Sex and the City

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#272]
### Series Name

Sex and the City

### Series Year

1998

### Series Database IDs

imdb:tt0159206,tmdb:105,tvdb:76648

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style with logo placed at top of frame.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Sex and the City",
      "delete_missing": true,
      "file": "times.ttf",
      "size": 1.1,
      "stroke_width": 0.25,
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/8ca2203a-62bf-461f-b112-916fb0a496a0)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14045909/fonts.zip)

**Comment by CollinHeist** [comment]
@archieyates I usually recommend people include the logo as part of the Blueprint, if you think it adds to the Card (more than a generic one). Did you want to do that? If so, just zip it and place that in the Source Files section

**Comment by archieyates** [comment]
I mean that's just the logo that was downloaded automatically when I added the series but if you'd prefer I added it to the blueprint I can do that tomorrow evening :)

**Comment by CollinHeist** [comment]
I don't have a preference, it's up to you. Some people make Blueprints w/ really specific logos in mind

**Comment by CollinHeist** [comment]
I don't have a preference, it's up to you. Some people make Blueprints w/ really specific logos in mind, that's all

/create-blueprint
