### ISSUE TITLE
[Blueprint] And Just Like That...

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#273]
### Series Name

And Just Like That...

### Series Year

2021

### Series Database IDs

imdb:tt13819960,tmdb:116450,tvdb:394924

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame card with logo placed at top of frame, and a custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s2e10": {
      "template_ids": [],
      "title": "The Last Supper: Appetizer",
      "match_title": false
    },
    "s2e11": {
      "template_ids": [],
      "title": "The Last Supper: Entr\u00e9e",
      "match_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Sex and the City",
      "delete_missing": true,
      "file": "times.ttf",
      "size": 1.1,
      "stroke_width": 0.25,
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/fd937e24-770c-4897-8dd7-455dbc63de8e)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14045900/fonts.zip)

**Comment by CollinHeist** [comment]
@archieyates Same as this one, did you want to include the logo?

**Comment by archieyates** [comment]
It's just the default one scraped by the tool but happy to add it in tomorrow if needs be.
