### ISSUE TITLE
[Blueprint] Percy Jackson and the Olympians

### ISSUE THREAD

**Issue by legacy3** [TitleCardMaker/Blueprints#277]
### Series Name

Percy Jackson and the Olympians

### Series Year

2023

### Series Database IDs

imdb:tt12324366,tmdb:103540,tvdb:415151

### Blueprint Description

A simple blueprint imitating the shows font and color. It emphasizes the episode title, which can be quite long. 

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Percy Jackson Disney",
      "color": "#8E7D7C",
      "delete_missing": true,
      "file": "Albertus Medium.ttf",
      "size": 1.1
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/20936924/e9b7e6bd-f3f0-41ea-a377-aa88500d5ade)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14050852/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks. /create-blueprint
