### ISSUE TITLE
[Blueprint] Digimon Adventure: 2020

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#279]
### Series Name

Digimon Adventure: 2020

### Series Year

2020

### Series Database IDs

imdb:tt11645760,tmdb:98034,tvdb:376003

### Creator Username

Reicha7

### Blueprint Description

Anime card type with kanji translation, a custom Font, and no season titles.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
     ],
    "card_type": "anime",
    "hide_season_text": true
  },
  "fonts": [
    {
      "name": "Digimon",
      "delete_missing": true,
      "file": "PixelDigivolve-mOm9.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/971a95c7-5f0b-4cad-895b-91723f652c84)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14058639/fonts.zip)

**Comment by CollinHeist** [comment]
@archieyates I think this would be a good candidate for a "Digimon" Template. Want me to do that for you?

**Comment by archieyates** [comment]
@CollinHeist certainly could do. Only reason I didn't is because I felt there were enough subtle differences between all the shows to not warrant it. Like they all use the same font but OG, Tamers, and Frontier don't include kanji (a personal choice since a lot of people grew up watching those dubbed). OG shows seasons whilst the rest don't since they're all single season.

Up to you though if you think it would benefit others more to have it templated :)

**Comment by CollinHeist** [comment]
Ah that makes sense! I'll leave it as-is, I didn't realize they were all different. /create-blueprint
