### ISSUE TITLE
[Blueprint] Digimon: Digital Monsters

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#283]
### Series Name

Digimon: Digital Monsters

### Series Year

1999

### Series Database IDs

imdb:tt0210418,tmdb:31654,tvdb:72241

### Creator Username

Reicha7

### Blueprint Description

Anime card type with a custom Font and season titles.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "season_title_ranges": [
      "1",
      "2"
    ],
    "season_title_values": [
      "Digimon Adventure",
      "Digimon Adventure 02"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Digimon",
      "delete_missing": true,
      "file": "PixelDigivolve-mOm9.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/97faaadc-0285-4d39-b2bc-4cc1ecdbf9c4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14058659/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks for submitting all of these! /create-blueprint
