### ISSUE TITLE
[Blueprint] The Watch

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#284]
### Series Name

The Watch

### Series Year

2021

### Series Database IDs

imdb:tt8080292,tmdb:94235,tvdb:369568

### Creator Username

Reicha7

### Blueprint Description

Comic book title card with custom fonts and colours themed off of the show's poster.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "banner_fill_color",
      "text_box_fill_color",
      "text_box_edge_color"
    ],
    "extra_values": [
      "rgb(29, 170, 249)",
      "rgba(220, 67, 151, 0.75)",
      "black",
      "rgb(239, 219, 0)"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Watch",
      "color": "#dc4397",
      "delete_missing": true,
      "file": "911porschav3.ttf",
      "size": 1.2
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/f592e8e8-ff20-46ed-ac2e-ef55bde7f8c6)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14059002/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks. /create-blueprint
