### ISSUE TITLE
[Blueprint] The Walking Dead

### ISSUE THREAD

**Issue by TyroFlakkripper** [TitleCardMaker/Blueprints#291]
### Series Name

The Walking Dead

### Series Year

2010

### Series Database IDs

imdb:tt1520211,tmdb:1402

### Creator Username

TyroFlakkripper

### Blueprint Description

Standard card with Walking Dead font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Walking Dead",
      "color": "white",
      "delete_missing": true,
      "file": "Dead Kansas.ttf",
      "size": 0.75,
      "stroke_width": 0.45,
      "title_case": "source"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![The Walking Dead (2010) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/156497767/1db95fba-f3f5-411f-98f1-765076919bf1)
![The Walking Dead (2010) - S02E06](https://github.com/TitleCardMaker/Blueprints/assets/156497767/1906a363-0768-4220-9ba2-0d4d1f3c164e)
![The Walking Dead (2010) - S04E06](https://github.com/TitleCardMaker/Blueprints/assets/156497767/523960d2-1228-4e91-aa07-d3389a193280)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14078666/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great - thanks! /create-blueprint
