### ISSUE TITLE
[Blueprint] Stephen King's IT

### ISSUE THREAD

**Issue by TyroFlakkripper** [TitleCardMaker/Blueprints#318]
### Series Name

Stephen King's IT

### Series Year

1990

### Series Database IDs

imdb:tt0099864,tmdb:19614,tvdb:113981

### Creator Username

TyroFlakkripper

### Blueprint Description

Inset card type with a custom font to try and match the show, font colored to red.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "inset",
    "hide_season_text": true,
    "hide_episode_text": true,
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "IT",
      "color": "#FF0000",
      "delete_missing": true,
      "file": "Top Secret.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/156497767/5f385e70-2a1c-4deb-ba27-8c21ad21e594)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14093091/fonts.zip)

**Comment by CollinHeist** [comment]
Ooh very cool, I like this. Thanks! /create-blueprint
