### ISSUE TITLE
[Blueprint] The Bear

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#333]
### Series Name

The Bear

### Series Year

2022

### Series Database IDs

imdb:tt14452776,tmdb:136315,tvdb:403294

### Creator Username

Reicha7

### Blueprint Description

Marvel-style card with border adjustments and a custom font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "marvel",
    "extra_keys": [
      "border_color",
      "text_box_height",
      "episode_text_location",
      "episode_text_color"
    ],
    "extra_values": [
      "black",
      "260",
      "compact",
      "white"
    ],
    "template_ids": [],
    "font_color": "#FFF7C8",
    "font_size": 2.0,
    "font_vertical_shift": -50,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "TV_Large",
      "delete_missing": true,
      "file": "impact.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/01821389-0e49-4f8a-8927-8733849ac8d4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14131318/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
