### ISSUE TITLE
[Blueprint] Big Mouth

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#335]
### Series Name

Big Mouth

### Series Year

2017

### Series Database IDs

imdb:tt6524350,tmdb:74204,tvdb:331431

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom font and an episode adjustment to fit 2 lines.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element",
      "frame_color",
      "frame_width",
      "separator"
    ],
    "extra_values": [
      "index",
      "title",
      "#f9d041",
      "8",
      "\u00b7"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s6e5": {
      "template_ids": [],
      "title": "Andrew's Gonna\\nTouch A Boob Tonight",
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Big Mouth",
      "delete_missing": true,
      "file": "Giants.ttf",
      "replacements_in": [
        "*"
      ],
      "replacements_out": [
        "-"
      ],
      "size": 1.5
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/b7fa0d43-83c4-40fc-9adc-ca79906581c2)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14132072/fonts.zip)

**Comment by CollinHeist** [comment]
Nice, thanks! /create-blueprint
