### ISSUE TITLE
[Blueprint] Taskmaster

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#341]
### Series Name

Taskmaster

### Series Year

2015

### Series Database IDs

imdb:tt4934214,tmdb:63404,tvdb:298905

### Creator Username

inapptom

### Blueprint Description

Standard card using a free variation of the Series font. Season and episode removed to match the in-show title card, and font size boosted slightly. The Final is removed from some series finales.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "match_titles": false,
    "font_size": 1.25,
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s14e10": {
      "template_ids": [],
      "title": "Did I Meet These Potatoes Before?"
    },
    "s15e10": {
      "template_ids": [],
      "title": "A Yardstick for Failure"
    },
    "s16e10": {
      "template_ids": [],
      "title": "Always Forks and Marbles"
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Taskmaster",
      "delete_missing": true,
      "file": "VeteranTypewriter.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/0b75ac58-5690-4bec-aff4-91621d032de4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14139653/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks /create-blueprint
