### ISSUE TITLE
[Blueprint] BoJack Horseman

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#345]
### Series Name

BoJack Horseman

### Series Year

2014

### Series Database IDs

imdb:tt3398228,tmdb:61222,tvdb:282254

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom font and logo instead of episode number.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element",
      "logo_size",
      "frame_width"
    ],
    "extra_values": [
      "logo",
      "title",
      "2",
      "6"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "BoJack Horseman",
      "delete_missing": true,
      "file": "Ness.ttf",
      "replacements_in": [
        "\u00cb",
        "\u00eb"
      ],
      "replacements_out": [
        "E",
        "e"
      ],
      "size": 1.05
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5a23bc09-af77-4018-a59f-c390e69f9db4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14146692/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
