### ISSUE TITLE
[Blueprint] Cadfael

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#346]
### Series Name

Cadfael

### Series Year

1994

### Series Database IDs

imdb:tt0108717,tmdb:35942,tvdb:77894

### Creator Username

Reicha7

### Blueprint Description

Standard card with a custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s3e2": {
      "template_ids": [],
      "title": "St. Peter's Fair",
      "match_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Cadfael",
      "delete_missing": true,
      "file": "OldEnglishFive.ttf",
      "title_case": "title"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/4dbbdfbb-239a-45cb-a004-5bdabf1e3c79)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14149060/fonts.zip)

**Comment by CollinHeist** [comment]
Nice - I haven't heard of this Series before. /create-blueprint
