### ISSUE TITLE
[Blueprint] Chernobyl

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#347]
### Series Name

Chernobyl

### Series Year

2019

### Series Database IDs

imdb:tt7366338,tmdb:87108,tvdb:360893

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame with custom font, removal of stroke, and logo at top of frame.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "hide_season_text": true,
    "extra_keys": [
      "top_element",
      "bottom_element",
      "frame_width"
    ],
    "extra_values": [
      "logo",
      "title",
      "10"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Chernobyl",
      "delete_missing": true,
      "file": "Hillstown Sans Clean Demo.otf",
      "size": 1.25
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/3d625b81-6743-4c8e-85dd-a8384a48cc86)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14149380/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks!
