### ISSUE TITLE
[Blueprint] Beast Wars: Transformers

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#350]
### Series Name

Beast Wars: Transformers

### Series Year

1996

### Series Database IDs

imdb:tt0115108,tmdb:958,tvdb:73562

### Creator Username

Reicha7

### Blueprint Description

Logo-style card with a custom font. The actual episode previews are too low res for good thumbnails. Logo is included.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "logo",
    "template_ids": [],
    "font_size": 1.5,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Transformers",
      "color": "#e9f6f8",
      "delete_missing": true,
      "file": "Transformers Movie.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/98ef5b33-6f67-4e5e-928e-2ee329dda3f6)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14151884/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14151887/source.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
