### ISSUE TITLE
[Blueprint] Codename: Kids Next Door

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#351]
### Series Name

Codename: Kids Next Door

### Series Year

1998

### Series Database IDs

imdb:tt0312109,tmdb:2660,tvdb:71685

### Creator Username

Reicha7

### Blueprint Description

Logo style card with a custom Font and custom episode name formatting to force a newline after "operation:" in the Episode title. Also included is a modified logo which is much more visually centered.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "logo",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "title_text_format"
    ],
    "extra_values": [
      "{f':{NEWLINE}'.join(title_text.split(\": \"))}"
    ],
    "skip_localized_images": true
  },
  "episodes": {
    "s0e2": {
      "template_ids": [],
      "title": "The Grim Adventures\\nof the Kids Next Door",
      "match_title": false,
      "auto_split_title": false
    },
    "s1e2": {
      "template_ids": [],
      "title": "Kenny and the Chimp:\\nDiseasy Does It!\\nOr Chimp N'Pox",
      "match_title": false,
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Kids Next Door",
      "interline_spacing": 25,
      "delete_missing": true,
      "file": "whitrabt.ttf",
      "title_case": "lower"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/1c622a4e-61e0-4308-8d33-2d5a589d0846)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14152267/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14152268/source.zip)

**Comment by CollinHeist** [comment]
Love this! /create-blueprint
