### ISSUE TITLE
[Blueprint] Ed, Edd n Eddy

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#353]
### Series Name

Ed, Edd n Eddy

### Series Year

1999

### Series Database IDs

imdb:tt0184111,tmdb:606,tvdb:77466

### Creator Username

Reicha7

### Blueprint Description

All the official title cards (apart from a few specials) for the Series already formatted to fit a 16:9 resolution so they don't get cropped.

### Blueprint

```json
{
  "series": {
    "card_type": "textless",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/767f44dc-a0cb-40a1-b235-aa81af3d68dd)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14152581/source.zip)

**Comment by CollinHeist** [comment]
Awesome, thanks! /create-blueprint
