### ISSUE TITLE
[Blueprint] House of the Dragon

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#356]
### Series Name

House of the Dragon

### Series Year

2022

### Series Database IDs

imdb:tt11198330,tmdb:94997,tvdb:371572

### Creator Username

azuravian, Reicha7

### Blueprint Description

Uses azuravian's TitleColorMatch card type with the Game of Thrones font coloured to match the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "azuravian/TitleColorMatch"
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Game of Thrones",
      "color": "#d2af83",
      "delete_missing": true,
      "file": "Game of Thrones.ttf",
      "size": 0.85
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/f77f635c-d49b-4a6d-b795-f7546158eb1c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14154449/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
