### ISSUE TITLE
[Blueprint] The Lord of the Rings: The Rings of Power

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#357]
### Series Name

The Lord of the Rings: The Rings of Power

### Series Year

2022

### Series Database IDs

imdb:tt7631058,tmdb:84773,tvdb:367506

### Creator Username

Reicha7

### Blueprint Description

Landscape style card with custom font and an offset to frame the thumbnail.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "landscape",
    "extra_keys": [
      "box_adjustments"
    ],
    "extra_values": [
      "-3 0 -30 0"
    ],
    "template_ids": [],
    "font_color": "#d9e2e4",
    "font_size": 1.25,
    "font_vertical_shift": 500,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Lord of the Rings",
      "color": "#D1C6AA",
      "delete_missing": true,
      "file": "ringbearer.ttf",
      "stroke_width": 0.8,
      "title_case": "source"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/914ce6b8-9d4d-4373-9f83-5a5464d524ab)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14154480/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint
