### ISSUE TITLE
[Blueprint] Kingdom

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#358]
### Series Name

Kingdom

### Series Year

2019

### Series Database IDs

imdb:tt6611916,tmdb:70593,tvdb:355228

### Creator Username

Reicha7

### Blueprint Description

Basic card with removal of "Kingdom" from the Specials

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "episodes": {
    "s0e1": {
      "template_ids": [],
      "title": "Ashin of the North",
      "match_title": true
    }
  },
  "fonts": [
    {
      "name": "Kingdom",
      "delete_missing": true,
      "file": "Baanoo.ttf",
      "size": 2.0,
      "stroke_width": 0.5,
      "title_case": "title"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/d6974e14-4d10-4e8e-be2b-bb8aadf2447b)

### Zip of Font Files

[Baanoo.ttf.zip](https://github.com/TitleCardMaker/Blueprints/files/14157900/Baanoo.ttf.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
