### ISSUE TITLE
[Blueprint] Alice in Borderland

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#359]
### Series Name

Alice in Borderland

### Series Year

2020

### Series Database IDs

imdb:tt10795658,tmdb:110316,tvdb:376472

### Creator Username

Reicha7

### Blueprint Description

Simple card that uses a custom card-themed font to match the show, Displays episode number in roman numerals.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "title_text_format"
    ],
    "extra_values": [
      "Episode {to_roman_numeral(episode_number)}\t"
    ]
  },
  "fonts": [
    {
      "name": "Alice in Borderland",
      "delete_missing": true,
      "file": "RoyalFlush-Regular.ttf",
      "interword_spacing": 100,
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/b64d9b87-088c-4b0b-a678-98dab8470681)

### Zip of Font Files

[RoyalFlush-Regular.ttf.zip](https://github.com/TitleCardMaker/Blueprints/files/14157891/RoyalFlush-Regular.ttf.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
