### ISSUE TITLE
[Blueprint] Hey Arnold!

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#361]
### Series Name

Hey Arnold!

### Series Year

1996

### Series Database IDs

imdb:tt0115200,tmdb:537,tvdb:72005

### Creator Username

PJ

### Blueprint Description

Standard card title with Hey-Arnold font and color

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "Hey Arnold",
      "color": "#f7d400",
      "delete_missing": true,
      "file": "ARNORG__.TTF",
      "interline_spacing": -20,
      "stroke_width": 1.2
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/45070803/33cdc919-8323-43d9-ada2-98e7953cd560)

### Zip of Font Files

[fonts](https://github.com/TitleCardMaker/Blueprints/files/14215497/fonts.zip)

**Comment by CollinHeist** [comment]
@PJGitHub9 Sorry for the delay. Looks like the font zip is corrupt for some reason. Could you re-upload that?

**Comment by PJGitHub9** [comment]
@CollinHeist no worries! Let me know if this works :) 
[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14215497/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
