### ISSUE TITLE
[Blueprint] Star Wars Rebels

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#362]
### Series Name

Star Wars Rebels

### Series Year

2014

### Series Database IDs

imdb:tt2930604,tmdb:60554,tvdb:283468

### Creator Username

Reicha7

### Blueprint Description

Star Wars card with episode text removed from the specials.

### Blueprint

```json
{
  "series": {
    "card_type": "star wars",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s0e5": {
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e6": {
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e7": {
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e8": {
      "hide_episode_text": true,
      "template_ids": []
    }
  },
  "templates": [],
  "fonts": [],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/c60e0620-7a63-47be-83fd-c32207188202)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
