### ISSUE TITLE
[Blueprint] All of Us Are Dead

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#365]
### Series Name

All of Us Are Dead

### Series Year

2022

### Series Database IDs

imdb:tt14169960,tmdb:99966,tvdb:382142

### Creator Username

Reicha7

### Blueprint Description

Simple card with custom Font and no season or episode text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "All Of Us Are Dead",
      "delete_missing": true,
      "file": "zombnze.ttf",
      "size": 2.0,
      "stroke_width": 0.05
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/317cee85-289a-4c70-b80a-458f548c259a)

### Zip of Font Files

[zombnze.ttf.zip](https://github.com/TitleCardMaker/Blueprints/files/14160778/zombnze.ttf.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
