### ISSUE TITLE
[Blueprint] The Last of Us

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#367]
### Series Name

The Last of Us

### Series Year

2023

### Series Database IDs

imdb:tt3581920,tmdb:100088,tvdb:392256

### Creator Username

Reicha7

### Blueprint Description

Simple card with custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Last Of Us",
      "delete_missing": true,
      "file": "The Last Of Us Rough.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/8fd17d4a-2796-4ecf-8b49-91831cb2a3e0)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14159201/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks

/create-blueprint
