### ISSUE TITLE
[Blueprint] Airwolf

### ISSUE THREAD

**Issue by Dragonsys** [TitleCardMaker/Blueprints#368]
### Series Name

Airwolf

### Series Year

1984

### Series Database IDs

imdb:tt0086662,tmdb:2119,tvdb:73200

### Creator Username

Dragonsys

### Blueprint Description

Standard card with custom Font to match title font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Airwolf",
      "color": "red",
      "delete_missing": true,
      "file": "BORG9.TTF",
      "replacements_in": [
        "^",
        "@"
      ],
      "replacements_out": [
        "",
        ""
      ],
      "size": 1.1,
      "stroke_width": 3.0,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/16159001/5f9fccd0-c485-4dfc-a470-0587035f3d97)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14160520/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! Thanks. /create-blueprint
