### ISSUE TITLE
[Blueprint] My Name

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#372]
### Series Name

My Name

### Series Year

2021

### Series Database IDs

imdb:tt12940504,tmdb:110356,tvdb:397441

### Creator Username

Reicha7

### Blueprint Description

Simple blueprint with custom Font and no season or episode text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "My Name",
      "delete_missing": true,
      "file": "roughriders.script-typeface.ttf",
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/38ea66b8-647e-4ca9-9245-e9042c7c81f8)

### Zip of Font Files

[roughriders.script-typeface.ttf.zip](https://github.com/TitleCardMaker/Blueprints/files/14173024/roughriders.script-typeface.ttf.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
