### ISSUE TITLE
[Blueprint] ONE PIECE

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#373]
### Series Name

ONE PIECE

### Series Year

2023

### Series Database IDs

imdb:tt11737520,tmdb:111110,tvdb:392276

### Creator Username

Reicha7, CollinHeist

### Blueprint Description

Tinted Frame card with series Font (thanks CollinHeist) and custom frame color to match Luffy's waistcoat.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "hide_season_text": true,
    "extra_keys": [
      "bottom_element",
      "top_element",
      "logo_size",
      "frame_color",
      "frame_width"
    ],
    "extra_values": [
      "title",
      "logo",
      "1.5",
      "red",
      "6"
    ]
  },
  "fonts": [
    {
      "name": "One Piece",
      "color": "rgb(98,155,211)",
      "delete_missing": true,
      "file": "one piece font.ttf",
      "size": 1.5,
      "stroke_width": 0.7
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/d1ed35ee-fe99-4c9b-82ac-1ff76e87f4b8)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14172703/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint
