### ISSUE TITLE
[Blueprint] Dinosaurs

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#374]
### Series Name

Dinosaurs

### Series Year

1991

### Series Database IDs

imdb:tt0101081,tmdb:3763,tvdb:76461

### Creator Username

Reicha7

### Blueprint Description

Logo style card with custom logo, backdrop, font, and some episode name fixes to drop them to new lines.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "logo",
    "episode_text_format": "Episode {to_cardinal(episode_number)}",
    "season_title_ranges": [
      "1",
      "2",
      "3",
      "4"
    ],
    "season_title_values": [
      "Season One",
      "Season Two",
      "Season Three",
      "Season Four"
    ],
    "extra_keys": [
      "use_background_image"
    ],
    "extra_values": [
      "true"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s2e13": {
      "template_ids": [],
      "title": "What 'Sexual Harris'\\nMeant",
      "match_title": false,
      "auto_split_title": false
    },
    "s2e18": {
      "template_ids": [],
      "title": "The Last Temptation\\nof Ethyl",
      "match_title": false,
      "auto_split_title": false
    },
    "s3e21": {
      "template_ids": [],
      "title": "Charlene and Her\\nAmazing Humans",
      "match_title": false,
      "auto_split_title": false
    },
    "s4e7": {
      "template_ids": [],
      "title": "The Greatest Story\\nEver Sold",
      "match_title": false,
      "auto_split_title": false
    },
    "s4e8": {
      "template_ids": [],
      "title": "Variations on a\\nTheme Park",
      "match_title": false,
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Dinosaurs",
      "color": "#e7743c",
      "delete_missing": true,
      "file": "before-collapse.regular.ttf",
      "size": 1.25,
      "stroke_width": 0.25,
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/02a7ce3d-02df-464d-a0df-e3ba4d1e6f00)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14172908/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14172909/source.zip)

**Comment by CollinHeist** [comment]
@archieyates Looks great - thanks! For future reference, you can do the same formatting for season titles, e.g. you could do a season text format (extra) as `Season {to_cardinal(season_number)}` or a season title range of `s1e1-s4e99` of `Season {to_cardinal(season_number)}`.

Obviously not necessary, just as an FYI. /create-blueprint

**Comment by archieyates** [comment]
Ah yeah I forgot about that extra!
