### ISSUE TITLE
[Blueprint] Hellbound

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#375]
### Series Name

Hellbound

### Series Year

2021

### Series Database IDs

imdb:tt12235718,tmdb:106651,tvdb:397444

### Creator Username

Reicha7

### Blueprint Description

Standard title card formatted to add additional spacing between each title character to match the style of the poster.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "title_text_format"
    ],
    "extra_values": [
      "{\"   \".join(title_text)}"
    ],
    "template_ids": [
      0
    ],
    "font_size": 1.5,
    "source_files": []
  },
  "episodes": {
    "s1e1": {
      "template_ids": [],
      "title": "Episode1",
      "match_title": false
    },
    "s1e2": {
      "template_ids": [],
      "title": "Episode2",
      "match_title": false
    },
    "s1e3": {
      "template_ids": [],
      "title": "Episode3",
      "match_title": false
    },
    "s1e4": {
      "template_ids": [],
      "title": "Episode4",
      "match_title": false
    },
    "s1e5": {
      "template_ids": [],
      "title": "Episode5",
      "match_title": false
    },
    "s1e6": {
      "template_ids": [],
      "title": "Episode6",
      "match_title": false
    }
  },
  "templates": [
    {
      "font_id": 1,
      "card_type": "standard",
      "hide_season_text": true,
      "hide_episode_text": true,
      "name": "TV_Name_Only",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Hellbound",
      "delete_missing": true,
      "file": "WindsorOpti-LightCondensed.otf",
      "stroke_width": 0.25,
      "title_case": "upper"
    },
    {
      "name": "TV_Large",
      "delete_missing": true,
      "file": "impact.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/b9d4ff58-391e-47b9-b868-f7d9a5f76ccc)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14173213/fonts.zip)

**Comment by CollinHeist** [comment]
Did adjusting the kerning / interword spacing not work? Just curious

**Comment by archieyates** [comment]
Since it's just basically the one word I didn't think about interword spacing. As for kerning I did try setting it to 1 when testing just the font and it didn't seem to do anything. Accidentally set it to a stupidly high number and did see it crush the text though.

**Comment by CollinHeist** [comment]
Yeah the interword spacing would only affect between the episode and number, and for the kerning you'd probably have to go negative, it is really picky to find the right value. But really just wondering, haha. I like your space solution

**Comment by archieyates** [comment]
Didn't realise it could go negative. I thought it was a percentage to be honest! I'll keep that in mind for next time though!

**Comment by CollinHeist** [comment]
It is a percentage, but you can have negative percentages, haha. Sounds good - thanks for submitting this! /create-blueprint
