### ISSUE TITLE
[Blueprint] Gen V

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#386]
### Series Name

Gen V

### Series Year

2023

### Series Database IDs

imdb:tt13159924,tmdb:205715,tvdb:417909

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with colour matching for the show and some custom title splits for certain episodes.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element",
      "logo_size",
      "frame_color",
      "frame_width"
    ],
    "extra_values": [
      "logo",
      "title",
      "2",
      "white",
      "12"
    ],
    "template_ids": [],
    "font_color": "#dcf216",
    "source_files": []
  },
  "episodes": {
    "s1e5": {
      "template_ids": [],
      "title": "Welcome to the\\nMonster Club",
      "match_title": false,
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "The Boys",
      "color": "#EC1B17",
      "delete_missing": true,
      "file": "Charlie don't surf.ttf",
      "size": 1.5,
      "stroke_width": 0.2,
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/f972b9dd-74bb-48f0-8fd5-2973976246c2)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14202892/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
