### ISSUE TITLE
[Blueprint] The 10th Kingdom

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#391]
### Series Name

The 10th Kingdom

### Series Year

2000

### Series Database IDs

imdb:tt0207275,tmdb:40546,tvdb:78886

### Creator Username

inapptom

### Blueprint Description

Tinted Frame with logo on top, episode name on bottom. Color and Font are matched to the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "font_color": "rgb(250,226,208)",
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "10th Kingdom",
      "delete_missing": true,
      "file": "Mason Regular.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/3f10ce83-06bc-49a8-b371-3116d0a2d9c8)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14209127/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14219763/source.zip)

**Comment by CollinHeist** [comment]
@thomaswilliamsastro Hey, thanks for submitting this! Did you want to include the logo in this? If not, that's fine, just checking

**Comment by thomaswilliamsastro** [comment]
@CollinHeist yes, sorry! Just updated with the file, don't know if it needs to be zipped though

**Comment by thomaswilliamsastro** [comment]
seems it does, updated now

**Comment by CollinHeist** [comment]
Yeah it does - thanks! Looks great. /create-blueprint
