### ISSUE TITLE
[Blueprint] Watchmen

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#392]
### Series Name

Watchmen

### Series Year

2019

### Series Database IDs

imdb:tt7049682,tmdb:79788,tvdb:360733

### Creator Username

Reicha7

### Blueprint Description

Comic style card with custom font and colour matching with the show's poster.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "hide_season_text": true,
    "extra_keys": [
      "text_box_fill_color",
      "episode_text_color",
      "banner_fill_color",
      "index_text_position",
      "index_text_rotation_angle",
      "title_text_rotation_angle",
      "index_banner_shift"
    ],
    "extra_values": [
      "black",
      "#fae200",
      "rgba(5, 18, 68, 0.9)",
      "right",
      "4",
      "-3",
      "20"
    ],
    "template_ids": [],
    "font_color": "#fae200",
    "font_size": 1.5,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "TV_Large",
      "delete_missing": true,
      "file": "impact.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/bbaeda74-fd00-4eef-8757-39414932b614)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14215168/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks. /create-blueprint
