### ISSUE TITLE
[Blueprint] Hazbin Hotel

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#393]
### Series Name

Hazbin Hotel

### Series Year

2024

### Series Database IDs

imdb:tt7216636,tmdb:94954,tvdb:358805

### Creator Username

Reicha7

### Blueprint Description

Tinted Glass style card that tries to mimic the look of the light-up signs at motels. Some custom episode editing including a textless card for the pilot.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted glass",
    "extra_keys": [
      "glass_color",
      "episode_text_color"
    ],
    "extra_values": [
      "rgba(238, 2, 66, 0.7)",
      "#ffffe5"
    ],
    "template_ids": [],
    "font_size": 1.2,
    "font_stroke_width": 0.0,
    "font_vertical_shift": -51,
    "source_files": []
  },
  "episodes": {
    "s0e1": {
      "card_type": "textless",
      "template_ids": [],
      "episode_text": "Pilot"
    },
    "s1e2": {
      "template_ids": [],
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Vegas Sign",
      "color": "#ffffe5",
      "delete_missing": true,
      "file": "budmo jiggler.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/c44b4d79-306c-484c-b42c-7eb59132803b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14215603/fonts.zip)

**Comment by CollinHeist** [comment]
This looks awesome - nice job! /create-blueprint
