### ISSUE TITLE
[Blueprint] This Country

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#396]
### Series Name

This Country

### Series Year

2017

### Series Database IDs

imdb:tt6583806,tmdb:70596,tvdb:323311

### Creator Username

inapptom

### Blueprint Description

Uses Standard card style, but with the show font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "This Country",
      "delete_missing": true,
      "file": "OPTIFranklinGothic-Medium.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/9a45cb2f-2aa4-41c5-9e0b-a49bf486969d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14222922/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks for submitting this! /create-blueprint
