### ISSUE TITLE
[Blueprint] Modern Family

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#398]
### Series Name

Modern Family

### Series Year

2009

### Series Database IDs

imdb:tt1442437,tmdb:1421,tvdb:95011

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom fonts and colouring to match the show.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_font",
      "frame_color",
      "episode_text_font_size"
    ],
    "extra_values": [
      "OPTITimes-Roman.otf",
      "#ef481b",
      "1.5"
    ]
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Modern Family",
      "delete_missing": true,
      "file": "Helvetica.ttf",
      "size": 1.5,
      "stroke_width": 0.5,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/36277ea5-e79d-4329-9ac4-cdbaad18c0fb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14226639/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14226641/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
