### ISSUE TITLE
[Blueprint] Silo

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#399]
### Series Name

Silo

### Series Year

2023

### Series Database IDs

imdb:tt14688458,tmdb:125988,tvdb:403245

### Creator Username

Reicha7

### Blueprint Description

Standard Card with custom font and some kerning to make it match the spacing of the logo

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0,
    "font_size": 1.2,
    "font_kerning": -50.0
  },
  "fonts": [
    {
      "name": "TV_Large",
      "delete_missing": true,
      "file": "impact.ttf",
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/e62742d2-831d-43eb-aa7d-e62d3f9a1952)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14226680/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks 👍🏻 /create-blueprint
