### ISSUE TITLE
[Blueprint] Doc Martin

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#400]
### Series Name

Doc Martin

### Series Year

2004

### Series Database IDs

imdb:tt0408381,tmdb:2430,tvdb:79285

### Creator Username

Reicha7

### Blueprint Description

Shape-style card with a Font designed to look like doctor's handwriting and medical coloring. Includes an override of the name of the 2022 Christmas Special

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "shape",
    "hide_season_text": true,
    "extra_keys": [
      "season_text_color",
      "shape_color"
    ],
    "extra_values": [
      "white",
      "red"
    ]
  },
  "episodes": {
    "s0e10": {
      "hide_season_text": false,
      "hide_episode_text": true,
      "template_ids": [],
      "title": "Last Christmas in Portwenn",
      "match_title": false,
      "season_text": "2022 Christmas Special"
    },
    "s1e5": {
      "template_ids": [],
      "auto_split_title": false
    }
  },
  "fonts": [
    {
      "name": "Doc Martin",
      "delete_missing": true,
      "file": "Original Handwriting.ttf",
      "stroke_width": 0.25,
      "title_case": "title"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5be9f98b-12a8-429b-930a-1dd6a19fa364)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14226996/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good 👍🏻 /create-blueprint
