### ISSUE TITLE
[Blueprint] Fawlty Towers

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#405]
### Series Name

Fawlty Towers

### Series Year

1975

### Series Database IDs

imdb:tt0072500,tmdb:2207,tvdb:75932

### Creator Username

Reicha7

### Blueprint Description

Comic Style card with the banners removed to create a mimic of the original Fawlty Towers sign.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "hide_title_banner",
      "hide_index_banner",
      "title_text_rotation_angle"
    ],
    "extra_values": [
      "true",
      "true",
      "4"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Fawlty Towers",
      "color": "black",
      "delete_missing": true,
      "file": "OPTIBelwe-Medium.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/092928ef-f0c5-45cf-a788-679dc1064d0d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14234368/fonts.zip)

**Comment by CollinHeist** [comment]
Nice! /create-blueprint
