### ISSUE TITLE
[Blueprint] Xiaolin Showdown

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#406]
### Series Name

Xiaolin Showdown

### Series Year

2003

### Series Database IDs

imdb:tt0386993,tmdb:679,tvdb:72245

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom Font and series color matching.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "bottom_element",
      "top_element",
      "frame_color",
      "frame_width",
      "logo_size"
    ],
    "extra_values": [
      "title",
      "logo",
      "#e32a26",
      "20",
      "2"
    ]
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Xiaolin",
      "color": "#fff200",
      "delete_missing": true,
      "file": "CHINESETAKEAWAY.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/457c98c9-651c-4d3a-9d57-aa4812f35100)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14234444/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14234445/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
