### ISSUE TITLE
[Blueprint] Xiaolin Chronicles

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#407]
### Series Name

Xiaolin Chronicles

### Series Year

2013

### Series Database IDs

imdb:tt2824770,tmdb:60306,tvdb:272647

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom Font and series color matching

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "bottom_element",
      "top_element",
      "frame_color",
      "frame_width",
      "logo_size"
    ],
    "extra_values": [
      "title",
      "logo",
      "#e32a26",
      "20",
      "2"
    ]
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Xiaolin",
      "color": "#fff200",
      "delete_missing": true,
      "file": "CHINESETAKEAWAY.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5369cb45-339e-434d-8f40-24ab250aabe4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14234472/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14234473/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
