### ISSUE TITLE
[Blueprint] Star Trek

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#411]
### Series Name

Star Trek

### Series Year

1966

### Series Database IDs

imdb:tt0060028,tmdb:253,tvdb:77526

### Creator Username

Reicha7

### Blueprint Description

Fade style card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "fade",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s0e1": {
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e2": {
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e3": {
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e4": {
      "hide_episode_text": true,
      "template_ids": []
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Star Trek",
      "delete_missing": true,
      "file": "TOS_Title.ttf",
      "size": 1.6
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/8250337f-b151-4cba-ada4-cc063b83092d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14252644/fonts.zip)

**Comment by CollinHeist** [comment]
That image! 💯 Haha I love it. /create-blueprint
