### ISSUE TITLE
[Blueprint] Star Trek: The Next Generation

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#412]
### Series Name

Star Trek: The Next Generation

### Series Year

1987

### Series Database IDs

imdb:tt0092455,tmdb:655,tvdb:71470

### Creator Username

Reicha7

### Blueprint Description

Fade style card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "fade",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Star Trek Next Generation",
      "delete_missing": true,
      "file": "TNG_Credits.ttf",
      "size": 0.9
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/59ef4af4-99e2-4107-aa9d-2205081ea297)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14252709/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
