### ISSUE TITLE
[Blueprint] Star Trek: Deep Space Nine

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#413]
### Series Name

Star Trek: Deep Space Nine

### Series Year

1993

### Series Database IDs

imdb:tt0106145,tmdb:580,tvdb:72073

### Creator Username

Reicha7

### Blueprint Description

Fade style card with custom font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "fade",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Deep Space Nine",
      "delete_missing": true,
      "file": "DS9_Title.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/ae36beb4-9df4-4ef8-b84b-c2f2a9b82b52)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14253332/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
