### ISSUE TITLE
[Blueprint] Squid Game: The Challenge

### ISSUE THREAD

**Issue by dmandrone** [TitleCardMaker/Blueprints#416]
### Series Name

Squid Game: The Challenge

### Series Year

2023

### Series Database IDs

imdb:tt28104766,tmdb:204082,tvdb:421260

### Creator Username

Cloudburst, CollinHeist

### Blueprint Description

Migration of CollinHeist's template for the original Squid Game series.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "rgb(208,72,123)"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Squid Game",
      "delete_missing": true,
      "file": "GameOfSquids.ttf",
      "interline_spacing": -40,
      "size": 1.1,
      "vertical_shift": -10
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/19500231/58b73a28-9f22-48c0-82b5-8c03027e395f)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14256667/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great - thanks! /create-blueprint
