### ISSUE TITLE
[Blueprint] Why Women Kill

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#418]
### Series Name

Why Women Kill

### Series Year

2019

### Series Database IDs

imdb:tt9054904,tmdb:87428,tvdb:365069

### Creator Username

inapptom

### Blueprint Description

Standard card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Why Women Kill",
      "delete_missing": true,
      "file": "Core Sans N 45 Regular.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/f07f5909-98e0-4f5e-a39e-f3130f893196)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14258179/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
