### ISSUE TITLE
[Blueprint] The Silent Sea

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#419]
### Series Name

The Silent Sea

### Series Year

2021

### Series Database IDs

imdb:tt11570202,tmdb:96777,tvdb:383137

### Creator Username

Reicha7

### Blueprint Description

Star Wars style card with a custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "star wars",
    "hide_season_text": true,
    "episode_text_format": "Episode {episode_number}",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Silent Sea",
      "color": "white",
      "delete_missing": true,
      "file": "Rajdhani-Regular.ttf",
      "stroke_width": 0.15,
      "interline_spacing": -50
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/f19df7f8-4d5e-4eaf-ab7b-21b6d645c464)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14272496/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
