### ISSUE TITLE
[Blueprint] For All Mankind

### ISSUE THREAD

**Issue by foux** [TitleCardMaker/Blueprints#42]
### Series Name

For All Mankind

### Series Year

2019

### Series Database IDs

imdb:tt7772588,tmdb:87917,tvdb:356202

### Creator Username

foux

### Blueprint Description

Tinted frame with white logo and Nasalization font. The logo file is included.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Nasalization",
      "delete_missing": true,
      "file": "nasalization-rg.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/246550/ea56e7e9-1b71-41f6-8541-4ef382630178)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13392636/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/13394261/source.zip)

**Comment by CollinHeist** [comment]
@foux Did you want to include that logo in the Blueprint?

**Comment by foux** [comment]
No. Where should I include it?

**Comment by CollinHeist** [comment]
Well if you don't want to include it that's okay, I was just checking. But if you do then yes in a `.zip` folder named `logo.png` (in the last part of the issue)

**Comment by foux** [comment]
> Well if you don't want to include it that's okay, I was just checking. But if you do then yes in a `.zip` folder named `logo.png` (in the last part of the issue)

Gotcha. I'll do it later tonight, because it's better with this logo

**Comment by CollinHeist** [comment]
I believe I found it on TMDb - there is this one:

https://www.themoviedb.org/t/p/original/1cTZRkonTo1ZfJl8aHsL0kiuLet.png

and this one (different, but perhaps you like more as it matches the titles):

https://www.themoviedb.org/t/p/original/du8cDKiXRIhOz6aFWuX5eDUxVGI.svg

**Comment by foux** [comment]
I've updated the original message with logo.png inside the source.zip file
