### ISSUE TITLE
[Blueprint] Godzilla: The Series

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#421]
### Series Name

Godzilla: The Series

### Series Year

1998

### Series Database IDs

imdb:tt0177443,tmdb:11100,tvdb:76061

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with series Font colored to match the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "frame_color",
      "frame_width",
      "top_element",
      "bottom_element",
      "shadow_color"
    ],
    "extra_values": [
      "black",
      "20",
      "logo",
      "title",
      "#5bb623"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Godzilla 1998",
      "color": "black",
      "delete_missing": true,
      "file": "PLAIO___.TTF",
      "size": 0.75
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/2108082c-a0c8-4781-8362-cd107ed4a152)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14273327/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good, thanks! /create-blueprint
