### ISSUE TITLE
[Blueprint] Physical: 100

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#422]
### Series Name

Physical: 100

### Series Year

2023

### Series Database IDs

imdb:tt25274446,tmdb:210905,tvdb:424941

### Creator Username

Reicha7

### Blueprint Description

Standard title card with custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "omit_gradient",
      "episode_text_font_size"
    ],
    "extra_values": [
      "true",
      "1.4"
    ],
    "template_ids": [],
    "font_stroke_width": 0.25,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Physical 100",
      "delete_missing": true,
      "file": "gravtrac compressed bd.otf",
      "size": 1.5
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/82ed2de7-7fd7-45de-bd89-405bb91fbb1b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14273829/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
