### ISSUE TITLE
[Blueprint] The Traitors (UK)

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#424]
### Series Name

The Traitors (UK)

### Series Year

2022

### Series Database IDs

imdb:tt23743442,tmdb:215307,tvdb:420543

### Creator Username

inapptom

### Blueprint Description

Tinted frame with logo/title. Logo size in increased for readability. Custom font similar to the show is used

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "logo",
      "title",
      "1.5"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Traitors",
      "delete_missing": true,
      "file": "dilemma-serif-bold.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/4921754c-9b51-4043-95a9-b74638953a0f)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14277334/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14277354/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
