### ISSUE TITLE
[Blueprint] The Traitors (US)

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#425]
### Series Name

The Traitors (US)

### Series Year

2023

### Series Database IDs

imdb:tt15557874,tmdb:215943,tvdb:428163

### Creator Username

inapptom

### Blueprint Description

Tinted frame with logo/title. Custom font similar to the show is used, and font colour matched to logo

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "font_color": "rgb(231,218,170)",
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Traitors",
      "delete_missing": true,
      "file": "dilemma-serif-bold.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/4d7f850f-8d91-468c-b40f-7b4985ac4309)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14277390/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14277395/source.zip)

**Comment by CollinHeist** [comment]
Look great - thanks! /create-blueprint
