### ISSUE TITLE
[Blueprint] The Traitors: Uncloaked

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#426]
### Series Name

The Traitors: Uncloaked

### Series Year

2024

### Series Database IDs

imdb:tt30490874,tmdb:242476,tvdb:443705

### Creator Username

inapptom

### Blueprint Description

Tinted frame with title, top omitted. Custom font similar to the show is used

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "bottom_element",
      "top_element"
    ],
    "extra_values": [
      "title",
      "omit"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Traitors",
      "delete_missing": true,
      "file": "dilemma-serif-bold.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/32936518/1bc65d84-50be-42a7-9103-e21afad08836)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14277409/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks 👍🏻 /create-blueprint
