### ISSUE TITLE
[Blueprint] Alienators: Evolution Continues

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#429]
### Series Name

Alienators: Evolution Continues

### Series Year

2001

### Series Database IDs

imdb:tt0303419,tmdb:10003,tvdb:249611

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame Title Card with custom Font and series-matching colors. Based on the UK version of the show: "Evolution: The Animated Series".

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "frame_color",
      "frame_width",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "#11c212",
      "8",
      "logo",
      "title",
      "2.5"
    ]
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Inter Medium",
      "color": "#d8c855",
      "delete_missing": true,
      "file": "Inter-Medium.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/71717ea3-6c2d-4d48-b3aa-80ec35d95f23)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14289644/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
