### ISSUE TITLE
[Blueprint] Desperate Housewives

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#430]
### Series Name

Desperate Housewives

### Series Year

2004

### Series Database IDs

imdb:tt0410975,tmdb:693,tvdb:73800

### Creator Username

Reicha7

### Blueprint Description

Standard style card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "font_size": 1.0,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "TV_Large",
      "delete_missing": true,
      "file": "impact.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/a16bb75f-70e1-4d6b-8b61-a9796c0df623)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14289831/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
