### ISSUE TITLE
[Blueprint] X-Men: Evolution

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#436]
### Series Name

X-Men: Evolution

### Series Year

2000

### Series Database IDs

imdb:tt0247827,tmdb:668,tvdb:71168

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom Font, and logo and text color matching.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "frame_color",
      "frame_width",
      "middle_element",
      "logo_vertical_shift",
      "shadow_color"
    ],
    "extra_values": [
      "#f0f7f8",
      "1.25",
      "#cdd1d1",
      "12",
      "logo",
      "450",
      "#b60203"
    ],
    "font_color": "#f0f7f8"
  },
  "fonts": [
    {
      "name": "X-Men",
      "color": "#e9e9e9",
      "delete_missing": true,
      "file": "sui generis rg.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/9e71f3a7-2db6-4dfa-8901-e5a01e0a2ccb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14303680/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14303681/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
