### ISSUE TITLE
[Blueprint] Wolverine and the X-Men

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#437]
### Series Name

Wolverine and the X-Men

### Series Year

2009

### Series Database IDs

imdb:tt0772145,tmdb:6549,tvdb:82870

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom Font, logo, and logo-matching colors.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "frame_color",
      "middle_element",
      "logo_size",
      "logo_vertical_shift",
      "shadow_color"
    ],
    "extra_values": [
      "#cea981",
      "1.25",
      "#e3caa2",
      "logo",
      "1.5",
      "450",
      "#030101"
    ],
    "font_color": "#cea981"
  },
  "fonts": [
    {
      "name": "X-Men",
      "color": "#e9e9e9",
      "delete_missing": true,
      "file": "sui generis rg.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/3e740e09-6870-47e0-97ee-c6768aabfb63)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14303733/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14303734/source.zip)

**Comment by CollinHeist** [comment]
Thanks 👍🏻 /create-blueprint
