### ISSUE TITLE
[Blueprint] Moon Knight

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#441]
### Series Name

Moon Knight

### Series Year

2022

### Series Database IDs

imdb:tt10234724,tmdb:92749,tvdb:368611

### Creator Username

anonfawkes

### Blueprint Description

Moonknight in the Marvel card type using the same Font as the logo in the silver color. The frame of the card is hidden.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "marvel",
    "extra_keys": [
      "hide_border"
    ],
    "extra_values": [
      "True"
    ]
  },
  "fonts": [
    {
      "name": "Moonknight",
      "color": "silver",
      "delete_missing": true,
      "file": "MOONFARK-goova-studio.ttf",
      "vertical_shift": -25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/507c7ad5-391b-44b4-8de6-40638439a7df)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14318186/fonts.zip)

**Comment by CollinHeist** [comment]
@JohnFawkes This made me realize the hide border logic is not correct. It should be resizing the image to fill the whole space

**Comment by JohnFawkes** [comment]
> @JohnFawkes This made me realize the hide border logic is not correct. It should be resizing the image to fill the whole space

ill do a new preview when you fix

**Comment by CollinHeist** [comment]
@JohnFawkes That should be fixed on develop now

**Comment by JohnFawkes** [comment]
just saw this. updating now

**Comment by JohnFawkes** [comment]
Done @CollinHeist

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
