### ISSUE TITLE
[Blueprint] Babylon Berlin

### ISSUE THREAD

**Issue by foux** [TitleCardMaker/Blueprints#442]
### Series Name

Babylon Berlin

### Series Year

2017

### Series Database IDs

imdb:tt4378376,tmdb:66980,tvdb:323945

### Creator Username

foux

### Blueprint Description

Simple tinted frame card with one line logo (for visibility) at the top, and index at the bottom, in the color of the logo

### Blueprint

```json
{
  "series": {
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "middle_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "omit",
      "index"
    ],
    "template_ids": [],
    "font_color": "#dec07b",
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![image](https://github.com/TitleCardMaker/Blueprints/assets/246550/2c165cd6-fd79-42a6-8103-00f71e8bf975)

### Zip of Source Files

[logo.png.zip](https://github.com/TitleCardMaker/Blueprints/files/14320533/logo.png.zip)

**Comment by foux** [comment]
Hum, not clear on the error. I suppose it is because of the logo?

**Comment by JohnFawkes** [comment]
> Hum, not clear on the error. I suppose it is because of the logo?

its not the logo. You put the blueprint zip in the source files. you dont do that

**Comment by JohnFawkes** [comment]
the source files are for if you want to include the logo or any source images.

**Comment by CollinHeist** [comment]
I went ahead and fixed that, as anon said the only things that you need to include in the source file zip are things like logos / other images you want. Thanks! /create-blueprint
