### ISSUE TITLE
[Blueprint] The OA

### ISSUE THREAD

**Issue by foux** [TitleCardMaker/Blueprints#45]
### Series Name

The OA

### Series Year

2016

### Series Database IDs

imdb:tt4635282,tmdb:69061,tvdb:321060

### Creator Username

foux

### Blueprint Description

Tinted frame with logo on top and Sackers Gothic Light Std Font used for the title text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "case": "upper",
      "name": "The OA",
      "delete_missing": true,
      "file": "Sackers Gothic Std Light.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/17693271/89fa6872-2b82-4a47-b561-2a14c1c6143b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13400684/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/13400685/source.zip)

**Comment by CollinHeist** [comment]
Thanks for making this! /create-blueprint

**Comment by foux** [comment]
Next time I will include english screenshot instead of French, didn't think about that!

**Comment by CollinHeist** [comment]
That's fine, haha I hadn't thought about it either. And it probably doesn't matter, since the Font is the same, I just don't want users to think the titles are translated
