### ISSUE TITLE
[Blueprint] The Queen's Gambit

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#450]
### Series Name

The Queen's Gambit

### Series Year

2020

### Series Database IDs

imdb:tt10048342,tmdb:87739,tvdb:387115

### Creator Username

Reicha7, flowcool

### Blueprint Description

Landscape style card with custom font (supplied by flowcool)

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "landscape",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "box_adjustments"
    ],
    "extra_values": [
      "-125 -50 -150 -50"
    ],
    "template_ids": [],
    "font_size": 1.5,
    "font_stroke_width": 0.25,
    "font_vertical_shift": 700,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Queen's Gambit (2020)",
      "color": "white",
      "delete_missing": true,
      "file": "PlantinMTProSmBd.TTF",
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/7d965068-4baa-4a41-936b-effdc105f7f3)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14337290/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
