### ISSUE TITLE
[Blueprint] The Tudors

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#451]
### Series Name

The Tudors

### Series Year

2007

### Series Database IDs

imdb:tt0758790,tmdb:2942,tvdb:79925

### Creator Username

Reicha7

### Blueprint Description

Overline style card with custom font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "extra_keys": [
      "separator",
      "line_color",
      "line_width"
    ],
    "extra_values": [
      "\u00b7",
      "#ae0001",
      "14"
    ]
  },
  "fonts": [
    {
      "name": "The Tudors",
      "delete_missing": true,
      "file": "ArgentineOpti-One.otf",
      "stroke_width": 0.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/f385f6d7-76c1-4eec-b613-d7d405329c8c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14337492/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great - thanks! /create-blueprint
