### ISSUE TITLE
[Blueprint] Kim Possible

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#457]
### Series Name

Kim Possible

### Series Year

2002

### Series Database IDs

imdb:tt0278866,tmdb:2345,tvdb:78259

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with custom Font and a special style overrides for the specials.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "logo",
      "title",
      "2"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s0e1": {
      "card_type": "standard",
      "hide_season_text": true,
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e2": {
      "card_type": "standard",
      "hide_season_text": true,
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e3": {
      "card_type": "standard",
      "hide_season_text": true,
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e4": {
      "card_type": "standard",
      "hide_season_text": true,
      "hide_episode_text": true,
      "template_ids": []
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Kim Possible",
      "color": "#8cb823",
      "delete_missing": true,
      "file": "vipnagorgialla.ttf",
      "stroke_width": 3.0,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/bd5caddd-4601-48bb-8b79-e142bd1e7bef)
![preview 2](https://github.com/TitleCardMaker/Blueprints/assets/9253709/da5b4cff-0ef0-4331-85c2-0861d7db01cb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14362123/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14362125/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
