### ISSUE TITLE
[Blueprint] Thunderbirds

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#459]
### Series Name

Thunderbirds

### Series Year

1965

### Series Database IDs

imdb:tt0057790,tmdb:891,tvdb:77964

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with logo-matching colors and absolute episode numbers.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "hide_season_text": true,
    "episode_text_format": "Episode {absolute_episode_number}",
    "extra_keys": [
      "episode_text_font_size",
      "shadow_color"
    ],
    "extra_values": [
      "2",
      "#e8dd97"
    ]
  },
  "fonts": [
    {
      "name": "Thunderbirds",
      "color": "#9c1f1a",
      "delete_missing": true,
      "file": "Anderson Thunderbirds Are GO.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/51ce040e-4a79-44c8-a39b-2f6152efcf19)

### Zip of Font Files

[Anderson Thunderbirds Are GO.ttf.zip](https://github.com/TitleCardMaker/Blueprints/files/14380832/Anderson.Thunderbirds.Are.GO.ttf.zip)

**Comment by CollinHeist** [comment]
I removed the `!` from the Font file name since that can cause problems on some OS's. Thanks! /create-blueprint
