### ISSUE TITLE
[Blueprint] The Thick of It

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#468]
### Series Name

The Thick of It

### Series Year

2005

### Series Database IDs

imdb:tt0459159,tmdb:4507,tvdb:79843

### Creator Username

Reicha7

### Blueprint Description

Standard title card with season and episode text removed. Times New Roman font included to match the series font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [
      0
    ],
    "font_size": 1.5,
    "font_stroke_width": 0.0,
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "font_id": 1,
      "card_type": "standard",
      "hide_season_text": true,
      "hide_episode_text": true,
      "name": "TV_Name_Only",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Thick of It",
      "delete_missing": true,
      "file": "times.ttf"
    },
    {
      "name": "TV_Large",
      "delete_missing": true,
      "file": "impact.ttf",
      "size": 2.0
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/3a71a5c4-6bbd-42ba-a295-cfc371547e66)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14411357/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
