### ISSUE TITLE
[Blueprint] Succession

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#469]
### Series Name

Succession

### Series Year

2018

### Series Database IDs

imdb:tt7660850,tmdb:76331,tvdb:338186

### Creator Username

Reicha7

### Blueprint Description

Standard title card with cardinal overrides for seasons and episodes and a custom font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "episode_text_format": "Episode {to_cardinal(episode_number)}",
    "extra_keys": [
      "season_text_format",
      "stroke_color"
    ],
    "extra_values": [
      "Season {to_cardinal(season_number)}",
      "white"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Succession",
      "delete_missing": true,
      "file": "DidactGothic-Regular.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/9af9919a-52c8-475d-9c6f-0cf2b004db80)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14411754/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good 👍🏻 /create-blueprint
