### ISSUE TITLE
[Blueprint] Shogun

### ISSUE THREAD

**Issue by thedinz** [TitleCardMaker/Blueprints#472]
### Series Name

Shogun

### Series Year

2024

### Series Database IDs

80284

### Creator Username

thedinz

### Blueprint Description

Using a red Gothic Font that has a similar feel to the Font used for the show. Pairing this with Yozora/SlimTitleCard to get close to the look we want.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "Yozora/SlimTitleCard"
  },
  "episodes": {
    "s1e1": {
      "template_ids": [],
      "title": "Episode 1"
    },
    "s1e2": {
      "template_ids": [],
      "title": "Episode 2"
    }
  },
  "fonts": [
    {
      "name": "Shogun",
      "color": "#FF0000",
      "delete_missing": true,
      "file": "The Darkest Night Personal Use.ttf"
    }
  ]
}
```

### Preview Title Cards

![Shōgun (2024) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/68015411/1b3c7f0d-7d36-4f79-9716-19371d5b4e0e)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14439632/fonts.zip)

**Comment by CollinHeist** [comment]
@thedinz Hey, thanks for submitting these! So a few things:
1. You don't need to include anything in the _Zip of Source Files_ section unless you are including Source Images, like logos, etc.
2. Only include the Font file in the font file section. TCM should export this for you in the zip. If you can correct those that should work.

**Comment by thedinz** [comment]
when i click edit i see it all as once long post rather then the template.... what the best way to make these corrections?

**Comment by thedinz** [comment]
ZIP OF FONT FILES
[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14439632/fonts.zip)

**Comment by CollinHeist** [comment]
In the future you will just need to paste that link into the section of the form, but I went ahead and did that for you 👍🏻

**Comment by CollinHeist** [comment]
Okay looks good - thanks! /create-blueprint

**Comment by CollinHeist** [comment]
Oh and one last thing, keep `[Blueprint]` at the start of the issue title, the scripts I've written look for that when creating blueprints. /create-blueprint
