### ISSUE TITLE
[Blueprint] Shōgun

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#473]
### Series Name

Shōgun

### Series Year

2024

### Series Database IDs

imdb:tt2788316,tmdb:126308,tvdb:392573

### Creator Username

Reicha7

### Blueprint Description

Anime style card with custom Font and coloring to match the Series poster.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "hide_season_text": true,
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "episode_text_color",
      "kanji_color"
    ],
    "extra_values": [
      "#c6161b",
      "#c6161b"
    ]
  },
  "fonts": [
    {
      "name": "ShōgunJack",
      "color": "#d4ad4e",
      "title_case": "title",
      "delete_missing": true,
      "file": "MADEC___.TTF"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/aa99a536-6370-47b9-8003-8afd0f3bf307)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14441206/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
