### ISSUE TITLE
[Blueprint] True Detective

### ISSUE THREAD

**Issue by thedinz** [TitleCardMaker/Blueprints#475]
### Series Name

True Detective

### Series Year

2014

### Series Database IDs

270633

### Creator Username

thedinz

### Blueprint Description

A very close font style, using Overline card and black and white which provides a very fitting look to the title cards. The preview Card uses a grayscale style. Includes the "Night Country" title for season 4.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "season_title_ranges": [
      "4"
    ],
    "season_title_values": [
      "Night Country"
    ],
    "font_color": "#ffffff",
    "source_files": []
  },
  "fonts": [
    {
      "name": "Yellowstone",
      "color": "#FFA500",
      "delete_missing": true,
      "file": "Lumberjack Rough.otf",
      "size": 1.2,
      "title_case": "source"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![True Detective (2014) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/68015411/98f09612-e6dd-481c-98af-3b1bee89f1b3)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14449420/fonts.zip)

**Comment by CollinHeist** [comment]
@thedinz Hey - thanks for submitting this. I forgot to mention that styles are the one thing _not_ included in Templates (the idea being they're generally personal preference). I'll edit the BP and remove that Template
