### ISSUE TITLE
[Blueprint] Scott Pilgrim Takes Off

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#476]
### Series Name

Scott Pilgrim Takes Off

### Series Year

2023

### Series Database IDs

imdb:tt16969708,tmdb:155292,tvdb:433113

### Creator Username

Reicha7

### Blueprint Description

Comicbook style card with colours designed to match the show's poster and a custom 8-bit font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "text_box_fill_color",
      "text_box_edge_color",
      "banner_fill_color"
    ],
    "extra_values": [
      "#fad688",
      "#02132d",
      "#fa654f",
      "rgba(2, 19, 45, 1)"
    ]
  },
  "fonts": [
    {
      "name": "Scott Pilgrim",
      "color": "#02d7b4",
      "delete_missing": true,
      "file": "pixel font-7.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/c75b56b3-083f-4af0-b829-ce010b0915d4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14454598/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Nice font. /create-blueprint
