### ISSUE TITLE
[Blueprint] Terry Pratchett's Hogfather

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#477]
### Series Name

Terry Pratchett's Hogfather

### Series Year

2006

### Series Database IDs

imdb:tt0765458,tmdb:4475,tvdb:79988

### Creator Username

Reicha7

### Blueprint Description

Simple Olivier style card with the Terry Pratchett font, and no episode text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "Terry Pratchett",
      "delete_missing": true,
      "file": "caslon-antique.regular.ttf",
      "size": 2.09
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/1290c33c-c8cb-4cca-ae6d-0d3b037ece4b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14454720/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
