### ISSUE TITLE
[Blueprint] Mummies Alive!

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#480]
### Series Name

Mummies Alive!

### Series Year

1997

### Series Database IDs

imdb:tt0125633,tmdb:6279,tvdb:73721

### Creator Username

Reicha7

### Blueprint Description

Standard style card using art watched and unwatched styling to mimic the logo card type, as the backdrop already contains the logo. Custom Font and colors to match the pharaoh in the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "extra_keys": [
      "stroke_color",
      "episode_text_color",
      "episode_text_vertical_shift"
    ],
    "extra_values": [
      "rgb(147,46,38)",
      "rgb(31,160,194)",
      "150"
    ],
    "font_vertical_shift": -150
  },
  "fonts": [
    {
      "name": "Egypt",
      "color": "#f0de2f",
      "delete_missing": true,
      "stroke_width": 2.0,
      "file": "vtcgoblinhand.bold.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/6eb94bd4-89f3-4bac-a91b-50c82536dae4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14467179/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14467180/source.zip)

**Comment by CollinHeist** [comment]
Looks great! I watched this show so much when I was growing up, good times.. /create-blueprint
