### ISSUE TITLE
[Blueprint] Count Duckula

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#481]
### Series Name

Count Duckula

### Series Year

1988

### Series Database IDs

imdb:tt0088500,tmdb:2416,tvdb:76307

### Creator Username

Reicha7

### Blueprint Description

Standard style card designed to be used with an Art Episode style. Uses the official Danger Mouse Font for the episode titles.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "extra_keys": [
      "omit_gradient",
      "episode_text_color",
      "episode_text_font_size",
      "episode_text_vertical_shift"
    ],
    "extra_values": [
      "true",
      "white",
      "2.0",
      "75"
    ]
  },
  "episodes": {
    "s1e42": {
      "template_ids": [],
      "title": "The Mysteries of the\\nWax Museum",
      "match_title": false,
      "auto_split_title": false
    },
    "s1e43": {
      "template_ids": [],
      "title": "The Return of the Curse\\nof the Secret of the Mummy's\\nTomb Meets Frankenduckula's\\nMonster and the Wolf-Man\\nand the Intergalactic Cabbage...",
      "match_title": false,
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Danger Mouse",
      "color": "#e52731",
      "size": 0.85,
      "stroke_width": 5.0,
      "vertical_shift": 450,
      "delete_missing": true,
      "file": "DANGER MOUSE.otf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/dcb2a3d2-b77b-4f3b-b548-c5938bf7805d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14467651/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14467652/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
