### ISSUE TITLE
[Blueprint] The Inbetweeners

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#482]
### Series Name

The Inbetweeners

### Series Year

2008

### Series Database IDs

imdb:tt1220617,tmdb:7317,tvdb:81950

### Creator Username

Reicha7

### Blueprint Description

Standard style card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Inbetweeners",
      "delete_missing": true,
      "file": "D-DIN-Bold.otf",
      "interword_spacing": -25,
      "title_case": "lower"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5366c698-50c5-45f2-8b73-ca30b809d42d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14467729/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
