### ISSUE TITLE
[Blueprint] The Owl House

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#486]
### Series Name

The Owl House

### Series Year

2020

### Series Database IDs

imdb:tt8050756,tmdb:92685,tvdb:349578

### Creator Username

Reicha7

### Blueprint Description

Tinted frame style card with a custom Font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "logo",
      "title",
      "2"
    ]
  },
  "fonts": [
    {
      "name": "Owl House",
      "color": "#f1e0a6",
      "delete_missing": true,
      "stroke_width": 0.25,
      "file": "Tyro Sans.ttf"
    }
  ]
}
```

### Preview Title Cards
![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/fc574765-969b-4e70-b07d-cf0aa31dac9a)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14470384/fonts.zip)

**Comment by CollinHeist** [comment]
@archieyates I haven't seen the show, is that image a spoiler?

**Comment by archieyates** [comment]
Oh I just went with the image it gave for the preview but it came from season 3 so maybe. I'll change it!

**Comment by CollinHeist** [comment]
Great, thanks 👍🏻 /create-blueprint
