### ISSUE TITLE
[Blueprint] The Office

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#488]
### Series Name

The Office

### Series Year

2001

### Series Database IDs

imdb:tt0290978,tmdb:2996,tvdb:78107

### Creator Username

Reicha7

### Blueprint Description

Standard title card with series font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "font_size": 2.0,
    "font_stroke_width": 0.0,
    "font_vertical_shift": -150
  },
  "fonts": [
    {
      "name": "The Office",
      "title_case": "lower",
      "delete_missing": true,
      "file": "Helvetica-Bold-Font.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/a70c4cdb-51f3-43c3-ace7-b47732962a97)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14470925/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
