### ISSUE TITLE
[Blueprint] Extras

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#489]
### Series Name

Extras

### Series Year

2005

### Series Database IDs

imdb:tt0445114,tmdb:2693,tvdb:75660

### Creator Username

Reicha7

### Blueprint Description

Standard style card that more matches Gervais' "The Office", whose Font was used in some Extras posters.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "font_size": 1.5,
    "font_stroke_width": 0.25,
    "font_vertical_shift": -150
  },
  "episodes": {
    "s0e1": {
      "template_ids": [],
      "title": "The Extra Special\\nSeries Finale",
      "match_title": false,
      "auto_split_title": false
    },
    "s1e2": {
      "template_ids": [],
      "title": "Ross Kemp &\\nVinnie Jones",
      "match_title": false,
      "auto_split_title": false
    },
    "s2e6": {
      "template_ids": [],
      "title": "Robert Lindsay &\\nJonathan Ross",
      "match_title": false,
      "auto_split_title": false
    }
  },
  "fonts": [
    {
      "name": "The Office",
      "delete_missing": true,
      "title_case": "lower",
      "file": "Helvetica-Bold-Font.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/09c107b9-d3d8-4da9-a522-b9c15b128190)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14470989/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! I've never heard of this show. /create-blueprint
