### ISSUE TITLE
[Blueprint] Severance

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#490]
### Series Name

Severance

### Series Year

2022

### Series Database IDs

imdb:tt11280740,tmdb:95396,tvdb:371980

### Creator Username

Reicha7

### Blueprint Description

Standard style card with bold Helvetica Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard"
  },
  "episodes": {
    "s1e5": {
      "title": "The Grim Barbarity\\nof Optics and Design",
      "match_title": false,
      "auto_split_title": false
    }
  },
  "fonts": [
    {
      "name": "Helvetica Bold",
      "delete_missing": true,
      "title_case": "title",
      "size": 1.25,
      "stroke_width": 0.0,
      "file": "Helvetica-Bold-Font.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5ab62d37-0d48-4c08-aeeb-c3cb171eba90)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14471003/fonts.zip)

**Comment by CollinHeist** [comment]
👍🏻 /create-blueprint
