### ISSUE TITLE
[Blueprint] PEN15

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#491]
### Series Name

PEN15

### Series Year

2019

### Series Database IDs

imdb:tt8324422,tmdb:85702,tvdb:348127

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame style card with a custom (trial) Font and series-matching colors.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "episode_text_vertical_shift",
      "frame_color",
      "frame_width",
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "rgb(4, 163, 148)",
      "-10",
      "white",
      "20",
      "title",
      "index"
    ]
  },
  "fonts": [
    {
      "name": "Thicker Trial",
      "color": "rgb(252, 204, 4)",
      "size": 1.5,
      "delete_missing": true,
      "file": "Thicker-Black-trial.ttf",
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/76b82d19-3acb-4516-a86e-93612255860c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14471106/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
