### ISSUE TITLE
[Blueprint] Nichijou: My Ordinary Life

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#494]
### Series Name

Nichijou: My Ordinary Life

### Series Year

2011

### Series Database IDs

imdb:tt2098308,tmdb:44684,tvdb:240291

### Creator Username

Reicha7

### Blueprint Description

Standard style card using series font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "omit_gradient"
    ],
    "extra_values": [
      "true"
    ]
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Nichijou",
      "delete_missing": true,
      "file": "HelveticaNeueMedium.ttf",
      "color": "black",
      "size": 2.0,
      "vertical_shift": -150,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/8dc7ba10-0fd1-4cf2-8441-91c90ad3441d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14471486/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
