### ISSUE TITLE
[Blueprint] Frieren: Beyond Journey's End

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#497]
### Series Name

Frieren: Beyond Journey's End

### Series Year

2023

### Series Database IDs

imdb:tt22248376,tmdb:209867,tvdb:424536

### Creator Username

anonfawkes

### Blueprint Description

Anime style card with default font using a skyblue stroke to mimic the skyblueish glow around the lettering of the logo

### Blueprint

```json
{
  "series": {
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "stroke_color",
      "episode_stroke_color"
    ],
    "extra_values": [
      "skyblue",
      "skyblue"
    ],
    "template_ids": [],
    "font_stroke_width": 2.0,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/6346f223-8b6b-46db-b763-5022e2fecc41)

**Comment by CollinHeist** [comment]
Nice - thanks 👍🏻 /create-blueprint
