### ISSUE TITLE
[Blueprint] Rurouni Kenshin

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#498]
### Series Name

Rurouni Kenshin

### Series Year

2023

### Series Database IDs

imdb:tt22249034,tmdb:210879,tvdb:413578

### Creator Username

anonfawkes

### Blueprint Description

Ruriuni Kenshin 2023 in the anime style with custom Font/color to match the original 1996 logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "episode_text_color",
      "stroke_color",
      "kanji_color",
      "episode_stroke_color"
    ],
    "extra_values": [
      "#be1022",
      "white",
      "#be1022",
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Rurouni Kenshin 2023",
      "color": "#be1022",
      "size": 1.3,
      "stroke_width": 4.0,
      "delete_missing": true,
      "file": "Ragingredlotusbb-RJ3W.otf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/40f58a59-3613-4d58-bb54-14b9722bee8a)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14474800/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
