### ISSUE TITLE
[Blueprint] The Seven Deadly Sins: Four Knights of the Apocalypse

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#499]
### Series Name

The Seven Deadly Sins: Four Knights of the Apocalypse

### Series Year

2023

### Series Database IDs

imdb:tt20228550,tmdb:218843,tvdb:420018

### Creator Username

anonfawkes

### Blueprint Description

Shape card style with custom font and colors to match the logo. Shape is diamond

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "shape",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "episode_text_color",
      "stroke_color",
      "season_text_color",
      "italicize_season_text",
      "season_text_font_size",
      "shape",
      "shape_color",
      "shape_width",
      "shape_stroke_width",
      "shape_stroke_color"
    ],
    "extra_values": [
      "#ea691f",
      "white",
      "#ea691f",
      "False",
      "1.3",
      "diamond",
      "#0c78ba",
      "15",
      "8",
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Seven Deadly Sins 2023",
      "delete_missing": true,
      "color": "#ea691f",
      "stroke_width": 1.25,
      "interline_spacing": 20,
      "file": "Deutsch.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/7275faa2-940e-4336-a3d8-68cb30e5d4eb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14474825/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
