### ISSUE TITLE
[Blueprint] Ninja Kamui

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#500]
### Series Name

Ninja Kamui

### Series Year

2024

### Series Database IDs

imdb:tt28480255,tmdb:202284,tvdb:420280

### Creator Username

anonfawkes

### Blueprint Description

Anime style card with a custom Font that closely matches the logo text font in red.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "hide_season_text": false,
    "hide_episode_text": true,
    "template_ids": [],
    "font_color": "red",
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Ninja Kamui - Anime",
      "delete_missing": true,
      "file": "BlackAsylum-xypj.ttf",
      "replacements_in": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9"
      ],
      "replacements_out": [
        "One",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six",
        "Seven",
        "Eight",
        "Nine"
      ]
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/4b68d755-e017-44fe-91a2-403e64b20b60)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14474846/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
