### ISSUE TITLE
[Blueprint] Ninja Kamui

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#501]
### Series Name

Ninja Kamui

### Series Year

2024

### Series Database IDs

imdb:tt28480255,tmdb:202284,tvdb:420280

### Creator Username

anonfawkes

### Blueprint Description

Inset card style with a custom font that closely matches the log text font in a red color. The Season text has been hidden to get a clean look on the episode title since the titles are "Episode #"

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "inset",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [],
    "extra_values": [],
    "template_ids": [],
    "font_color": "red",
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Ninja Kamui - Inset",
      "delete_missing": true,
      "file": "BlackAsylum-xypj.ttf",
      "replacements_in": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9"
      ],
      "replacements_out": [
        "One",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six",
        "Seven",
        "Eight",
        "Nine"
      ]
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/6b1753e9-248b-4c08-be48-f6bfa7230a91)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14474862/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint
