### ISSUE TITLE
[Blueprint] Ash Vs Evil Dead

### ISSUE THREAD

**Issue by thedinz** [TitleCardMaker/Blueprints#504]
### Series Name

Ash VS Evil Dead

### Series Year

2015

### Series Database IDs

296295

### Creator Username

thedinz

### Blueprint Description

This template used the Divider style with a copy-cat font. I prefer to pair this with a blurred watched Episode style.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "divider"
  },
  "fonts": [
    {
      "name": "Evil Dead",
      "color": "#EE0000",
      "delete_missing": true,
      "file": "Evil Dead.ttf"
    }
  ]
}
```

### Preview Title Cards

![Ash vs Evil Dead (2015) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/68015411/1d3e8672-e59a-48e2-a0fc-e917dbac2fb8)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14504612/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
