### ISSUE TITLE
[Blueprint]  11.22.63

### ISSUE THREAD

**Issue by thedinz** [TitleCardMaker/Blueprints#505]
### Series Name

11.22.63

### Series Year

2016

### Series Database IDs

301824

### Creator Username

thedinz

### Blueprint Description

This uses the default style, i think it looks better when you make the cards black and white and it is paired with an official font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "name": "Blurred Greyscale Unique",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "11.22.63",
      "delete_missing": true,
      "file": "STAMPWRITER-KIT.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![11 22 63 (2016) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/68015411/16d12688-7779-413c-b138-0238174fb948)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14485957/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! I'll update this when I allow styles to be added to BPs 👍🏻 /create-blueprint
