### ISSUE TITLE
[Blueprint] ted

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#507]
### Series Name

ted

### Series Year

2024

### Series Database IDs

imdb:tt14824792,tmdb:201834,tvdb:404604

### Creator Username

Reicha7, CollinHeist

### Blueprint Description

Modification on Collinheist's blueprint to remove stroke and season text

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "template_ids": [],
    "font_stroke_width": 0.0,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "ted",
      "color": "rgb(75,144,71)",
      "delete_missing": true,
      "file": "Gotham Bold.otf",
      "size": 1.2,
      "title_case": "lower",
      "vertical_shift": -15
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/6ea2ea2e-d8b7-474f-a89b-2aadb43926bd)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14489573/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
