### ISSUE TITLE
[Blueprint] Dragon Ball GT

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#509]
### Series Name

Dragon Ball GT

### Series Year

1996

### Series Database IDs

imdb:tt0139774,tmdb:12697,tvdb:79275

### Creator Username

anonfawkes

### Blueprint Description

Textless upscaled official Title Cards. Credit to Kwickflix for doing the work of upscaling

### Blueprint

```json
{
  "series": {
    "card_type": "textless"
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/a5d5bc38-4e7c-426d-9d12-920da30fe183)

### Zip of Source Files

[Dragon Ball GT (1996).zip](https://github.com/TitleCardMaker/Blueprints/files/14548991/Dragon.Ball.GT.1996.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
