### ISSUE TITLE
[Blueprint] Dragon Ball Z

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#510]
### Series Name

Dragon Ball Z

### Series Year

1989

### Series Database IDs

imdb:tt0214341,tmdb:12971,tvdb:81472

### Creator Username

anonfawkes

### Blueprint Description

Textless upscaled official Title Cards set as textless. Credit to Kwickflix for doing the work of upscaling

### Blueprint

```json
{
  "series": {
    "card_type": "textless"
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/992b01d4-ba42-4207-abc9-349ca5d2c5e4)

**Comment by CollinHeist** [comment]
Thanks again! /create-blueprint
