### ISSUE TITLE
[Blueprint] - Andromeda

### ISSUE THREAD

**Issue by bugmancx** [TitleCardMaker/Blueprints#515]
### Series Name

Andromeda

### Series Year

2000

### Series Database IDs

tvdb:77544,imdb:tt0213327

### Creator Username

bugmancx

### Blueprint Description

Tinted frame with series logo and episode title font, matching logo colour

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "logo_size"
    ],
    "extra_values": [
      "1"
    ],
    "template_ids": [
      0
    ],
    "font_color": "rgb(242, 181, 112)",
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "card_type": "tinted frame",
      "extra_keys": [
        "top_element",
        "logo_size",
        "bottom_element"
      ],
      "extra_values": [
        "logo",
        "2.5",
        "title"
      ],
      "name": "Tinted Frame Logo",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Andromeda",
      "delete_missing": true,
      "file": "AndromedaLogo.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![Andromeda (2000) - S02E16](https://github.com/TitleCardMaker/Blueprints/assets/130010/6624151c-d9f0-45fe-9e50-d08edce841a0)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14591036/fonts.zip)

**Comment by CollinHeist** [comment]
@bugmancx Hey, thanks for submitting this - looks good. The reason the tests failed initially is the bot is really picky about parsing the form into a Blueprint, so the font link you provided made it error out. If you need to, you can include that in the comment below the Blueprint.

Thanks! /create-blueprint
