### ISSUE TITLE
[Blueprint] Bates Motel

### ISSUE THREAD

**Issue by thedinz** [TitleCardMaker/Blueprints#519]
### Series Name

Bates Motel

### Series Year

2013

### Series Database IDs

262414

### Creator Username

thedinz

### Blueprint Description

Star wars card type with a Font intended to look like the neon lights of the logo. I prefer personally to pair this with "blurred artwork" style.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "star wars",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Bates Motel",
      "color": "#00BFFF",
      "delete_missing": true,
      "file": "Beon-Regular.otf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![Bates Motel (2013) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/68015411/7cc2a60d-8a02-4f74-898f-c32d97962dd4)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14604861/fonts.zip)

**Comment by CollinHeist** [comment]
Nice, looks good 👍🏻 /create-blueprint
