### ISSUE TITLE
[Blueprint] Extraordinary

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#521]
### Series Name

Extraordinary

### Series Year

2023

### Series Database IDs

imdb:tt14531842,tmdb:47907,tvdb:401147

### Creator Username

Reicha7

### Blueprint Description

Comic style card designed to mimic the poster with a similar custom font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "extra_keys": [
      "episode_text_color",
      "index_text_position",
      "text_box_fill_color",
      "text_box_edge_color",
      "index_text_rotation_angle",
      "hide_title_banner",
      "hide_index_banner"
    ],
    "extra_values": [
      "#f7f91a",
      "right",
      "black",
      "black",
      "0.0000001",
      "true",
      "true"
    ],
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Extraordinary",
      "color": "#f7f91a",
      "delete_missing": true,
      "file": "distortion-of-the-brain-and-mind.regular.ttf",
      "size": 2.0,
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/457c471c-1154-4ce6-ab22-7db341066f9a)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14608222/fonts.zip)

**Comment by CollinHeist** [comment]
This looks really good! Thanks. /create-blueprint
