### ISSUE TITLE
[Blueprint] Scream: The TV Series

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#530]
### Series Name

Scream: The TV Series

### Series Year

2015

### Series Database IDs

imdb:tt3921180,tmdb:62823,tvdb:294417

### Creator Username

Reicha7

### Blueprint Description

Cutout card with the series Font, and uses the Standard card type for the specials.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "cutout",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "red"
    ],
    "template_ids": [],
    "font_stroke_width": 0.0,
    "source_files": []
  },
  "episodes": {
    "s0e4": {
      "card_type": "standard",
      "hide_episode_text": true,
      "template_ids": []
    },
    "s0e5": {
      "card_type": "standard",
      "hide_episode_text": true,
      "template_ids": []
    },
    "s2e1": {
      "template_ids": [],
      "font_vertical_shift": -50,
      "title": "I Know What\\nYou Did Last Summer",
      "auto_split_title": false
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Scream TV Series",
      "file": "Scream.ttf",
      "replacements_in": [
      ],
      "replacements_out": [
      ],
      "title_case": "upper"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/7396ab59-f201-4a92-a24e-25603d45f7d1)
![preview2](https://github.com/TitleCardMaker/Blueprints/assets/9253709/ab786a09-d352-4d08-922a-ffb47af9c6b9)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14643632/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks /create-blueprint
