### ISSUE TITLE
[Blueprint] X-Men '97

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#541]
### Series Name

X-Men '97

### Series Year

2024

### Series Database IDs

imdb:tt16026746,tmdb:138502,tvdb:412432

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame card with a custom Font and colors to match the show.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_font_size",
      "frame_width",
      "middle_element",
      "logo_size",
      "logo_vertical_shift",
      "shadow_color"
    ],
    "extra_values": [
      "1.25",
      "12",
      "logo",
      "1.25",
      "475",
      "#d32327"
    ]
  },
  "fonts": [
    {
      "name": "X-Men",
      "color": "#fef200",
      "file": "sui generis rg.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/b21637b5-4d2e-4a68-8e99-142c7b507962)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14675658/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
