### ISSUE TITLE
[Blueprint] Delicious in Dungeon

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#558]
### Series Name

Delicious in Dungeon

### Series Year

2024

### Series Database IDs

imdb:tt21621494,tmdb:207784,tvdb:423257

### Creator Username

Reicha7

### Blueprint Description

Anime-style card with custom Font and custom line breaks for each part of each Episode.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "auto_split_title": false,
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "title_text_format",
      "episode_text_color",
      "stroke_color",
      "kanji_color",
      "kanji_stroke_color",
      "episode_stroke_color"
    ],
    "extra_values": [
      "{f'{NEWLINE}'.join(title_text.split(\"/\" ))}",
      "black",
      "white",
      "black",
      "white",
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Delicious in Dungeon",
      "color": "black",
      "file": "Magical World.otf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/1bb9469b-98a6-4510-b64b-81e7dc4970fe)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14729941/fonts.zip)

**Comment by CollinHeist** [comment]
Was this before the series-level auto split toggle was working?

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
