### ISSUE TITLE
[Blueprint] Black Mirror

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#563]
### Series Name

Black Mirror

### Series Year

2011

### Series Database IDs

imdb:tt2085059,tmdb:42009,tvdb:253463

### Creator Username

Reicha7

### Blueprint Description

Retro card type with a Font similar to the Series'.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "Yozora/RetroTitleCard",
    "extra_keys": [
      "override_style"
    ],
    "extra_values": [
      "rewind"
    ]
  },
  "episodes": {
    "s0e2": {
      "title": "Bandersnatch",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Black Mirror",
      "file": "BeVietnam-Bold.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/978ee00f-4043-412b-a830-baae3af3ba34)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14735722/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great - San Junipero is my favorite episode, so good choice on the preview 👍🏻 /create-blueprint
