### ISSUE TITLE
[Blueprint] Smallville

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#566]
### Series Name

Smallville

### Series Year

2001

### Series Database IDs

imdb:tt0279600,tmdb:4604,tvdb:72218

### Blueprint Description

Standard card with branded Font. (1) and (2) are removed from Episodes that contain unique names to fit the standard naming convention.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard"
  },
  "episodes": {
    "s3e21": {
      "template_ids": [],
      "title": "Forsaken",
      "match_title": false
    },
    "s3e22": {
      "template_ids": [],
      "title": "Covenant",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Smallville",
      "color": "#FF0000",
      "delete_missing": true,
      "file": "smallville.ttf",
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![Smallville (2001) - S03E07](https://github.com/TitleCardMaker/Blueprints/assets/88596884/1bd8918b-438a-4ca8-9e74-17b2243a8d55)
![Smallville (2001) - S03E10](https://github.com/TitleCardMaker/Blueprints/assets/88596884/dc452ff0-6c33-494f-be5e-1a009f373b8c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14758898/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good, thanks! /create-blueprint
