### ISSUE TITLE
[Blueprint] iCarly

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#567]
### Series Name

iCarly

### Series Year

2021

### Series Database IDs

imdb:tt13657062,tmdb:119243,tvdb:397597

### Blueprint Description

Standard Card with a branded font that matches the "iTitle" aesthetic.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "iCarly",
      "delete_missing": true,
      "file": "icarly.ttf",
      "size": 1.1,
      "title_case": "source"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![iCarly (2021) - S03E09](https://github.com/TitleCardMaker/Blueprints/assets/88596884/782f4b6a-14c0-4fd4-acbd-90e7442e6e57)
![iCarly (2021) - S01E09](https://github.com/TitleCardMaker/Blueprints/assets/88596884/a29a41ec-94aa-4800-96c6-85f822f163a5)
![preview](https://github.com/TitleCardMaker/Blueprints/assets/88596884/590ac293-0cab-493b-95fd-c83e6a7517ae)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14758959/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
