### ISSUE TITLE
[Blueprint] The Marvelous Mrs. Maisel

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#568]
### Series Name

The Marvelous Mrs. Maisel

### Series Year

2017

### Series Database IDs

imdb:tt5788792,tmdb:70796,tvdb:326791

### Blueprint Description

Standard card with a branded Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Mrs. Maisel",
      "delete_missing": true,
      "file": "maisel.ttf",
      "kerning": 0.7,
      "interline_spacing": 40,
      "interword_spacing": 20,
      "size": 1.5,
      "stroke_width": 0.3,
      "title_case": "source",
      "vertical_shift": 20
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![The Marvelous Mrs  Maisel (2017) - S02E04](https://github.com/TitleCardMaker/Blueprints/assets/88596884/c7f1a64a-512d-485c-b12c-483150c5f150)
![The Marvelous Mrs  Maisel (2017) - S02E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/16a91cfe-0b79-4a07-bc13-dee60456e002)
![preview](https://github.com/TitleCardMaker/Blueprints/assets/88596884/ee4a0b99-c977-41a1-85a6-60f3d7e3945b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14759097/fonts.zip)

**Comment by CollinHeist** [comment]
Nice 👍🏻 /create-blueprint
