### ISSUE TITLE
[Blueprint] Batwoman

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#569]
### Series Name

Batwoman

### Series Year

2019

### Series Database IDs

imdb:tt8712204,tmdb:89247,tvdb:361315

### Blueprint Description

Comic book card with thematic colors and randomized banner angles.

### Blueprint

```json
{
  "series": {
    "card_type": "comic book",
    "extra_keys": [
      "title_text_rotation_angle",
      "index_text_rotation_angle",
      "text_box_fill_color",
      "banner_fill_color"
    ],
    "extra_values": [
      "random[-4, 4]",
      "random[-4, -3]",
      "rgba(220,20,60,1)",
      "rgba(0,0,128,0.6)"
    ]
  }
}
```

### Preview Title Cards

![Batwoman (2019) - S03E10](https://github.com/TitleCardMaker/Blueprints/assets/88596884/723f912e-72b5-4e79-9256-64cbc15b8981)
![Batwoman (2019) - S03E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/48a20d55-eabe-4a38-a534-f6849136eb3a)
![Batwoman (2019) - S01E06](https://github.com/TitleCardMaker/Blueprints/assets/88596884/8a15dc3c-97e1-4165-9a20-b51bcb13bb81)

**Comment by CollinHeist** [comment]
Looks good - nice color choice. /create-blueprint
