### ISSUE TITLE
[Blueprint] The Real Housewives of Beverly Hills

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#572]
### Series Name

The Real Housewives of Beverly Hills

### Series Year

2010

### Series Database IDs

imdb:tt1720601,tmdb:32390,tvdb:196741

### Blueprint Description

Standard card with a thematic Font.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "#1496b8"
    ],
    "font_id": 0
  },
  "fonts": [
    {
      "name": "Housewives",
      "delete_missing": true,
      "file": "housewives.otf",
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)",
        "(4)",
        "(Part One)",
        "(Part Two)",
        "(Part Three)",
        "(Part Four)",
        "Part One",
        "Part Two",
        "Part Three",
        "Part Four",
        "Part 1",
        "Part 2",
        "Part 3",
        "Part 4",
        "(Part 1)",
        "(Part 2)",
        "(Part 3)",
        "(Part 4)"
      ],
      "replacements_out": [
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV"
      ],
      "stroke_width": 1.3
    }
  ]
}
```

### Preview Title Cards

![The Real Housewives of Beverly Hills (2010) - S12E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/7e53c70a-bc82-43ea-96e4-12721b8a3c2c)
![The Real Housewives of Beverly Hills (2010) - S10E05](https://github.com/TitleCardMaker/Blueprints/assets/88596884/5c8a68c2-1045-4b92-aafc-903c1dd7c04c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14761381/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks 👍🏻 /create-blueprint
