### ISSUE TITLE
[Blueprint] Crazy Ex-Girlfriend

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#575]
### Series Name

Crazy Ex-Girlfriend

### Series Year

2015

### Series Database IDs

imdb:tt4094300,tmdb:63161,tvdb:295777

### Blueprint Description

Music card type with full-length titles allowed, a smaller font size, and an included backdrop.

### Blueprint

```json
{
  "series": {
    "card_type": "music",
    "extra_keys": [
      "player_style",
      "percentage",
      "timeline_color",
      "truncate_long_titles"
    ],
    "extra_values": [
      "artwork",
      "{episode_number / season_episode_max}",
      "pink",
      "False"
    ],
    "font_size": 0.9
  }
}
```

### Preview Title Cards

![Crazy Ex-Girlfriend (2015) - S03E13](https://github.com/TitleCardMaker/Blueprints/assets/88596884/78d45844-c010-4a79-8b32-cd88c2e0138d)
![Crazy Ex-Girlfriend (2015) - S04E17](https://github.com/TitleCardMaker/Blueprints/assets/88596884/16bb8fd3-41e9-412f-8ab0-65ce11a07780)

### Zip of Source Files

[backdrop.zip](https://github.com/TitleCardMaker/Blueprints/files/14764919/backdrop.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
