### ISSUE TITLE
[Blueprint] Black Mirror

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#580]
### Series Name

Black Mirror

### Series Year

2011

### Series Database IDs

imdb:tt2085059,tmdb:42009,tvdb:253463

### Blueprint Description

Masks created using a photoshop automation I put together. Font curated by @Reicha7's

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "override_style"
    ],
    "extra_values": [
      "rewind"
    ],
    "template_ids": [
      0
    ],
    "font_vertical_shift": -20,
    "source_files": []
  },
  "episodes": {},
  "templates": [
    {
      "card_type": "tinted frame",
      "extra_keys": [
        "frame_color",
        "top_element",
        "bottom_element"
      ],
      "extra_values": [
        "#DAC960",
        "omit",
        "title"
      ],
      "name": "Twilight Zone",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Black Mirror",
      "delete_missing": true,
      "file": "BeVietnam-Bold.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![Black Mirror (2011) - S05E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/5a16097c-4a4a-4672-a83b-b87598c4b8a7)
![Black Mirror (2011) - S02E03](https://github.com/TitleCardMaker/Blueprints/assets/88596884/099b240c-12e9-48bf-9f65-63732e4a55d7)
![Black Mirror (2011) - S04E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/4edafb72-4f7e-4bd4-9a9d-2855e7df4d60)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14776142/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14776739/source.zip)

**Comment by CollinHeist** [comment]
@MrSaiclops Any thoughts on adding some vertical shift to the title text so it's centered around the line? If not just let me know

**Comment by MrSaiclops** [comment]
> @MrSaiclops Any thoughts on adding some vertical shift to the title text so it's centered around the line? If not just let me know

I like that. Edited the original post to add -20 vertical shift.

**Comment by CollinHeist** [comment]
Nice, thanks! /create-blueprint
