### ISSUE TITLE
[Blueprint] Prohibition

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#591]
### Series Name

Prohibition

### Series Year

2011

### Series Database IDs

imdb:tt1950799,tmdb:39983,tvdb:251965

### Blueprint Description

Overline card with omission of episode/season index.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "hide_episode_text": true,
    "hide_season_text": true,
    "extra_keys": [
      "line_color",
      "line_position"
    ],
    "extra_values": [
      "red",
      "bottom"
    ],
    "match_titles": false,
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "Burns",
      "file": "burns.ttf"
    }
  ]
}
```

### Preview Title Cards

![Prohibition (2011) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/22816030-c301-4326-b850-77df2d5a1e40)
![Prohibition (2011) - S01E03](https://github.com/TitleCardMaker/Blueprints/assets/88596884/ec5b760d-257c-4bcf-ad2b-c9efe4469c50)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14790883/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good /create-blueprint
