### ISSUE TITLE
[Blueprint] The Dust Bowl

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#592]
### Series Name

The Dust Bowl

### Series Year

2012

### Series Database IDs

imdb:tt2357472,tmdb:56629,tvdb:264098

### Blueprint Description

Overline card with omission of episode/season index.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "hide_episode_text": true,
    "hide_season_text": true,
    "extra_keys": [
      "line_color",
      "line_position"
    ],
    "extra_values": [
      "red",
      "bottom"
    ],
    "match_titles": false,
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "Burns",
      "file": "burns.ttf"
    }
  ]
}
```

### Preview Title Cards

![The Dust Bowl (2012) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/44fd263e-79df-4569-9bf5-a18fead44f23)
![The Dust Bowl (2012) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/6ce47b0c-1819-4e56-9371-8caba0d57e61)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14791268/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks 👍🏻 /create-blueprint
