### ISSUE TITLE
[Blueprint] Hemingway

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#594]
### Series Name

Hemingway

### Series Year

2021

### Series Database IDs

imdb:tt13129360,tmdb:111592,tvdb:394111

### Blueprint Description

Overline card with dates in place of episode/season index.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "hide_episode_text": true,
    "extra_keys": [
      "line_color",
      "line_position"
    ],
    "extra_values": [
      "red",
      "bottom"
    ],
    "match_titles": false,
    "auto_split_title": false
  },
  "episodes": {
    "s1e1": {
      "template_ids": [],
      "title": "A Writer",
      "season_text": "(1899-1929)"
    },
    "s1e2": {
      "template_ids": [],
      "title": "The Avatar",
      "season_text": "(1929-1944)"
    },
    "s1e3": {
      "template_ids": [],
      "title": "The Blank Page",
      "season_text": "(1944-1961)"
    }
  },
  "fonts": [
    {
      "name": "Burns",
      "file": "burns.ttf"
    }
  ]
}
```

### Preview Title Cards

![Hemingway (2021) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/6d6858d9-1c2f-443b-a30a-7f6ef655f273)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14791454/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
