### ISSUE TITLE
[Blueprint] Benjamin Franklin

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#596]
### Series Name

Benjamin Franklin

### Series Year

2022

### Series Database IDs

imdb:tt16415264,tmdb:156138,tvdb:415024

### Blueprint Description

Overline card with dates in place of episode/season index.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "hide_episode_text": true,
    "extra_keys": [
      "line_color",
      "line_position"
    ],
    "extra_values": [
      "red",
      "bottom"
    ],
    "match_titles": false,
    "auto_split_title": false
  },
  "episodes": {
    "s1e1": {
      "template_ids": [],
      "title": "Join or Die",
      "season_text": "(1706-1774)"
    },
    "s1e2": {
      "template_ids": [],
      "title": "An American",
      "season_text": "(1775-1790)"
    }
  },
  "fonts": [
    {
      "name": "Burns",
      "file": "burns.ttf"
    }
  ]
}
```

### Preview Title Cards

![Benjamin Franklin (2022) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/044e2d0a-101e-4f19-a382-4c6096426369)
![Benjamin Franklin (2022) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/5463f0ae-b2d6-4f21-bc11-c4abb3c7c406)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14791501/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks /create-blueprint
