### ISSUE TITLE
[Blueprint] The U.S. and the Holocaust

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#597]
### Series Name

The U.S. and the Holocaust

### Series Year

2022

### Series Database IDs

imdb:tt20863280,tmdb:204165,tvdb:421197

### Blueprint Description

Overline card with dates in place of episode/season index.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "hide_episode_text": true,
    "extra_keys": [
      "line_color",
      "line_position"
    ],
    "extra_values": [
      "red",
      "bottom"
    ],
    "match_titles": false,
    "auto_split_title": false
  },
  "episodes": {
    "s1e1": {
      "template_ids": [],
      "title": "The Golden Door",
      "season_text": "(Beginnings - 1938)"
    },
    "s1e2": {
      "template_ids": [],
      "title": "Yearning to Breathe Free",
      "season_text": "(1938 - 1942)"
    },
    "s1e3": {
      "template_ids": [],
      "title": "The Homeless, Tempest-Tossed",
      "season_text": "(1942 - )"
    }
  },
  "fonts": [
    {
      "name": "Burns",
      "file": "burns.ttf"
    }
  ]
}
```

### Preview Title Cards

![The U S  and the Holocaust (2022) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/6306eaac-8d67-4299-843e-6254200b15a3)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14791519/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
