### ISSUE TITLE
[Blueprint] The American Buffalo

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#598]
### Series Name

The American Buffalo

### Series Year

2023

### Series Database IDs

imdb:tt27131398,tmdb:219756,tvdb:430628

### Blueprint Description

Overline card with no season or episode text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "hide_episode_text": true,
    "hide_season_text": true,
    "extra_keys": [
      "line_color",
      "line_position"
    ],
    "extra_values": [
      "red",
      "bottom"
    ],
    "match_titles": false,
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "Burns",
      "file": "burns.ttf"
    }
  ]
}
```

### Preview Title Cards

![The American Buffalo (2023) - S01E01](https://github.com/TitleCardMaker/Blueprints/assets/88596884/d1fb7c30-c161-4598-a5a6-6312d0217ebc)
![The American Buffalo (2023) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/3f4b390a-536b-46ab-98ca-1518e79b6c91)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14791550/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
