### ISSUE TITLE
[Set] The Real Housewives

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#600]
### Set Name

The Real Housewives

### Blueprints

blueprints/R/The Real Housewives of Atlanta (2008)/0
blueprints/R/The Real Housewives of Beverly Hills (2010)/0
blueprints/R/The Real Housewives of Miami (2011)/0

**Comment by CollinHeist** [comment]
Nice! Good to see the issue/workflow actually work, haha. /create-set
