### ISSUE TITLE
[Blueprint] The Real Housewives Ultimate Girls Trip

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#605]
### Series Name

The Real Housewives Ultimate Girls Trip

### Series Year

2021

### Series Database IDs

imdb:tt15614920,tmdb:136105,tvdb:409671

### Blueprint Description

Standard card type with a thematic Font. Custom season titles since this one is anthological, in a sense. 

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "season_title_ranges": [
      "1",
      "2",
      "3",
      "4"
    ],
    "season_title_values": [
      "Turks and Caicos",
      "Ex-Wives Club",
      "Thailand",
      "Ex-Wives Club II"
    ],
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "#f48148"
    ],
    "auto_split_title": true,
    "source_files": [],
    "font_id": 0
  },
  "fonts": [
    {
      "name": "Housewives",
      "file": "housewives.otf",
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)",
        "(4)",
        "(Part One)",
        "(Part Two)",
        "(Part Three)",
        "(Part Four)",
        "Part One",
        "Part Two",
        "Part Three",
        "Part Four",
        "Part 1",
        "Part 2",
        "Part 3",
        "Part 4",
        "(Part 1)",
        "(Part 2)",
        "(Part 3)",
        "(Part 4)"
      ],
      "replacements_out": [
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV"
      ],
      "stroke_width": 1.3
    }
  ]
}
```

### Preview Title Cards

![The Real Housewives Ultimate Girls Trip (2021) - S04E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/3803b872-688e-4f49-a1f2-da1f4d4ab7b7)
![The Real Housewives Ultimate Girls Trip (2021) - S02E07](https://github.com/TitleCardMaker/Blueprints/assets/88596884/821877a5-9489-4026-b4af-f2fdf52398d5)
![The Real Housewives Ultimate Girls Trip (2021) - S01E02](https://github.com/TitleCardMaker/Blueprints/assets/88596884/5b037de3-4349-47ff-8327-d52636aae136)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14798572/fonts.zip)

### Set IDs

7

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
