### ISSUE TITLE
[Blueprint] The Real Housewives of Dallas

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#608]
### Series Name

The Real Housewives of Dallas

### Series Year

2016

### Series Database IDs

imdb:tt5512352,tmdb:39283,tvdb:307475

### Blueprint Description

Standard card type with a thematic Font.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "#1E70BA"
    ],
    "auto_split_title": true,
    "font_id": 0,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Housewives",
      "file": "housewives.otf",
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)",
        "(4)",
        "(Part One)",
        "(Part Two)",
        "(Part Three)",
        "(Part Four)",
        "Part One",
        "Part Two",
        "Part Three",
        "Part Four",
        "(Part 1)",
        "(Part 2)",
        "(Part 3)",
        "(Part 4)",
        "Part 1",
        "Part 2",
        "Part 3",
        "Part 4"
      ],
      "replacements_out": [
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV"
      ],
      "stroke_width": 1.3
    }
  ]
}
```

### Preview Title Cards

![The Real Housewives of Dallas (2016) - S04E14](https://github.com/TitleCardMaker/Blueprints/assets/88596884/0a91be1f-5ab4-45eb-8411-9ccae2cc89c1)
![The Real Housewives of Dallas (2016) - S05E14](https://github.com/TitleCardMaker/Blueprints/assets/88596884/68904383-cfad-4aa8-94df-a7c29337dd47)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14798903/fonts.zip)

### Set IDs

7

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
