### ISSUE TITLE
[Blueprint] Kaamelott

### ISSUE THREAD

**Issue by foux** [TitleCardMaker/Blueprints#61]
### Series Name

Kaamelott

### Series Year

2005

### Series Database IDs

imdb:tt0441059,tmdb:11466,tvdb:79175

### Creator Username

foux

### Blueprint Description

Faded card with Kaamelott style font in white

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "fade",
    "template_ids": [],
    "font_size": 0.9,
    "source_files": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Ozzy II",
      "delete_missing": true,
      "file": "Ozzy II.ttf"
    }
  ],
  "previews": [],
  "description": []
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/246550/58e80b03-4d9b-421f-bd44-2c2fcc353249)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/13456634/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/13456640/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
