### ISSUE TITLE
[Blueprint] The Real Housewives of New York City

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#613]
### Series Name

The Real Housewives of New York City

### Series Year

2008

### Series Database IDs

imdb:tt1191056,tmdb:14808,tvdb:84669

### Blueprint Description

Standard card type with a thematic Font.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "#BE424A"
    ],
    "auto_split_title": true,
    "font_id": 0,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Housewives",
      "file": "housewives.otf",
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)",
        "(4)",
        "(Part One)",
        "(Part Two)",
        "(Part Three)",
        "(Part Four)",
        "Part One",
        "Part Two",
        "Part Three",
        "Part Four",
        "(Part 1)",
        "(Part 2)",
        "(Part 3)",
        "(Part 4)",
        "Part 1",
        "Part 2",
        "Part 3",
        "Part 4"
      ],
      "replacements_out": [
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV"
      ],
      "stroke_width": 1.3
    }
  ]
}
```

### Preview Title Cards

![The Real Housewives of New York City (2008) - S12E08](https://github.com/TitleCardMaker/Blueprints/assets/88596884/36f66da5-e44e-4beb-a0e3-12a811ed9070)
![The Real Housewives of New York City (2008) - S09E21](https://github.com/TitleCardMaker/Blueprints/assets/88596884/ea4ee0da-3d9d-4f84-9211-f8d8b1fde95f)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14799460/fonts.zip)

### Set IDs

7

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
