### ISSUE TITLE
[Blueprint] The Real Housewives of Dubai

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#615]
### Series Name

The Real Housewives of Dubai

### Series Year

2022

### Series Database IDs

imdb:tt15823202,tmdb:196592,tvdb:413388

### Blueprint Description

Standard card type with a thematic Font.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "#F48148"
    ],
    "auto_split_title": true,
    "font_id": 0,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Housewives",
      "file": "housewives.otf",
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)",
        "(4)",
        "(Part One)",
        "(Part Two)",
        "(Part Three)",
        "(Part Four)",
        "Part One",
        "Part Two",
        "Part Three",
        "Part Four",
        "(Part 1)",
        "(Part 2)",
        "(Part 3)",
        "(Part 4)",
        "Part 1",
        "Part 2",
        "Part 3",
        "Part 4"
      ],
      "replacements_out": [
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV",
        "I",
        "II",
        "III",
        "IV"
      ],
      "stroke_width": 1.3
    }
  ]
}
```

### Preview Title Cards

![The Real Housewives of Dubai (2022) - S01E14](https://github.com/TitleCardMaker/Blueprints/assets/88596884/5b258488-e027-44ed-92bd-1739e8325ebb)
![The Real Housewives of Dubai (2022) - S01E12](https://github.com/TitleCardMaker/Blueprints/assets/88596884/e4a0939c-c2c9-4a57-ac7d-fef71a4268d5)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14799558/fonts.zip)

### Set IDs

7

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
