### ISSUE TITLE
[Set] Ken Burns

### ISSUE THREAD

**Issue by MrSaiclops** [TitleCardMaker/Blueprints#623]
### Set Name

Ken Burns

### Blueprints

blueprints/C/The Civil War (1990)/0
blueprints/B/Baseball (1994)/0
blueprints/J/Jazz (2001)/0
blueprints/M/Mark Twain (2002)/0
blueprints/P/Prohibition (2011)/0
blueprints/D/The Dust Bowl (2012)/0
blueprints/V/The Vietnam War (2017)/0
blueprints/H/Hemingway (2021)/0
blueprints/M/Muhammad Ali (2021)/0
blueprints/B/Benjamin Franklin (2022)/0
blueprints/U/The U.S. and the Holocaust (2022)/0
blueprints/A/The American Buffalo (2023)/0
blueprints/R/The Roosevelts - An Intimate History (2014)/0

**Comment by CollinHeist** [comment]
Thanks! /create-set
