### ISSUE TITLE
[Blueprint] ONE PIECE

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#624]
### Series Name

ONE PIECE

### Series Year

2023

### Series Database IDs

imdb:tt11737520,tmdb:111110,tvdb:392276

### Creator Username

Reicha7

### Blueprint Description

Textless cards using the custom "One Piece" title card from each episode. Doesn't display any episode names but the art is great.

### Blueprint

```json
{
  "series": {
    "card_type": "textless",
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![s1e1](https://github.com/TitleCardMaker/Blueprints/assets/9253709/a83259be-5771-420b-8168-d455ad01840b)
![s1e3](https://github.com/TitleCardMaker/Blueprints/assets/9253709/165dd6b3-bc61-4b95-a4ec-07d580068fb3)
![s1e4](https://github.com/TitleCardMaker/Blueprints/assets/9253709/91061ab4-c9a1-4a11-9d33-f32c097f1874)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14812390/source.zip)

**Comment by CollinHeist** [comment]
Looks good! The official cards are great. /create-blueprint
