### ISSUE TITLE
[Blueprint] The Rise and Fall of Boris Johnson

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#626]
### Series Name

The Rise and Fall of Boris Johnson

### Series Year

2024

### Series Database IDs

tmdb:247772,tvdb:446791

### Creator Username

Reicha7

### Blueprint Description

Simple standard card for TV shows without episode names.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "The Rise and Fall of Boris Johnson",
      "file": "impact.ttf",
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/eacd3fbb-86e5-4f59-a08c-35056c78ff17)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14812925/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
