### ISSUE TITLE
[Blueprint] Mammals

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#630]
### Series Name

Mammals

### Series Year

2024

### Series Database IDs

tmdb:247293,tvdb:433127

### Creator Username

Reicha7

### Blueprint Description

Landscape card type in a Documentary template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/4a015eb0-4863-47ff-acdc-e28c6de7ad01)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14828256/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
