### ISSUE TITLE
[Blueprint] Planet Earth

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#631]
### Series Name

Planet Earth

### Series Year

2006

### Series Database IDs

imdb:tt0795176,tmdb:1044,tvdb:79257

### Creator Username

Reicha7

### Blueprint Description

Landscape card type in a Documentary template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/dbf64ca2-beab-4961-99b0-f573e4baec91)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14828290/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
