### ISSUE TITLE
[Blueprint] Planet Earth II

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#632]
### Series Name

Planet Earth II

### Series Year

2016

### Series Database IDs

imdb:tt5491994,tmdb:68595,tvdb:318408

### Creator Username

Reicha7

### Blueprint Description

Landscape card type in a Documentary template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5f1fe13e-f37f-45b1-9d11-ea0af241d1a6)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14828292/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
