### ISSUE TITLE
[Blueprint] Planet Earth III

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#633]
### Series Name

Planet Earth III

### Series Year

2023

### Series Database IDs

imdb:tt9805674,tmdb:116156,tvdb:413197

### Creator Username

Reicha7

### Blueprint Description

Landscape card type in a Documentary template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/e1fae7f3-458b-4871-926e-d595d84e1aa5)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14828296/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
