### ISSUE TITLE
[Blueprint] The Blue Planet

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#634]
### Series Name

The Blue Planet

### Series Year

2001

### Series Database IDs

imdb:tt0296310,tmdb:13579,tvdb:74372

### Creator Username

Reicha7

### Blueprint Description

Landscape card type in a Documentary template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/73563cb9-7d4d-439e-a6d5-b7e40b150de5)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14828299/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
