### ISSUE TITLE
[Blueprint] Blue Planet II

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#635]
### Series Name

Blue Planet II

### Series Year

2017

### Series Database IDs

imdb:tt6769208,tmdb:74313,tvdb:330942

### Creator Username

Reicha7

### Blueprint Description

Landscape card type in a Documentary template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/de9ce7b0-dab9-43f8-9626-b683124e9d29)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14828303/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
