### ISSUE TITLE
[Blueprint] Monarch: Legacy of Monsters

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#645]
### Series Name

Monarch: Legacy of Monsters

### Series Year

2023

### Series Database IDs

imdb:tt17220216,tmdb:202411,tvdb:422598

### Creator Username

Reicha7

### Blueprint Description

Retro Style card with Godzilla 2014 font all coloured to look like a classified photo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "Yozora/RetroTitleCard",
    "extra_keys": [
      "override_bw"
    ],
    "extra_values": [
      "bw"
    ]
  },
  "fonts": [
    {
      "name": "Godzilla",
      "color": "red",
      "file": "OPTICompit-Regular.otf",
      "size": 1.5,
      "stroke_width": 0
    }
  ]
}
```

### Preview Title Cards

![Monarch - Legacy of Monsters - S01E03 - Secrets and Lies](https://github.com/TitleCardMaker/Blueprints/assets/9253709/7b24607b-6c6a-4fe7-ad6b-7b7bdc323767)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14844423/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
