### ISSUE TITLE
[Blueprint] Alias

### ISSUE THREAD

**Issue by stevenffrench** [TitleCardMaker/Blueprints#646]
### Series Name

Alias

### Series Year

2001

### Series Database IDs

imdb:tt0285333,tmdb:2046,tvdb:75930

### Creator Username

Starpc

### Blueprint Description

Standard card type with a custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard"
  },
  "fonts": [
    {
      "name": "Alias",
      "color": "white",
      "file": "Alias.ttf",
      "size": 1.25,
      "vertical_shift": 25
    }
  ]
}
```

### Preview Title Cards

![Alias (2001) - S03E08](https://github.com/TitleCardMaker/Blueprints/assets/65608383/d721c723-bc18-4038-a1b9-3201f91cd0c3)
![Alias (2001) - S01E21](https://github.com/TitleCardMaker/Blueprints/assets/65608383/c0177341-6f40-486b-b118-87a1ac8c934c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14845580/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
