### ISSUE TITLE
[Blueprint] Deadman Wonderland

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#652]
### Series Name

Deadman Wonderland

### Series Year

2011

### Series Database IDs

imdb:tt1909447,tmdb:42503,tvdb:247997

### Creator Username

anonfawkes

### Blueprint Description

Anime style card with a custom Font that closely matches the text logo. Also colored using the colors of the main character's body Shiro.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "stroke_color",
      "kanji_vertical_shift",
      "kanji_color",
      "kanji_font_size",
      "kanji_stroke_color",
      "kanji_stroke_width",
      "episode_stroke_color"
    ],
    "extra_values": [
      "rgba(125,57,48,255)",
      "10",
      "white",
      "1.5",
      "rgba(125,57,48,255)",
      "3.5",
      "rgba(125,57,48,255)"
    ]
  },
  "fonts": [
    {
      "name": "Deadman Wonderland",
      "color": "white",
      "title_case": "upper",
      "size": 1.5,
      "stroke_width": 4.0,
      "vertical_shift": -30,
      "file": "File.otf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/6ef78526-acc7-4cf7-976b-2ac46d6c8a0d)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14848991/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
