### ISSUE TITLE
[Set] Digimon

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#653]
### Set Name

Digimon Collection

### Blueprints

blueprints/D/Digimon - Digital Monsters (1999)/0
blueprints/D/Digimon Tamers (2001)/0
blueprints/D/Digimon Frontier (2002)/0
blueprints/D/Digimon Adventure 20th Memorial Story (2019)/0
blueprints/D/Digimon Adventure - 2020 (2020)/0

**Comment by CollinHeist** [comment]
Thanks! /create-set
