### ISSUE TITLE
[Blueprint] Beacon 23

### ISSUE THREAD

**Issue by BEisem** [TitleCardMaker/Blueprints#668]
### Series Name

Beacon 23

### Series Year

2023

### Series Database IDs

imdb:tt9174724,tmdb:112388,tvdb:399240

### Creator Username

Departed69

### Blueprint Description

Uses the "Divider" card type with a Font to match the series title font, and a red divider to match the color in the title font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "divider",
    "extra_keys": [
      "divider_color"
    ],
    "extra_values": [
      "Red"
    ]
  },
  "fonts": [
    {
      "name": "Neo Sans Regular",
      "file": "Neo Sans Regular.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/34734248/4f58ea9e-7bfb-459d-bcb9-3285c9345766)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14899074/fonts.zip)

**Comment by CollinHeist** [comment]
@BEisem Thanks! I'd make sure popups aren't blocked for TCM, it should auto-fill some parts of the form out for you when you click "export," so it's good to check. /create-blueprint
