### ISSUE TITLE
[Blueprint] The Big Lez Show

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#673]
### Series Name

The Big Lez Show

### Series Year

2012

### Series Database IDs

imdb:tt5804986,tmdb:70327,tvdb:279220

### Creator Username

Reicha7

### Blueprint Description

Uses a combination of the "official" thumbnails from the show as well as a custom font to try and roughly match the hand-drawn font. Uses a couple of Textless cards but mainly Standard.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "stroke_color"
    ],
    "extra_values": [
      "#9792b2"
    ],
    "font_color": "#fecfe1"
  },
  "episodes": {
    "s0e16": {
      "card_type": "textless",
      "template_ids": []
    },
    "s0e17": {
      "template_ids": [],
      "auto_split_title": false,
      "title": "on Location with\\nClarence Claymore",
      "match_title": false
    },
    "s1e8": {
      "template_ids": [],
      "auto_split_title": false,
      "title": "Lez and Quinton\\nCharge the Scooby\\nDoo Spooky Coaster",
      "match_title": false
    },
    "s2e9": {
      "template_ids": [],
      "auto_split_title": false,
      "title": "Attack of the\\nChoomahs (Part 1)",
      "match_title": false
    },
    "s2e10": {
      "template_ids": [],
      "auto_split_title": false,
      "title": "Attack of the\\nChoomahs (Part 2)",
      "match_title": false
    },
    "s4e5": {
      "card_type": "textless",
      "template_ids": [],
      "auto_split_title": false,
      "title": "Choomah Island 3\\nDenouement",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Big Lez",
      "file": "DreamyBubbleDEMO-DEMO.ttf",
      "kerning": -15.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/5b86eb7e-0b94-401d-a659-130a33be3ad1)
![preview 2](https://github.com/TitleCardMaker/Blueprints/assets/9253709/cdb199d4-04c4-4e81-9a8a-dd8a193637ca)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14938518/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14938519/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
