### ISSUE TITLE
[Blueprint] Mike Nolan's Long Weekend

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#674]
### Series Name

Mike Nolan's Long Weekend

### Series Year

2019

### Series Database IDs

imdb:tt10917170,tmdb:232849,tvdb:376255

### Creator Username

Reicha7

### Blueprint Description

Standard style cards with custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "stroke_color"
    ],
    "extra_values": [
      "#fed3e1",
      "#b64c90"
    ],
    "font_color": "#25bffd"
      
  },
  "fonts": [
    {
      "name": "Big Lez",
      "file": "DreamyBubbleDEMO-DEMO.ttf",
      "kerning": -15.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/efd02321-839e-496b-86f2-7b0d141ebfd8)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14938544/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
