### ISSUE TITLE
[Blueprint] SASSY THE SASQUATCH

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#676]
### Series Name

SASSY THE SASQUATCH

### Series Year

2022

### Series Database IDs

imdb:tt21209936,tmdb:204933,tvdb:421839

### Creator Username

Reicha7

### Blueprint Description

Standard style card (with a textless for the special) using custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "template_ids": [],
    "font_color": "#c37848",
    "source_files": []
  },
  "episodes": {
    "s0e1": {
      "card_type": "textless",
      "template_ids": []
    },
    "s1e2": {
      "template_ids": [],
      "auto_split_title": false,
      "title": "WATER YOU\\nTALKINABEET",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Big Lez",
      "file": "DreamyBubbleDEMO-DEMO.ttf",
      "kerning": -15.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/75ca1915-fcff-41ab-9bb0-745b3f9877a6)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14938607/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/14938616/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
