### ISSUE TITLE
[Blueprint] The Donny & Clarence Show

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#677]
### Series Name

The Donny & Clarence Show

### Series Year

2024

### Series Database IDs

tmdb:251218,tvdb:448601

### Creator Username

Reicha7

### Blueprint Description

Standard style card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "stroke_color"
    ],
    "extra_values": [
      "#f2ebce",
      "#f2ebce"
    ],
    "template_ids": [],
    "font_color": "#9d9d51",
    "source_files": []
  },
  "fonts": [
    {
      "name": "Big Lez",
      "file": "DreamyBubbleDEMO-DEMO.ttf",
      "kerning": -15.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/67819d43-d9f1-42a0-921e-4f618efbd4d3)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14938641/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
