### ISSUE TITLE
[Blueprint] Fallout

### ISSUE THREAD

**Issue by JohnFawkes** [TitleCardMaker/Blueprints#681]
### Series Name

Fallout

### Series Year

2024

### Series Database IDs

imdb:tt12637874,tmdb:106379,tvdb:416744

### Creator Username

anonfawkes

### Blueprint Description

Inset card type with the season and episode text hidden. Uses the Fallout Font with the lightening bolt "O" and yellow color to match the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "inset",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "hide_line"
    ],
    "extra_values": [
      "True"
    ]
  },
  "fonts": [
    {
      "name": "Fallout",
      "file": "Overseer Italic.otf",
      "color": "rgb(252, 212, 60)"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/33303104/c4904876-555b-4bc2-841a-0cd13314a482)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/14944882/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
