### ISSUE TITLE
[Blueprint] Jeopardy!

### ISSUE THREAD

**Issue by JCPlex81** [TitleCardMaker/Blueprints#703]
### Series Name

Jeopardy!

### Series Year

1984

### Series Database IDs

imdb:tt0159881,tmdb:2912,tvdb:77075

### Creator Username

BattleChambers

### Blueprint Description

Notification card type that hides the show's title to prevent spoilers. Should be used with Art styles so the included backdrop is used.

To ensure this works, you must have Sonarr set as your Episode Data Source.

### Blueprint

```json
{
  "series": {
    "card_type": "notification",
    "hide_season_text": true,
    "extra_keys": [
      "title_text_format",
      "episode_text_font_size"
    ],
    "extra_values": [
      "\"\"",
      "6"
    ]
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/157861309/d02e941c-d7bb-40a5-ba4a-aa5bc94c0eb6)

### Zip of Source Files

[Jeopardy Backdrop.zip](https://github.com/TitleCardMaker/Blueprints/files/15017471/Jeopardy.Backdrop.zip)

**Comment by CollinHeist** [comment]
@JCPlex81 Thanks! Just a few minor things:

1. Looks like you're using a custom Font (Halo) in TCM, but did not include the Font file (included in the Blueprint .zip file TCM exports) in the issue. Looks like this Font isn't even being used, but that's part of why the BP failed the tests
2. Like the form says, you need to include a __zip__ (`.zip` file) of source files, not directly upload the image.

I can fix 1, but you'll need to zip that image and then edit the issue. Thanks!

**Comment by CollinHeist** [comment]
Thanks! Looks great. /create-blueprint
