### ISSUE TITLE
[Blueprint] Baby Reindeer

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#709]
### Series Name

Baby Reindeer

### Series Year

2024

### Series Database IDs

imdb:tt13649112,tmdb:241259,tvdb:417223

### Creator Username

Reicha7

### Blueprint Description

Basic style card with series title colour matching

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "font_id": 0
  },
  "fonts": [
    {
      "name": "Baby Reindeer",
      "file": "impact.ttf",
      "color": "#df4741",
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/4af8ef2d-45b9-4b2e-b937-ca07b150ee0c)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15068716/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
