### ISSUE TITLE
[Blueprint] Person of Interest

### ISSUE THREAD

**Issue by stevenffrench** [TitleCardMaker/Blueprints#718]
### Series Name

Person of Interest

### Series Year

2011

### Series Database IDs

imdb:tt1839578,tmdb:1411,tvdb:248742

### Creator Username

starpc

### Blueprint Description

Tinted frame in yellow as a homage to people who know of The Machine.  A custom font to is also utilized.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "frame_color"
    ],
    "extra_values": [
      "yellow"
    ],
    "template_ids": [],
    "auto_split_title": true,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Person of Interest",
      "file": "Acens.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/65608383/72d81fa2-077a-4bdd-a877-e859d0572f58)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15102199/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
