### ISSUE TITLE
[Blueprint] Clarkson's Farm (2021)

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#723]
### Series Name

Clarkson's Farm

### Series Year

2021

### Series Database IDs

imdb:tt10541088,tmdb:117648

### Creator Username

TheChrisK

### Blueprint Description

Overline card using a matching font called AZ Hello.

### Blueprint

```json
{
  "series": {
    "card_type": "overline",
    "extra_keys": [
      "separator",
      "episode_text_color",
      "line_position",
      "line_width"
    ],
    "extra_values": [
      "\u2022",
      "#ffffff",
      "bottom",
      "9"
    ],
    "font_id": 0
  },
  "fonts": [
    {
      "name": "AZ Hello",
      "color": "#fed814",
      "file": "AZ Hello.OTF",
      "size": 1.4,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/be11ed9e-cbeb-4057-9a04-5d00798e5901)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15135583/fonts.zip)

**Comment by TheChrisK** [comment]
That was easier. :)

**Comment by CollinHeist** [comment]
Yes, much easier, haha. Thanks! /create-blueprint
