### ISSUE TITLE
[Blueprint] Father of the Pride

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#724]
### Series Name

Father of the Pride

### Series Year

2004

### Series Database IDs

imdb:tt0361179,tmdb:441,tvdb:72681

### Creator Username

Reicha7

### Blueprint Description

Standard style card with a custom font and absolute episode numbering.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "episode_text_format": "Episode {absolute_episode_number}"
  },
  "fonts": [
    {
      "name": "Father of the Pride",
      "color": "#f5b925",
      "file": "impact.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/1a888916-6586-4a7b-b665-25f018673859)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15135930/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
