### ISSUE TITLE
[Blueprint] Foundation

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#725]
### Series Name

Foundation

### Series Year

2021

### Series Database IDs

imdb:tt0804484,tmdb:93740,tvdb:366972

### Creator Username

Reicha7

### Blueprint Description

Sci-Fi style card with shows font and colours designed to match some of the logo colours.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "azuravian/SciFiTitleCard",
    "extra_keys": [
      "add_trailing_underscore",
      "overlay_bottom_color",
      "overlay_top_color",
      "overlay_middle_color",
      "overlay_rectangles_color",
      "overlay_top_alpha"
    ],
    "extra_values": [
      "false",
      "#a99480",
      "#a99480",
      "#705b2d",
      "white",
      "0.00001"
    ],
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Foundation",
      "file": "FoundationTitlesHand-SemiBold-v0.85.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/8c2f9515-3315-47e0-b8f6-1cf245cf96b8)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15135968/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great 👍🏻 Thanks /create-blueprint
