### ISSUE TITLE
[Blueprint] Star Trek: Discovery

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#730]
### Series Name

Star Trek: Discovery

### Series Year

2017

### Series Database IDs

imdb:tt5171438,tmdb:67198,tvdb:328711

### Creator Username

TheChrisK

### Blueprint Description

Standard card using Edge of the Galaxy font.

Color scheme matches this poster (https://theposterdb.com/api/assets/21376).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "#e8bbd5"
    ],
    "template_ids": [
      0
    ],
    "auto_split_title": true,
    "font_color": "#e8bbd5",
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font_size"
      ],
      "extra_values": [
        "#fde698",
        "1.2"
      ],
      "name": "Star Trek Episodes",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#ffffff",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/f5462f40-a408-49bd-b2a4-067fb48bb2bd)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15139602/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
