### ISSUE TITLE
[Blueprint] Star Trek: Lower Decks

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#731]
### Series Name

Star Trek: Lower Decks

### Series Year

2020

### Series Database IDs

imdb:tt9184820,tmdb:85948,tvdb:367138

### Blueprint Description

Standard card using Edge of the Galaxy font.

Color scheme matches this poster (https://theposterdb.com/api/assets/93031).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "#fca9d7"
    ],
    "template_ids": [
      0
    ],
    "auto_split_title": true,
    "font_color": "#fca9d7",
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font_size"
      ],
      "extra_values": [
        "#fde698",
        "1.2"
      ],
      "name": "Star Trek Episodes",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#ffffff",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/cdbc992c-820c-4d16-b5ff-5ca7e7d9d698)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15139614/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
