### ISSUE TITLE
[Blueprint] Star Trek: Voyager

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#732]
### Series Name

Star Trek: Voyager

### Series Year

1995

### Series Database IDs

imdb:tt0112178,tmdb:1855,tvdb:74550

### Blueprint Description

Standard card using Edge of the Galaxy font. Episodes with unsupported characters have been edited.

Color scheme matches this poster (https://theposterdb.com/api/assets/21377).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "#fde59f"
    ],
    "template_ids": [
      0
    ],
    "auto_split_title": true,
    "font_color": "#fde59f",
    "source_files": []
  },
  "episodes": {
    "s1e1": {
      "template_ids": [],
      "title": "Caretaker (1)"
    },
    "s4e20": {
      "template_ids": [],
      "title": "Vis a Vis"
    },
    "s7e25": {
      "template_ids": [],
      "title": "Endgame (1)"
    }
  },
  "templates": [
    {
      "font_id": 0,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font_size"
      ],
      "extra_values": [
        "#fde698",
        "1.2"
      ],
      "name": "Star Trek Episodes",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#ffffff",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/159e5682-9fa2-40bc-a188-b0bda54578cb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15139621/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
