### ISSUE TITLE
[Blueprint] Star Trek: Deep Space Nine

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#733]
### Series Name

Star Trek: Deep Space Nine

### Series Year

1993

### Series Database IDs

imdb:tt0106145,tmdb:580,tvdb:72073

### Creator Username

TheChrisK

### Blueprint Description

Standard card using Edge of the Galaxy font.

Color scheme matches this poster https://theposterdb.com/api/assets/21381).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "#b2d3f4"
    ],
    "template_ids": [
      0
    ],
    "auto_split_title": true,
    "font_color": "#b2d3f4",
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font_size"
      ],
      "extra_values": [
        "#fde698",
        "1.2"
      ],
      "name": "Star Trek Episodes",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#ffffff",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/1978e196-5912-470b-bb25-2caf57329a1b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15139641/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
