### ISSUE TITLE
[Blueprint] G.I. Joe: A Real American Hero

### ISSUE THREAD

**Issue by stevenffrench** [TitleCardMaker/Blueprints#741]
### Series Name

G.I. Joe: A Real American Hero

### Series Year

1983

### Series Database IDs

imdb:tt0337762,tmdb:29200,tvdb:77780

### Creator Username

starpc

### Blueprint Description

Comic Book title card in red with a custom font to match the show title.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "template_ids": [],
    "auto_split_title": true,
    "source_files": []
  },
  "fonts": [
    {
      "name": "G. I. Joe",
      "file": "Action_Force.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/65608383/b0cf056a-88c9-4483-9892-72310ac1023b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15145462/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint
