### ISSUE TITLE
[Blueprint] Quantum Leap

### ISSUE THREAD

**Issue by stevenffrench** [TitleCardMaker/Blueprints#742]
### Series Name

Quantum Leap

### Series Year

1989

### Series Database IDs

imdb:tt0096684,tmdb:4018,tvdb:72248

### Creator Username

starpc

### Blueprint Description

Retro Title Card in rewind style with a custom font to match the show's title.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "Yozora/RetroTitleCard",
    "extra_keys": [
      "override_style",
      "overlay_top_color",
      "overlay_rectangles_color"
    ],
    "extra_values": [
      "rewind",
      "rgb(48, 90, 141)",
      "rgb(244, 248, 254)"
    ],
    "template_ids": [],
    "auto_split_title": true,
    "font_size": 0.85,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Quantum Leap",
      "file": "QuantumLeap.TTF",
      "replacements_in": [
        "("
      ],
      "replacements_out": [
        "Part "
      ]
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/65608383/e1bf7a13-3ab7-4129-adec-49c02e25995b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15145657/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! /create-blueprint
