### ISSUE TITLE
[Blueprint] Final Space

### ISSUE THREAD

**Issue by mayberts** [TitleCardMaker/Blueprints#743]
### Series Name

Final Space

### Series Year

2018

### Series Database IDs

imdb:tt6317068,tmdb:74387,tvdb:332353

### Creator Username

mayberts

### Blueprint Description

Standard card with season text hidden. I use a blurred watched Style. The Font is a close match, but not exact.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "template_ids": [],
    "font_color": "#C1CDC1",
    "source_files": []
  },
  "fonts": [
    {
      "name": "Final Space",
      "file": "prowler.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/27490448/2faf6e94-3452-4d6b-a9fa-facc2d7c0fca)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15152193/fonts.zip)

**Comment by CollinHeist** [comment]
@mayberts Hey did you want to include a preview Card which includes the custom font?

**Comment by mayberts** [comment]
> @mayberts Hey did you want to include a preview Card which includes the custom font?

I thought I had, but it doesn't look like it is showing.  I will take a look now

**Comment by CollinHeist** [comment]
Sorry for the delay! I didn't get any emails about these, for some reason. Looks good! /create-blueprint
