### ISSUE TITLE
[Blueprint] Star Trek: Strange New Worlds

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#745]
### Series Name

Star Trek: Strange New Worlds

### Series Year

2022

### Series Database IDs

imdb:tt12327578,tmdb:103516,tvdb:382389

### Creator Username

TheChrisK

### Blueprint Description

Standard card using Edge of the Galaxy font.

Color scheme matches this poster (https://theposterdb.com/api/assets/233019).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "#fde698"
    ],
    "template_ids": [
      0
    ],
    "auto_split_title": true,
    "font_color": "#fde698",
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font_size"
      ],
      "extra_values": [
        "#fde698",
        "1.2"
      ],
      "name": "Star Trek Episodes",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#ffffff",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/73fe5718-46b9-4304-8515-1f2e3b39b2b8)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15171072/fonts.zip)

### Set IDs

19

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
