### ISSUE TITLE
[Blueprint] Star Trek: Picard

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#746]
### Series Name

Star Trek: Picard

### Series Year

2020

### Series Database IDs

imdb:tt8806524,tmdb:85949,tvdb:364093

### Creator Username

TheChrisK

### Blueprint Description

Standard card using Edge of the Galaxy font.

Color scheme matches this poster (https://theposterdb.com/poster/40656).

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color"
    ],
    "extra_values": [
      "#f7d97a"
    ],
    "template_ids": [
      0
    ],
    "auto_split_title": true,
    "font_color": "#f7d97a",
    "source_files": []
  },
  "episodes": {
    "s3e9": {
      "template_ids": [],
      "title": "Vox"
    }
  },
  "templates": [
    {
      "font_id": 0,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font_size"
      ],
      "extra_values": [
        "#fde698",
        "1.2"
      ],
      "name": "Star Trek Episodes",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#ffffff",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/15892287/408b0db8-c5d6-4de2-a1d9-f40db2b0acec)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15171100/fonts.zip)

### Set IDs

19

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
