### ISSUE TITLE
[Blueprint] Columbo

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#747]
### Series Name

Columbo

### Series Year

1968

### Series Database IDs

imdb:tt1466074,tmdb:873,tvdb:70369

### Creator Username

Reicha7

### Blueprint Description

Standard style card with a font designed to match the in-show text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "template_ids": [],
    "font_color": "#ecd961",
    "source_files": []
  },
  "fonts": [
    {
      "name": "Helvetica Bold",
      "file": "Helvetica-Bold-Font.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/697d2349-4401-40c1-9df2-0e9c171fe09a)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15182005/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
