### ISSUE TITLE
[Blueprint] The Dark Crystal: Age of Resistance

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#749]
### Series Name

The Dark Crystal: Age of Resistance

### Series Year

2019

### Series Database IDs

imdb:tt6905542,tmdb:71809,tvdb:361549

### Creator Username

Reicha7

### Blueprint Description

Tinted Frame card with a custom Font and series color matching. 1 Episode name is adjusted to account for missing font glyph.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "episode_text_font",
      "episode_text_font_size",
      "episode_text_vertical_shift",
      "frame_color",
      "frame_width",
      "shadow_color"
    ],
    "extra_values": [
      "#de28a1",
      "{title_font}",
      "1.5",
      "-15",
      "#c7c7c7",
      "14",
      "#34035c"
    ]
  },
  "episodes": {
    "s1e8": {
      "title": "Prophets Do Not Know Everything",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Dark Crystal",
      "color": "#de28a1",
      "size": 1.2,
      "file": "dc_s.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/28e45163-65f9-4369-ae49-3bc958e02025)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15205746/fonts.zip)

**Comment by archieyates** [comment]
Wasn't 100% sure on the best way to do fonts for the episode text font so I just put it in source

**Comment by CollinHeist** [comment]
I think that is (generally) the best way to do it. I added a feature after seeing this BP where if you specify `{title_font}` as the episode text font file then it will just use the same file, so that should simplify this type of thing.

Thanks! /create-blueprint
