### ISSUE TITLE
[Blueprint] Jeopardy! Masters

### ISSUE THREAD

**Issue by JCPlex81** [TitleCardMaker/Blueprints#752]
### Series Name

Jeopardy! Masters

### Series Year

2023

### Series Database IDs

imdb:tt27715632,tmdb:219241,tvdb:429912

### Creator Username

BattleChambers

### Blueprint Description

Fade card type using an art style to avoid revealing any spoilers. Episode data source should be set to Sonarr and you can toggle greyscale art for watched episodes to your liking. 

### Blueprint

```json
{
  "series": {
    "card_type": "fade",
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![Jeopardy Masters Example](https://github.com/TitleCardMaker/Blueprints/assets/157861309/b6d24f95-423b-4867-b799-e502c7755cb0)

### Zip of Source Files

[Jeopardy masters.zip](https://github.com/TitleCardMaker/Blueprints/files/15226775/Jeopardy.masters.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good. /create-blueprint
