### ISSUE TITLE
[Blueprint] Star Wars: Tales of the Empire

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#753]
### Series Name

Star Wars: Tales of the Empire

### Series Year

2024

### Series Database IDs

imdb:tt32019314,tmdb:251091,tvdb:448549

### Creator Username

Reicha7

### Blueprint Description

Star Wars card type with an episode override to look better

### Blueprint

```json
{
  "series": {
    "card_type": "star wars",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s1e2": {
      "template_ids": [],
      "auto_split_title": false
    }
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/091bbda3-4a5f-4d4e-946c-55eb4ae5b51c)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
