### ISSUE TITLE
[Blueprint] Bucky O'Hare and the Toad Wars!

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#754]
### Series Name

Bucky O'Hare and the Toad Wars!

### Series Year

1992

### Series Database IDs

imdb:tt0185793,tmdb:27453,tvdb:76788

### Creator Username

Reicha7

### Blueprint Description

Logo Style card with custom font and supplied logo and backdrop. Use with an art style to use the backdrop.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "logo",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "stroke_color",
      "use_background_image"
    ],
    "extra_values": [
      "rgb(245, 221, 8)",
      "rgb(150, 20, 154)",
      "true"
    ]
  },
  "fonts": [
    {
      "name": "Bucky O'Hare",
      "color": "rgb(245, 221, 8)",
      "stroke_width": 2.5,
      "file": "round-pop.regular.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/2d794ff1-3a79-4010-a07d-9f5117a57630)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15227401/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/15227404/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
