### ISSUE TITLE
[Blueprint] Glee

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#756]
### Series Name

Glee

### Series Year

2009

### Series Database IDs

imdb:tt1327801,tmdb:1417,tvdb:83610

### Creator Username

Reicha7

### Blueprint Description

Overline style card with a custom Font designed to mimic the show's.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "episode_text_format": "E{episode_number}",
    "season_title_ranges": [
      "s1e1-s6e13"
    ],
    "season_title_values": [
      "S{season_number}"
    ],
    "extra_keys": [
      "separator",
      "line_position"
    ],
    "extra_values": [
      ":",
      "bottom"
    ]
  },
  "fonts": [
    {
      "name": "Glee",
      "color": "rgb(250, 240, 4)",
      "file": "KAMAR.TTF",
      "kerning": 5.0,
      "size": 1.46,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/d9b4da7a-a2f5-4d62-b768-faff126f4e58)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15255570/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Sorry for the delay. /create-blueprint
