### ISSUE TITLE
[Blueprint] Galactica 1980

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#759]
### Series Name

Galactica 1980

### Series Year

1980

### Series Database IDs

imdb:tt0080221,tmdb:4621,tvdb:71170

### Creator Username

Tech Jedi

### Blueprint Description

Tinted Frame Plus card with a Galactic font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "rgb(223, 228, 232)",
      "2.0",
      "logo",
      "index",
      "2.0"
    ]
  },
  "fonts": [
    {
      "name": "Battlestar Galactica",
      "color": "rgb(223, 228, 232)",
      "file": "BATTLEST.TTF",
      "replacements_in": [
        "@",
        "'",
        ">",
        "/",
        "(",
        "~",
        "+",
        ")",
        "}",
        "]",
        "\"",
        "\\",
        "<",
        "[",
        "=",
        "|",
        "#",
        "&",
        "^",
        "$",
        "%",
        "*",
        "`",
        "{"
      ],
      "replacements_out": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "and",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "size": 0.8,
      "title_case": "source"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/28914268/c923379c-101d-438c-a876-aa80bea4a41c)

### Zip of Font Files

[BATTLEST.TTF.zip](https://github.com/TitleCardMaker/Blueprints/files/15301411/BATTLEST.TTF.zip)

### Zip of Source Files

[logo.png.zip](https://github.com/TitleCardMaker/Blueprints/files/15315891/logo.png.zip)

**Comment by CollinHeist** [comment]
@TechJedi51 Hey - did you want to include the logo file you've got in the card here? Same with the other BPs you submitted. If not, just let me know 👍🏻

**Comment by TechJedi51** [comment]
Yes. How do I do that?

**Comment by TechJedi51** [comment]
![logo](https://github.com/TitleCardMaker/Blueprints/assets/28914268/625749f4-b78f-40d9-a953-c211eb1e58f2)

**Comment by CollinHeist** [comment]
There are instructions on the [website](https://titlecardmaker.com/blueprints/#sharing-your-own-blueprint), the logo should be zipped and then added to the form under the source files section

**Comment by CollinHeist** [comment]
I added that for you - thanks! /create-blueprint
