### ISSUE TITLE
[Blueprint] Battlestar Galactica

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#760]
### Series Name

Battlestar Galactica

### Series Year

1978

### Series Database IDs

imdb:tt0076984,tmdb:501,tvdb:71173

### Creator Username

Tech Jedi

### Blueprint Description

Title Frame Plus card with logo color for text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "rgb(223, 228, 232)",
      "2.0",
      "logo",
      "index",
      "4.0"
    ]
  },
  "fonts": [
    {
      "name": "Battlestar Galactica",
      "color": "rgb(223, 228, 232)",
      "file": "BATTLEST.TTF",
      "replacements_in": [
        "@",
        "'",
        ">",
        "/",
        "(",
        "~",
        "+",
        ")",
        "}",
        "]",
        "\"",
        "\\",
        "<",
        "[",
        "=",
        "|",
        "#",
        "&",
        "^",
        "$",
        "%",
        "*",
        "`",
        "{"
      ],
      "replacements_out": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "and",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "size": 0.8,
      "title_case": "source"
    }
  ]
}
```

### Preview Title Cards

![Battlestar Galactica (1978) - S01E24 - The Hand of God](https://github.com/TitleCardMaker/Blueprints/assets/28914268/a2fa190e-9b2e-4ba6-a868-49251486805c)

### Zip of Font Files

[BATTLEST.TTF.zip](https://github.com/TitleCardMaker/Blueprints/files/15301486/BATTLEST.TTF.zip)

### Zip of Source Files

[logo.png.zip](https://github.com/TitleCardMaker/Blueprints/files/15315892/logo.png.zip)

**Comment by TechJedi51** [comment]
![logo](https://github.com/TitleCardMaker/Blueprints/assets/28914268/231bc7e4-17c8-4977-95d8-6ff252daabe7)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
