### ISSUE TITLE
[Blueprint] Batman

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#761]
### Series Name

Batman

### Series Year

1966

### Series Database IDs

imdb:tt0059968,tmdb:2287,tvdb:77871

### Blueprint Description

Tinted Frame Plus with Ad Lib(Batman 60's) font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_font_size",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "2.0",
      "logo",
      "index",
      "2.0"
    ]
  },
  "fonts": [
    {
      "name": "Batman 60's",
      "color": "yellow",
      "file": "adlib.ttf",
      "title_case": "source"
    }
  ]
}
```

### Preview Title Cards

![Batman (1966) - S02E12 - The Clock King Gets Crowned](https://github.com/TitleCardMaker/Blueprints/assets/28914268/4a3c6520-10c6-4acd-9e38-7578fa4ca686)

### Zip of Font Files

[adlib.ttf.zip](https://github.com/TitleCardMaker/Blueprints/files/15301560/adlib.ttf.zip)

### Zip of Source Files

[logo.png.zip](https://github.com/TitleCardMaker/Blueprints/files/15315893/logo.png.zip)

**Comment by TechJedi51** [comment]
![logo](https://github.com/TitleCardMaker/Blueprints/assets/28914268/a1a1d794-9023-4866-8fb4-c966ea4225bb)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
