### ISSUE TITLE
[Blueprint] Young Justice

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#764]
### Series Name

Young Justice

### Series Year

2010

### Series Database IDs

imdb:tt1641384,tmdb:33217,tvdb:192061

### Creator Username

Reicha7

### Blueprint Description

Basic Marvel/DC style card with custom season names.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "season_title_ranges": [
      "1",
      "2",
      "3",
      "4"
    ],
    "season_title_values": [
      "Identity",
      "Invasion",
      "Outsiders",
      "Phantoms"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "card_type": "marvel",
      "name": "DC and Marvel",
      "filters": []
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/a97a99af-53bb-4576-8389-8c2644e41a77)

### Set IDs

2

**Comment by CollinHeist** [comment]
Looks good - I added this to my Marvel Set, hope that's cool. Thanks! /create-blueprint
