### ISSUE TITLE
[Blueprint] The Offer

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#768]
### Series Name

The Offer

### Series Year

2022

### Series Database IDs

imdb:tt13111040,tmdb:114068,tvdb:392770

### Blueprint Description

Tinted Frame Plus card type using the Corleone (The Godfather) Font. 

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_font_size",
      "top_element",
      "bottom_element",
      "logo_size",
      "blur_edges"
    ],
    "extra_values": [
      "2.0",
      "logo",
      "index",
      "2.0",
      "false"
    ]
  },
  "fonts": [
    {
      "name": "The Godfather",
      "color": "white",
      "title_case": "source",
      "file": "Corleone.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/28914268/aa946923-0809-4f0e-be17-44a144f25efd)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15325443/fonts.zip)

### Zip of Source Files

[logo.png.zip](https://github.com/TitleCardMaker/Blueprints/files/15341215/logo.png.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint
