### ISSUE TITLE
[Blueprint] The Munsters

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#769]
### Series Name

The Munsters

### Series Year

1964

### Series Database IDs

imdb:tt0057773,tmdb:1712,tvdb:77280

### Blueprint Description

Tinted Frame Plus card with the Munsters font (Liquidism). Red logo and text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_font_size",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "2.0",
      "logo",
      "index",
      "2.0"
    ]
  },
  "fonts": [
    {
      "name": "The Munsters",
      "color": "red",
      "title_case": "source",
      "file": "Liquidism.otf"
    }
  ]
}
```

### Preview Title Cards

![The Munsters (1964) - S02E04 - Herman Munster, Shutter Bug](https://github.com/TitleCardMaker/Blueprints/assets/28914268/78e6ee3d-dc64-4cc6-b1a3-10b61ee56989)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15325617/fonts.zip)

### Zip of Source Files

[logo.png (1).zip](https://github.com/TitleCardMaker/Blueprints/files/15341225/logo.png.1.zip)

**Comment by CollinHeist** [comment]
Thanks again! /create-blueprint
