### ISSUE TITLE
[Blueprint] Arrested Development

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#771]
### Series Name

Arrested Development

### Series Year

2003

### Series Database IDs

imdb:tt0367279,tmdb:4589,tvdb:72173

### Creator Username

Reicha7, rtgurley

### Blueprint Description

Tinted frame blueprint using rtgurley's font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "frame_color"
    ],
    "extra_values": [
      "white"
    ],
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Arrested Development",
      "color": "#FA5601",
      "file": "BlurWeb-Medium W03 Regular.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/dbe7aac6-9503-458c-8d99-1be602e946cd)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15366437/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
