### ISSUE TITLE
[Blueprint] The Staircase

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#772]
### Series Name

The Staircase

### Series Year

2022

### Series Database IDs

imdb:tt11324406,tmdb:122196,tvdb:400269

### Creator Username

Reicha7

### Blueprint Description

Standard card with custom font with similar letter spacing.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s1e8": {
      "template_ids": [],
      "auto_split_title": false,
      "title": "America's Sweetheart or:\\nTime Over Time",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Staircase",
      "color": "#e6e453",
      "file": "SourceSansPro-Regular.ttf",
      "kerning": -20.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/85eb89a9-f968-4c5f-8108-e91885192abd)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15366799/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
