### ISSUE TITLE
[Blueprint] How It's Made

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#775]
### Series Name

How It's Made

### Series Year

2001

### Series Database IDs

imdb:tt0835010,tmdb:1749,tvdb:79485

### Creator Username

Reicha7

### Blueprint Description

Divider card with Helvetica font and custom code for splitting the title into a new line for each segment of the episode.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "divider",
    "extra_keys": [
      "title_text_format",
      "text_position",
      "title_text_position"
    ],
    "extra_values": [
      "{f'{NEWLINE}'.join(title_text.split(\"; \" ))}",
      "lower left",
      "right"
    ],
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "How It's Made",
      "color": "white",
      "file": "Helvetica-Bold-Font.ttf",
      "stroke_width": 0.0,
      "interline_spacing": 12
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/075ab9d3-9af9-4f92-bff0-3a613af2b912)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15382133/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks 👍🏻 /create-blueprint
