### ISSUE TITLE
[Blueprint] Twisted Metal

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#777]
### Series Name

Twisted Metal

### Series Year

2023

### Series Database IDs

imdb:tt14261112,tmdb:133748,tvdb:366532

### Creator Username

Reicha7

### Blueprint Description

Textless card using the in-show cards (which don't show the episode name)

### Blueprint

```json
{
  "series": {
    "card_type": "textless",
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/28c75f0b-8c52-468a-a8ee-482eadcfc989)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/15410130/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
