### ISSUE TITLE
[Blueprint] Fruits Basket

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#780]
### Series Name

Fruits Basket

### Series Year

2001

### Series Database IDs

imdb:tt0328738,tmdb:36941,tvdb:78900

### Creator Username

Reicha7

### Blueprint Description

Anime card with a custom Font and no season text.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "hide_season_text": true
  },
  "fonts": [
    {
      "name": "Fruits Basket 2001",
      "color": "#fef8e9",
      "file": "Dkabeille-AdZL.otf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/512e7fbe-d2b6-424b-a245-7126f6eccab3)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15457702/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
