### ISSUE TITLE
[Blueprint] Fruits Basket

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#781]
### Series Name

Fruits Basket

### Series Year

2019

### Series Database IDs

imdb:tt9304350,tmdb:85991,tvdb:357488

### Creator Username

Reicha7

### Blueprint Description

Anime card with a custom Font and a manual Kanji translation for the special.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ]
  },
  "episodes": {
    "s0e1": {
      "hide_episode_text": true,
      "extra_keys": [
        "kanji"
      ],
      "extra_values": [
        "\u30d5\u30eb\u30fc\u30c4\u30d0\u30b9\u30b1\u30c3\u30c8 -prelude-"
      ]
    }
  },
  "fonts": [
    {
      "name": "Fruits Basket 2019",
      "file": "Attentica 4F UltraLight.ttf",
      "size": 1.5,
      "title_case": "lower",
      "vertical_shift": -50
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/015715de-f2c6-422f-a83e-b71df189b92b)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15457710/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
