### ISSUE TITLE
[Blueprint] Jurassic World: Chaos Theory

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#782]
### Series Name

Jurassic World: Chaos Theory

### Series Year

2024

### Series Database IDs

imdb:tt29899148,tmdb:237512,tvdb:440997

### Creator Username

Reicha7

### Blueprint Description

Logo card which includes the art and the Jurassic Park font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "logo",
    "hide_season_text": true,
    "extra_keys": [
      "episode_text_color",
      "episode_text_vertical_shift",
      "logo_size",
      "logo_vertical_shift",
      "use_background_image"
    ],
    "extra_values": [
      "#f1a719",
      "100",
      "0.75",
      "-250",
      "true"
    ]
  },
  "fonts": [
    {
      "name": "Jurassic Park",
      "file": "Jurassic_Park.ttf",
      "size": 1.5,
      "color": "#ec6402",
      "vertical_shift": -100
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/c8277419-48d6-47cb-b6eb-22c1ef30c2db)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15476639/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
