### ISSUE TITLE
[Blueprint] Hell's Kitchen (US)

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#785]
### Series Name

Hell's Kitchen (US)

### Series Year

2005

### Series Database IDs

imdb:tt0437005,tmdb:2370,tvdb:74897

### Creator Username

Reicha7

### Blueprint Description

Notification card designed to be used with a backdrop for all episodes. Recommend to use an art style.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "notification",
    "extra_keys": [
      "glass_color",
      "edge_color"
    ],
    "extra_values": [
      "rgba(250, 11, 14, 0.5)",
      "#fa0b0e"
    ],
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "Hell's Kitchen",
      "color": "white",
      "file": "Trajan Bold.ttf",
      "kerning": 0.4
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/1977ca42-0f7d-43bb-afef-94eb3d91f654)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15506019/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/TitleCardMaker/Blueprints/files/15506021/source.zip)

**Comment by CollinHeist** [comment]
Thanks - looks good! /create-blueprint
