### ISSUE TITLE
[Blueprint] Death and Other Details

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#786]
### Series Name

Death and Other Details

### Series Year

2024

### Series Database IDs

imdb:tt15439048,tmdb:133813,tvdb:410100

### Creator Username

Reicha7

### Blueprint Description

Music style card with custom font and series' logo colours for the player.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "music",
    "hide_season_text": true,
    "extra_keys": [
      "player_style",
      "percentage",
      "timeline_color",
      "draw_heart",
      "heart_color",
      "heart_stroke_color"
    ],
    "extra_values": [
      "basic",
      "{episode_number / season_episode_max}",
      "rgb(230, 81, 23)",
      "true",
      "rgb(230, 81, 23)",
      "rgb(230, 81, 23)"
    ],
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Death and Other Details",
      "color": "#ebefd7",
      "file": "EmblemaOne-Regular.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/8e399d66-ce68-456c-9da3-77def42484bb)

### Zip of Font Files

[fonts.zip](https://github.com/TitleCardMaker/Blueprints/files/15506204/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
