### ISSUE TITLE
[Blueprint] Jurassic World: Camp Cretaceous

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#787]
### Series Name

Jurassic World: Camp Cretaceous

### Series Year

2020

### Series Database IDs

imdb:tt10436228,tmdb:93741,tvdb:365066

### Creator Username

Reicha7

### Blueprint Description

Logo card which includes the art and the Jurassic Park font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "logo",
    "extra_keys": [
      "episode_text_color",
      "episode_text_vertical_shift",
      "logo_size",
      "logo_vertical_shift",
      "use_background_image"
    ],
    "extra_values": [
      "#f1a719",
      "100",
      "0.75",
      "-250",
      "true"
    ],
    "template_ids": [],
    "font_color": "#ec6402",
    "font_vertical_shift": -100,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Jurassic Park",
      "file": "Jurassic_Park.ttf",
      "replacements_in": [
        "-",
        ",",
        ".",
        "'",
        "?",
        "!"
      ],
      "replacements_out": [
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "size": 1.5
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/6490f20d-aad3-435a-bafc-f9828d627106)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/15523733/fonts.zip)

**Comment by archieyates** [comment]
Added font

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
