### ISSUE TITLE
[Blueprint] Atypical

### ISSUE THREAD

**Issue by cspowell82** [TitleCardMaker/Blueprints#796]
### Series Name

Atypical

### Series Year

2017

### Series Database IDs

imdb:tt6315640,tmdb:71578,tvdb:330374

### Blueprint Description

Blueprint for Netflix's Atypical.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "#fff",
      "{title_font}",
      "title",
      "logo",
      "1.5"
    ],
    "font_title_case": "title"
  },
  "fonts": [
    {
      "name": "Atypical - Daft Brush",
      "file": "DaftBrush.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/45018586/068bf68e-da04-4815-b4fa-a07652036473)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/15796861/fonts.zip)

### Zip of Source Files

[fonts.zip](https://github.com/user-attachments/files/15778684/fonts.zip)

**Comment by CollinHeist** [comment]
Hey - so this "failed" because only the font zip is supposed to be uploaded in the "Zip of Font Files" section. There are some instructions [here](https://titlecardmaker.com/blueprints/#sharing-your-own-blueprint) for reference. I'll fix it for now

**Comment by cspowell82** [comment]
Aah, thank you.   
On Tue, Jun 11, 2024 at 10:11 PM, Collin Heist ***@***.***&gt; wrote:  Hey - so this "failed" because only the font zip is supposed to be uploaded in the "Zip of Font Files" section. There are some instructions here for reference. I'll fix it for now

**Comment by CollinHeist** [comment]
No problem! One other thing, in the future you _can_ include the logo within a Blueprint (in the Source Files section) - just in case you wanted someone to use the same logo as you.

Thanks for submitting this, looks good! /create-blueprint

**Comment by cspowell82** [comment]
The logo I didn't upload. ![logo](https://github.com/TitleCardMaker/Blueprints/assets/45018586/a7a9224e-2d60-49d8-ae0e-134898cc9d63)
