### ISSUE TITLE
[Blueprint] Black Butler

### ISSUE THREAD

**Issue by NibblesOnGithub** [TitleCardMaker/Blueprints#797]
### Series Name

Black Butler

### Series Year

2008

### Series Database IDs

imdb:tt1316554,tmdb:50712,tvdb:83996

### Creator Username

Nibbles

### Blueprint Description

Anime style card with a backdrop and a custom font to match the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "extra_keys": [
      "stroke_color",
      "kanji_vertical_shift",
      "kanji_color",
      "kanji_font_size",
      "kanji_stroke_color"
    ],
    "extra_values": [
      "white",
      "25",
      "black",
      "1.7",
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Black Butler",
      "color": "black",
      "file": "Plain Black Wide.ttf",
      "stroke_width": 5.0,
      "vertical_shift": 25
    }
  ]
}
```

### Preview Title Cards

![card-unique](https://github.com/TitleCardMaker/Blueprints/assets/48078280/7bdc5b1b-f2a7-40cb-8a1b-6d4e6e4fc798)

### Zip of Font Files

[Plain Black Wide.zip](https://github.com/user-attachments/files/15780212/Plain.Black.Wide.zip)

### Zip of Source Files

[backdrop.jpg.zip](https://github.com/user-attachments/files/15796916/backdrop.jpg.zip)

**Comment by NibblesOnGithub** [comment]
![preview](https://github.com/TitleCardMaker/Blueprints/assets/48078280/bccaa967-e3c8-4c84-9ae1-94652826258d)
[fonts.zip](https://github.com/user-attachments/files/15780276/fonts.zip)


in case those are needed cuz I'm stupid.

**Comment by CollinHeist** [comment]
@NibblesOnGithub Looks good - thanks! As long as the font files are zipped and included in the issue, that's all that's needed. Only thing I noticed is that the filename of the image should match as it appears in TCM - so `backdrop.jpg` in this case - so that it is automatically used when someone imports it. I made that change for you 👍🏻 

/create-blueprint

**Comment by CollinHeist** [comment]
Looks like GitHub had a stroke.. /create-blueprint
