### ISSUE TITLE
[Blueprint] Baby Reindeer

### ISSUE THREAD

**Issue by cspowell82** [TitleCardMaker/Blueprints#800]
### Series Name

Baby Reindeer

### Series Year

2024

### Series Database IDs

imdb:tt13649112,tmdb:241259,tvdb:417223

### Blueprint Description

Tinted Frame Blueprint with custom font and color matching.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "frame_color",
      "frame_width"
    ],
    "extra_values": [
      "rgb(236, 52, 52)",
      "rgb(236, 52, 52)",
      "10"
    ],
    "template_ids": [
      0
    ],
    "font_color": "rgb(236, 52, 52)",
    "source_files": []
  },
  "templates": [
    {
      "font_id": 1,
      "card_type": "tinted frame",
      "hide_season_text": true,
      "extra_keys": [
        "episode_text_color",
        "episode_text_font",
        "frame_color",
        "top_element",
        "middle_element",
        "bottom_element",
        "logo_size",
        "blur_edges",
        "shadow_color"
      ],
      "extra_values": [
        "#fff",
        "{title_font}",
        "#fff",
        "title",
        "omit",
        "logo",
        "1.5",
        "true",
        "black"
      ],
      "name": "Tinted Frame",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Impact",
      "file": "impact.ttf"
    },
    {
      "name": "Inter-Regular",
      "color": "#ffffff",
      "file": "Inter-Regular.otf",
      "title_case": "source"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/45018586/8dda0cb0-c33c-4597-9ab1-8db470d3118a)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/15806140/fonts.zip)

### Zip of Source Files

[logo.png.zip](https://github.com/user-attachments/files/15806153/logo.png.zip)

**Comment by CollinHeist** [comment]
Looks like you changed the cards to have a red frame, but that's not what you have in the preview Card. Did you mean to do that?

**Comment by cspowell82** [comment]
I just uploaded the output from the export. It should have a red frame.   
On Sun, Jun 16, 2024 at 3:13 PM, Collin Heist ***@***.***&gt; wrote:  Looks like you changed the cards to have a red frame, but that's not what you have in the preview Card. Did you mean to do that?

**Comment by CollinHeist** [comment]
If you changed the card config and did not recreate any of them before exporting the Blueprint then there is no "accurate" Card for TCM to grab for the export

**Comment by CollinHeist** [comment]
I'm going to close this - feel free to reopen if you're able to fix the preview! Thanks
