### ISSUE TITLE
[Blueprint] Squid Girl

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#803]
### Series Name

Squid Girl

### Series Year

2010

### Series Database IDs

imdb:tt1738090,tmdb:35447,tvdb:195721

### Creator Username

Reicha7

### Blueprint Description

Anime card with custom font, custom line breaks, and colours to match the show's logo

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "season_title_ranges": [
      "0",
      "1",
      "2"
    ],
    "season_title_values": [
      "Specials",
      "Season One",
      "Season Two"
    ],
    "extra_keys": [
      "title_text_format",
      "episode_text_color",
      "kanji_color",
      "kanji_stroke_color",
      "kanji_stroke_width"
    ],
    "extra_values": [
      "{f'{NEWLINE}'.join(title_text.split(\"/ \" ))}",
      "rgb(236, 204, 34)",
      "rgb(15, 101, 163)",
      "white",
      "0.75"
    ],
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "Squid Girl",
      "file": "Bubble Mint.ttf",
      "size": 0.75
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/abcda404-1e6f-40fe-bc4c-44ea91a2510e)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/15844816/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
