### ISSUE TITLE
[Blueprint] The Apprentice (UK)

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#804]
### Series Name

The Apprentice (UK)

### Series Year

2005

### Series Database IDs

imdb:tt0450897,tmdb:2472,tvdb:75795

### Creator Username

Reicha7

### Blueprint Description

Notification card designed to be used with backdrop art.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "notification",
    "episode_text_format": "Week {episode_number}",
    "match_titles": false,
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "The Apprentice",
      "color": "#ebebeb",
      "file": "impact.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/df429b4d-02b0-4ae7-ae9d-7335a4a7c44b)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/15844849/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/user-attachments/files/15844846/source.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good. /create-blueprint
