### ISSUE TITLE
[Blueprint] Band of Brothers

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#805]
### Series Name

Band of Brothers

### Series Year

2001

### Series Database IDs

imdb:tt0185906,tmdb:4613,tvdb:74205

### Creator Username

Reicha7

### Blueprint Description

Textless cards using the official title cards from the show

### Blueprint

```json
{
  "series": {
    "card_type": "textless",
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/4148a73b-1908-4c35-a6c6-d1e9c9bc4e56)

### Zip of Source Files

[source.zip](https://github.com/user-attachments/files/15858681/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
