### ISSUE TITLE
[Blueprint] The Pacific

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#807]
### Series Name

The Pacific

### Series Year

2010

### Series Database IDs

imdb:tt0374463,tmdb:16997,tvdb:85539

### Creator Username

Reicha7

### Blueprint Description

Textless title cards using the ones from within the show.

### Blueprint

```json
{
  "series": {
    "card_type": "textless",
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/147592f8-606e-45cd-baa9-03334e9e9405)

### Zip of Source Files

[source.zip](https://github.com/user-attachments/files/15859927/source.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
