### ISSUE TITLE
[Blueprint] Maniac

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#811]
### Series Name

Maniac

### Series Year

2018

### Series Database IDs

imdb:tt5580146,tmdb:73411,tvdb:350864

### Creator Username

Reicha7

### Blueprint Description

Retro style card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "Yozora/RetroTitleCard",
    "hide_season_text": true,
    "extra_keys": [
      "override_bw",
      "override_style"
    ],
    "extra_values": [
      "color",
      "play"
    ],
    "template_ids": [],
    "font_kerning": 0.05,
    "source_files": []
  },
  "episodes": {
    "s1e7": {
      "template_ids": [],
      "match_title": true
    }
  },
  "fonts": [
    {
      "name": "Maniac",
      "file": "BLUELINES.TTF",
      "size": 0.75,
      "stroke_width": 0.01
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/aae757f5-5482-4781-90da-812837dd4fb0)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/15962030/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
