### ISSUE TITLE
[Blueprint] Gordon Ramsay: Uncharted

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#812]
### Series Name

Gordon Ramsay: Uncharted

### Series Year

2019

### Series Database IDs

imdb:tt9165706,tmdb:91405,tvdb:365920

### Creator Username

Reicha7

### Blueprint Description

Overline style card with a custom font designed to match series poster.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "extra_keys": [
      "episode_text_color",
      "line_color",
      "line_position",
      "line_width"
    ],
    "extra_values": [
      "#f0f0f0",
      "#fdde13",
      "bottom",
      "15"
    ]
  },
  "episodes": {
    "s3e2": {
      "template_ids": [],
      "title": "Portugal's Rugged Coast"
    }
  },
  "fonts": [
    {
      "name": "Gordon Ramsay Uncharted",
      "color": "#f0f0f0",
      "file": "Topline-regular.ttf",
      "stroke_width": 0.0,
      "replacements_in": [
        "\u2019"
      ],
      "replacements_out": [
        "'"
      ],
      "size": 1.15
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/f6d2a784-c6dc-4c1f-ad56-0b1661e18e83)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16041669/fonts.zip)

**Comment by archieyates** [comment]
I tried to change the episode text size to scale it up a bit but it didn't seem to be working

**Comment by CollinHeist** [comment]
I'll take a look at fixing that extra. Thanks /create-blueprint
