### ISSUE TITLE
[Blueprint] Suburra: Blood on Rome

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#813]
### Series Name

Suburra: Blood on Rome

### Series Year

2017

### Series Database IDs

imdb:tt7197684,tmdb:73671,tvdb:327138

### Creator Username

Reicha7

### Blueprint Description

Stripe style card with colours and font designed to match the series poster

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "striped",
    "extra_keys": [
      "episode_text_color",
      "overlay_color",
      "text_position"
    ],
    "extra_values": [
      "#fffbe2",
      "#64878f",
      "upper left"
    ]
  },
  "fonts": [
    {
      "name": "Suburra",
      "color": "#fffbe2",
      "size": 1.75,
      "file": "Singo Sans Regular.ttf",
      "interword_spacing": -25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/9253709/68fba8a5-4e69-432b-a44e-1f865406169a)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16041718/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good 👍🏻 /create-blueprint
