### ISSUE TITLE
[Blueprint] Rainbow Brite

### ISSUE THREAD

**Issue by Natejt** [TitleCardMaker/Blueprints#815]
### Series Name

Rainbow Brite

### Series Year

1984

### Series Database IDs

imdb:tt0174422,tmdb:572,tvdb:71398

### Blueprint Description

Tinted Frame style card with logo, font, and colors matching the logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "frame_color",
      "top_element",
      "bottom_element",
      "logo_size",
      "shadow_color"
    ],
    "extra_values": [
      "rgb(243,186,48)",
      "logo",
      "title",
      "2.5",
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Rainbow Bright",
      "color": "rgb(201,53,65)",
      "file": "RollingNoOne-ExtraBold.ttf",
      "stroke_width": 2.5,
      "title_case": "title"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/14960259/17c65bc8-c2c6-45c0-8ae0-fe7926799477)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16045060/fonts.zip)

### Zip of Source Files

[logo.zip](https://github.com/user-attachments/files/16045063/logo.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks great. /create-blueprint
