### ISSUE TITLE
[Blueprint] Jane the Virgin

### ISSUE THREAD

**Issue by Natejt** [TitleCardMaker/Blueprints#816]
### Series Name

Jane the Virgin

### Series Year

2014

### Series Database IDs

imdb:tt3566726,tmdb:61418,tvdb:281621

### Blueprint Description

Calligraphy style card for the texture, logo and chapter font matching the show.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "calligraphy",
    "hide_season_text": true,
    "hide_episode_text": true,
    "extra_keys": [
      "subtitle"
    ],
    "extra_values": [
      "\"\""
    ],
    "auto_split_title": false
  },
  "fonts": [
    {
      "name": "Courier New",
      "file": "cour.ttf",
      "line_split_modifier": 30,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/TitleCardMaker/Blueprints/assets/14960259/f7b3ed6d-129c-4f98-ac5b-e1ff9b2cb593)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16045171/fonts.zip)

### Zip of Source Files

[logo.zip](https://github.com/user-attachments/files/16045176/logo.zip)

**Comment by CollinHeist** [comment]
Thanks! Nice job /create-blueprint
