### ISSUE TITLE
[Blueprint] Batman Beyond

### ISSUE THREAD

**Issue by Visnes** [TitleCardMaker/Blueprints#818]
### Series Name

Batman Beyond

### Series Year

1999

### Series Database IDs

imdb:tt0147746,tmdb:513,tvdb:75417

### Creator Username

Visnes

### Blueprint Description

Standard card type with white episode titles in the middle on a dark blurred background in grayscale. Use with blurred grayscale style.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0
  },
  "fonts": [
    {
      "name": "Batman Beyond",
      "color": "#FFFFFF",
      "file": "batmanbeyond.ttf",
      "title_case": "source",
      "size": 1.5
    }
  ]
}
```

### Preview Title Cards

![card-unique](https://github.com/TitleCardMaker/Blueprints/assets/15141314/ac7e4ce1-b870-409e-9ae6-59484ac67675)

### Zip of Font Files

[batmanbeyond.ttf.zip](https://github.com/user-attachments/files/16055425/batmanbeyond.ttf.zip)

**Comment by CollinHeist** [comment]
Okay looks good now! Thanks for submitting this /create-blueprint
