### ISSUE TITLE
[Blueprint] The Muppets

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#826]
### Series Name

The Muppets

### Series Year

2015

### Series Database IDs

imdb:tt4651824,tmdb:62815,tvdb:295721

### Creator Username

Reicha7

### Blueprint Description

Frame style card with office font to match show's poster.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "frame",
    "hide_season_text": true,
    "hide_episode_text": true,
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "The Muppets",
      "color": "black",
      "file": "TYPIST.TTF",
      "interword_spacing": 30,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/f1a1c148-69a5-44e1-8019-d1b039923e4e)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16227902/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! Thanks /create-blueprint
