### ISSUE TITLE
[Blueprint] Elfen Lied

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#828]
### Series Name

Elfen Lied

### Series Year

2004

### Series Database IDs

imdb:tt0480489,tmdb:42671,tvdb:75941

### Creator Username

Reicha7

### Blueprint Description

Anime style card with a custom Font, episode override for OVA. Designed for Absolute ordering.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "hide_season_text": true,
    "extra_keys": [
      "stroke_color",
      "kanji_vertical_shift",
      "kanji_font_size",
      "kanji_stroke_color",
      "episode_stroke_color"
    ],
    "extra_values": [
      "#7a181c",
      "70",
      "1.5",
      "#7a181c",
      "#7a181c"
    ]
  },
  "episodes": {
    "s1e11": {
      "extra_keys": [
        "kanji"
      ],
      "extra_values": [
        "\u901a\u308a\u96e8\u306b\u3066 \u6216\u3044"
      ]
    }
  },
  "fonts": [
    {
      "name": "Elfen Lied",
      "file": "YakuzaDemoRegular.ttf",
      "vertical_shift": -100,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/d76bbd5f-a7f4-4b9a-8c87-0b81de17d1b6)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16322680/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
