### ISSUE TITLE
[Blueprint] Gurren Lagann

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#829]
### Series Name

Gurren Lagann

### Series Year

2007

### Series Database IDs

imdb:tt0948103,tmdb:21729,tvdb:80096

### Creator Username

Reicha7

### Blueprint Description

Anime style card with a custom Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "translations": [
      {
        "language_code": "ja",
        "data_key": "kanji"
      }
    ],
    "hide_season_text": true
  },
  "fonts": [
    {
      "name": "Inter Medium",
      "color": "white",
      "file": "Inter-Medium.ttf",
      "kerning": -7.5,
      "title_case": "title"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/09aa8236-ddd8-4356-9faa-a6602b7c87f1)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16322703/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks 👍🏻 /create-blueprint
