### ISSUE TITLE
[Blueprint] Phineas and Ferb

### ISSUE THREAD

**Issue by Invictus6474** [TitleCardMaker/Blueprints#834]
### Series Name

Phineas and Ferb

### Series Year

2007

### Series Database IDs

imdb:tt0852863,tmdb:1877,tvdb:81848

### Creator Username

DBKrishnan

### Blueprint Description

Standard Card with SansPerry font (by creeonaskateboard). Preview Cards are using a blurred style.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Phineas and Ferb",
      "file": "SansPerry.ttf"
    }
  ]
}
```

### Preview Title Cards

![Phineas and Ferb (2007) - S01E01](https://github.com/user-attachments/assets/78748883-9a9d-41bf-9132-edef154f6bfa)
![Phineas and Ferb (2007) - S01E02](https://github.com/user-attachments/assets/c5865170-dbe3-4e07-ad29-66b3d5212b2a)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16370429/fonts.zip)

**Comment by CollinHeist** [comment]
@Invictus6474 Hey - thanks for submitting this! Looks good. /create-blueprint
