### ISSUE TITLE
[Blueprint] Altered Carbon

### ISSUE THREAD

**Issue by Invictus6474** [TitleCardMaker/Blueprints#835]
### Series Name

Altered Carbon

### Series Year

2018

### Series Database IDs

imdb:tt2261227,tmdb:68421,tvdb:332331

### Creator Username

DBKrishnan

### Blueprint Description

Standard Card with Altered Carbon font (by Difficultylevel) in red. Season and episode text are hidden. Preview Cards are using a blurred style.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "Altered Carbon",
      "color": "rgb(252, 4, 5)",
      "file": "Altered_Carbon_V1.ttf",
      "kerning": 2.0
    }
  ]
}
```

### Preview Title Cards

![Altered Carbon (2018) - S01E01](https://github.com/user-attachments/assets/40aec396-f130-4de8-8df7-3bb59dfa6b0f)
![Altered Carbon (2018) - S01E05](https://github.com/user-attachments/assets/ada308a2-d9a0-4c1c-a5c5-f9197ff8d8f0)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16382249/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks great. /create-blueprint
