### ISSUE TITLE
[Blueprint] Seven Worlds, One Planet

### ISSUE THREAD

**Issue by thomaswilliamsastro** [TitleCardMaker/Blueprints#841]
### Series Name

Seven Worlds, One Planet

### Series Year

2019

### Series Database IDs

imdb:tt9805708,tmdb:90790,tvdb:359251

### Creator Username

inapptom, Reicha7, CollinHeist

### Blueprint Description

Landscape card following CollinHeist and Reicha7's template.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ]
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/e5662f2c-34e6-4fb9-8ccb-b714ea405ed9)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16455031/fonts.zip)

### Set IDs

10

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
