### ISSUE TITLE
[Blueprint] Red Dwarf

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#842]
### Series Name

Red Dwarf

### Series Year

1988

### Series Database IDs

imdb:tt0094535,tmdb:326,tvdb:71326

### Creator Username

Cwavs

### Blueprint Description

Standard card type with in the series' Font. The season and episode text is hidden for The Promised Land.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": [],
    "source_files": []
  },
  "episodes": {
    "s0e23": {
      "hide_season_text": true,
      "hide_episode_text": true,
      "template_ids": []
    }
  },
  "fonts": [
    {
      "name": "Microgramma D Extended Bold - Red Dwarf",
      "file": "Microgramma D Extended Bold.otf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/50334592-6a54-485b-add7-aa7b6fd9ad82)

### Zip of Font Files

[fa1b9a.zip](https://github.com/user-attachments/files/16489085/fa1b9a.zip)

**Comment by Cwavs** [comment]
Sorry for the additional ping, just updated the description a tad.

**Comment by CollinHeist** [comment]
Totally fine - thanks! Looks great. /create-blueprint
