### ISSUE TITLE
[Blueprint] Inside Job

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#844]
### Series Name

Inside Job

### Series Year

2021

### Series Database IDs

imdb:tt10231312,tmdb:97727,tvdb:365098

### Creator Username

Cwavs

### Blueprint Description

Tinted Frame Plus with a similar font to the logo, and the part number instead of the season text.

You will need to manually set the "Episode Text Font" extra to the included Font file.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_font",
      "episode_text_font_size"
    ],
    "extra_values": [
      "/config/assets/fonts/22/SpecialElite-Regular.ttf",
      "1.5"
    ],
    "season_title_ranges": [
      "s1e1-s1e10",
      "s1e11-s1e18"
    ],
    "season_title_values": [
      "Part 1",
      "Part 2"
    ]
  },
  "fonts": [
    {
      "name": "Special Elite - Inside Job",
      "file": "SpecialElite-Regular.ttf",
      "size": 1.5,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/a6879a5c-e178-4a6f-8bf9-9e64decdece3)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16534499/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good /create-blueprint
