### ISSUE TITLE
[Blueprint] Platonic

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#849]
### Series Name

Platonic

### Series Year

2023

### Series Database IDs

imdb:tt13366604,tmdb:112211,tvdb:391020

### Creator Username

PJ

### Blueprint Description

Standard card type with a matching Font.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0
  },
  "fonts": [
    {
      "name": "Platonic",
      "file": "Mangueira-Heavy.ttf",
      "size": 1.25,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/8dba8d1a-8576-4300-a5e8-e5b7ffe57967)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16720288/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great - thanks! /create-blueprint
