### ISSUE TITLE
[Blueprint] Ashes to Ashes

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#851]
### Series Name

Ashes to Ashes

### Series Year

2008

### Series Database IDs

imdb:tt1008108,tmdb:1180,tvdb:81253

### Creator Username

Cwavs

### Blueprint Description

Music style title card with series logo and unofficial and official episode titles.

### Blueprint

```json
{
  "series": {
    "card_type": "music",
    "extra_keys": [
      "percentage"
    ],
    "extra_values": [
      "{episode_number / season_episode_max}"
    ]
  }
}
```

### Preview Title Cards

![out](https://github.com/user-attachments/assets/21420719-16cd-4ffd-ab01-9a7961ecdbed)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
