### ISSUE TITLE
[Blueprint] Based on a True Story

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#853]
### Series Name

Based on a True Story

### Series Year

2023

### Series Database IDs

imdb:tt19500224,tmdb:197373,tvdb:418934

### Creator Username

PJ

### Blueprint Description

Tinted Frame card with a matching color and font, and a logo as the top element. Inspired by ilovetea on MediUX.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "frame_color",
      "top_element",
      "bottom_element",
      "logo_size",
      "shadow_color"
    ],
    "extra_values": [
      "rgb(254, 229, 48)",
      "logo",
      "title",
      "1.5",
      "rgb(242, 68, 80)"
    ]
  },
  "fonts": [
    {
      "name": "Based on a True Story",
      "file": "Geomatrix.ttf",
      "color": "rgb(254, 229, 48)",
      "size": 1.4
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/6f55632c-899c-440c-9f77-cdf69d495360)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16754660/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great, thanks! /create-blueprint
