### ISSUE TITLE
[Set] Life on Mars

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#854]
### Set Name

Life on Mars (a.k.a. Gene Hunt's World)

### Blueprints

blueprints/A/Ashes to Ashes (2008)/0
blueprints/L/Life on Mars (2006)/0

**Comment by Cwavs** [comment]
Alternate fun title: Gene Hunt's World

**Comment by CollinHeist** [comment]
Love it 👍🏻 Thanks! /create-set
