### ISSUE TITLE
[Blueprint] RWBY

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#856]
### Series Name

RWBY

### Series Year

2013

### Series Database IDs

imdb:tt3066242,tmdb:50137,tvdb:263999

### Creator Username

Cwavs

### Blueprint Description

Tinted Frame Plus with red series logo, and other colors adjusted to match the other character's accent colors. Logo font is used for the text, and Season and Episode have been substituted for Volume and Chapter respectively.

You will need to manually set the "Episode Text Font" extra to the included Font file.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "episode_text_format": "Chapter {episode_number}",
    "season_title_ranges": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ],
    "season_title_values": [
      "Volume 1",
      "Volume 2",
      "Volume 3",
      "Volume 4",
      "Volume 5",
      "Volume 6",
      "Volume 7",
      "Volume 8",
      "Volume 9"
    ],
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "frame_color"
    ],
    "extra_values": [
      "rgb(246, 197, 102)",
      "1.5",
      "rgb(42, 39, 50)"
    ]
  },
  "fonts": [
    {
      "name": "RWBY Font",
      "color": "rgb(255, 255, 255)",
      "title_case": "title",
      "file": "RWBY-Z.ttf"
    }
  ]
}
```

### Preview Title Cards

![out](https://github.com/user-attachments/assets/36550736-80ff-4685-b68d-51e3676b20ac)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16788208/fonts.zip)

**Comment by CollinHeist** [comment]
@Cwavs Looks really good, thanks! I made one change: TCM has an "Episode Text Format" setting that you can set so that all episode texts are dynamically changed - I used this instead of manually setting the "chapter" title in the episode text of every Episode. /create-blueprint

**Comment by Cwavs** [comment]
Ahhh that's what that's for. I was wondering if there was an easier way to do it, but I couldn't find any documentation on it!
