### ISSUE TITLE
[Blueprint] RWBY: Ice Queendom

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#857]
### Series Name

RWBY: Ice Queendom

### Series Year

2022

### Series Database IDs

imdb:tt19389868,tmdb:195966,tvdb:418203

### Creator Username

Cwavs

### Blueprint Description

Tinted Frame Plus with red series logo, and other colors adjusted to match the other character's accent colors. Logo font is used for text and Season and Episode have been substituted for Volume and Chapter respectively.

You will need to manually set the "Episode Text Font" extra to the included Font file.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "episode_text_format": "Chapter {episode_number}",
    "season_title_ranges": [
      "1"
    ],
    "season_title_values": [
      "Volume 1"
    ],
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "frame_color"
    ],
    "extra_values": [
      "rgb(255, 255, 0)",
      "1.5",
      "rgb(0, 0, 0)"
    ]
  },
  "fonts": [
    {
      "name": "RWBY Font",
      "color": "rgb(255, 255, 255)",
      "title_case": "title",
      "file": "RWBY-Z.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/67cd1425-c917-4475-b898-0a8eb415daf8)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16788230/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks again! I made the same change here, too. /create-blueprint
