### ISSUE TITLE
[Set] RWBY

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#858]
### Set Name

RWBY Universe

### Blueprints

blueprints/r/RWBY (2013)/0
blueprints/r/RWBY - Ice Queendom (2022)/0

**Comment by Cwavs** [comment]
Preemptive for when the sets get merged.

**Comment by CollinHeist** [comment]
Sets can be created while they're on `staging`, so we should be good. Thanks! /create-set
