### ISSUE TITLE
[Blueprint] Lego Star Wars: Rebuild the Galaxy

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#860]
### Series Name

Lego Star Wars: Rebuild the Galaxy

### Series Year

2024

### Series Database IDs

imdb:tt32306451,tmdb:253760,tvdb:449814

### Creator Username

TechJedi51

### Blueprint Description

Gold title and LEGO red border, using the LEGO Outline font. The logo file is included.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "frame_color",
      "frame_width",
      "top_element",
      "bottom_element",
      "logo_size",
      "logo_vertical_shift"
    ],
    "extra_values": [
      "yellow",
      "red",
      "12",
      "logo",
      "title",
      "4",
      "200"
    ]
  },
  "fonts": [
    {
      "name": "LEGO",
      "color": "white",
      "file": "Legothick.ttf",
      "size": 2.0,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![Screenshot 2024-09-13 at 9 43 19 AM](https://github.com/user-attachments/assets/9162fa98-3405-4397-bf7f-9d2d6fbfa122)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16997001/fonts.zip)

### Zip of Source Files

[logo.png.zip](https://github.com/user-attachments/files/16997007/logo.png.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good. /create-blueprint
