### ISSUE TITLE
[Blueprint] Judy Justice

### ISSUE THREAD

**Issue by TechJedi51** [TitleCardMaker/Blueprints#861]
### Series Name

Judy Justice

### Series Year

2021

### Series Database IDs

imdb:tt13368190,tmdb:114294,tvdb:391619

### Creator Username

TechJedi51

### Blueprint Description

Tinted Frame Plus card type, with the font color adjusted to match the gold in the logo. Easier to read with a black text shadow.

### Blueprint

```json
{
  "series": {
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size",
      "frame_color",
      "frame_width",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "#DFA46D",
      "2.0",
      "#55053B",
      "8",
      "logo",
      "index",
      "2.0"
    ],
    "font_color": "#DFA46D"
  }
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/3eca1bc4-126b-41d9-bc04-25f1c8c94808)

**Comment by CollinHeist** [comment]
Thanks again! /create-blueprint
