### ISSUE TITLE
[Blueprint] Goosebumps

### ISSUE THREAD

**Issue by azuravian** [TitleCardMaker/Blueprints#862]
### Series Name

Goosebumps

### Series Year

2023

### Series Database IDs

imdb:tt17720272,tmdb:157004,tvdb:415840

### Creator Username

Azuravian

### Blueprint Description

Uses the Standard card type with a free font based off of the Goosebumps logo.  The logo itself is not a font and is hand-made.

Episode title text uses a blue color similar to the poster for the series.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "episode_text_vertical_shift",
      "episode_text_color"
    ],
    "extra_values": [
      "20",
      "white"
    ]
  },
  "fonts": [
    {
      "name": "Goosebumps",
      "color": "rgb(86, 189, 194)",
      "size": 1.25,
      "vertical_shift": -20,
      "file": "Gortem.woff",
      "title_case": "title"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/1ef75733-03a6-4a18-888d-74a69c85429e)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17040616/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
