### ISSUE TITLE
[Blueprint] Bad Sisters

### ISSUE THREAD

**Issue by iloveteaandcoffee** [TitleCardMaker/Blueprints#863]
### Series Name

Bad Sisters

### Series Year

2022

### Series Database IDs

imdb:tt15469618,tmdb:199318,tvdb:418182

### Creator Username

iloveteaandcoffee

### Blueprint Description

Music card type series with a matching Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "music",
    "extra_keys": [
      "player_style",
      "player_width",
      "subtitle"
    ],
    "extra_values": [
      "logo",
      "1050",
      "{\"\"}"
    ],
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Bad Sisters",
      "file": "Kiona-Regular.ttf"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/a75e4f8e-0fb6-4738-927a-cf33976e2cdf)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17043208/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks - looks great! /create-blueprint
