### ISSUE TITLE
[Blueprint] Agatha All Along

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#872]
### Series Name

Agatha All Along

### Series Year

2024

### Series Database IDs

imdb:tt15571732,tmdb:138501,tvdb:412429

### Creator Username

Reicha7

### Blueprint Description

Templated Marvel Style Card with "Miniseries" for the season

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "season_title_ranges": [
      "1"
    ],
    "season_title_values": [
      "Miniseries"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "episodes": {
    "s1e2": {
      "template_ids": [],
      "auto_split_title": false
    }
  },
  "templates": [
    {
      "card_type": "marvel",
      "name": "DC and Marvel",
      "filters": []
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/950aa8a1-11a4-40ed-923e-e26ceb3d7d2a)

### Set IDs

2

**Comment by CollinHeist** [comment]
Looks great! Thanks /create-blueprint
