### ISSUE TITLE
[Blueprint] The Penguin

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#873]
### Series Name

The Penguin

### Series Year

2024

### Series Database IDs

imdb:tt15435876,tmdb:194764,tvdb:417648

### Creator Username

Reicha7

### Blueprint Description

Marvel Style Templated Card with Miniseries override for season

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "season_title_ranges": [
      "1"
    ],
    "season_title_values": [
      "Miniseries"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "card_type": "marvel",
      "name": "DC and Marvel",
      "filters": []
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/610b38ae-e3a1-4acb-b48d-bba1bf554d9f)

### Set IDs

16

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
