### ISSUE TITLE
[Blueprint] The IT Crowd

### ISSUE THREAD

**Issue by iloveteaandcoffee** [TitleCardMaker/Blueprints#877]
### Series Name

The IT Crowd

### Series Year

2006

### Series Database IDs

imdb:tt0487831,tmdb:2490,tvdb:79216

### Creator Username

iloveteaandcoffee

### Blueprint Description

IT Crowd cards using the music title card with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "music",
    "extra_keys": [
      "episode_text_color",
      "player_width",
      "subtitle",
      "timeline_color"
    ],
    "extra_values": [
      "rgba(252,252,251,255)",
      "1050",
      "\"\"",
      "rgba(252,252,251,255)"
    ],
    "match_titles": false
  },
  "fonts": [
    {
      "name": "IT Crowd",
      "file": "LettersLaughingattheirExecution.ttf",
      "color": "rgba(252,252,251,255)",
      "kerning": 1.5
    }
  ]
}
```

### Preview Title Cards

![The IT Crowd (2006) - S01E01](https://github.com/user-attachments/assets/647eb68b-1eec-43b7-b22a-e4ac911b81e1)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17097050/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint
