### ISSUE TITLE
[Blueprint] Sausage Party: Foodtopia

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#880]
### Series Name

Sausage Party: Foodtopia

### Series Year

2024

### Series Database IDs

imdb:tt23036426,tmdb:213249,tvdb:426452

### Creator Username

Reicha7

### Blueprint Description

Basic name-only style card with font colours to match show's logo.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "hide_season_text": true,
    "hide_episode_text": true,
    "font_id": 0,
    "extra_keys": [
      "stroke_color",
      "omit_gradient"
    ],
    "extra_values": [
      "yellow",
      "true"
    ]
  },
  "fonts": [
    {
      "name": "Sausage Party",
      "file": "impact.ttf",
      "size": 2.0,
      "color": "red",
      "stroke_width": 1.0,
      "vertical_shift": -200
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/47437c56-5456-43dc-af03-b93ad3396403)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17139189/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
