### ISSUE TITLE
[Blueprint] Landscapers

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#882]
### Series Name

Landscapers

### Series Year

2021

### Series Database IDs

imdb:tt11471892,tmdb:113987,tvdb:375516

### Creator Username

Reicha7

### Blueprint Description

Simple name-only template

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0,
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "Landscapers",
      "file": "impact.ttf",
      "size": 2.0
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/02031fb9-d4cf-45bc-8b6a-cbae854f2465)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17139371/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks again! /create-blueprint
