### ISSUE TITLE
[Blueprint] Everybody Still Hates Chris

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#891]
### Series Name

Everybody Still Hates Chris

### Series Year

2024

### Series Database IDs

imdb:tt15121038,tvdb:423040

### Creator Username

PJ

### Blueprint Description

Standard card with a simple font and the color matched

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "stroke_color",
      "omit_gradient",
      "episode_text_color"
    ],
    "extra_values": [
      "rgb(48, 52, 180)",
      "false",
      "rgb(197, 28, 231)"
    ]
  },
  "fonts": [
    {
      "name": "Everybody Hates Chris",
      "file": "COOPBL.TTF",
      "color": "rgb(200, 255, 102)",
      "size": 1.0,
      "stroke_width": 1.52,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/1b3e0ef9-6fac-4444-a202-d731cefb4aad)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17175968/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
