### ISSUE TITLE
[Blueprint] Agatha All Along

### ISSUE THREAD

**Issue by azuravian** [TitleCardMaker/Blueprints#893]
### Series Name

Agatha All Along

### Series Year

2024

### Series Database IDs

imdb:tt15571732,tmdb:138501,tvdb:412429

### Creator Username

Azuravian

### Blueprint Description

Marvel card with all white text on a dark purple background (color obtained using Analyze Palette on the official logo).

This is one of a series of Blueprints for Marvel series with each using the Marvel card with a colored bottom text box to match the show.

### Blueprint

```json
{
  "series": {
    "card_type": "marvel",
    "extra_keys": [
      "episode_text_color",
      "text_box_color"
    ],
    "extra_values": [
      "white",
      "rgb(23, 15, 44)"
    ],
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![image](https://github.com/user-attachments/assets/0a1b6f0e-5216-4970-a4d8-5298310394cf)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
