### ISSUE TITLE
[Blueprint] WandaVision

### ISSUE THREAD

**Issue by azuravian** [TitleCardMaker/Blueprints#894]
### Series Name

WandaVision

### Series Year

2021

### Series Database IDs

imdb:tt9140560,tmdb:85271,tvdb:362392

### Blueprint Description

Marvel card with all white text on a red background (color obtained using Analyze Palette on the official logo).

This is one of a series of Blueprints for Marvel series with each using the Marvel card with a colored bottom text box to match the show.

### Blueprint

```json
{
  "series": {
    "card_type": "marvel",
    "extra_keys": [
      "episode_text_color",
      "text_box_color"
    ],
    "extra_values": [
      "white",
      "rgb(212, 29, 30)"
    ],
    "template_ids": [],
    "source_files": []
  }
}
```

### Preview Title Cards

![image](https://github.com/user-attachments/assets/b5f97002-6d7d-4e84-a99d-ec39bad3b984)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
