### ISSUE TITLE
[Blueprint] Sweetpea

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#922]
### Series Name

Sweetpea

### Series Year

2024

### Series Database IDs

imdb:tt11218290,tvdb:421654

### Creator Username

PJ

### Blueprint Description

Simple Font matched with the Olivier card type.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "extra_keys": [
      "episode_text_vertical_shift",
      "omit_gradient"
    ],
    "extra_values": [
      "30",
      "false"
    ]
  },
  "fonts": [
    {
      "name": "Sweetpea",
      "color": "rgb(253, 152, 213)",
      "file": "mondia-light.otf",
      "size": 1.8,
      "stroke_width": 0.5,
      "title_case": "lower",
      "interline_spacing": -80
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/90cb3099-5328-4b48-bf41-425b5114bb9d)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17335928/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
