### ISSUE TITLE
[Blueprint] Shrinking

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#923]
### Series Name

Shrinking

### Series Year

2023

### Series Database IDs

imdb:tt15677150,tmdb:136311,tvdb:411364

### Creator Username

PJ

### Blueprint Description

Olivier card type with a matching Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "extra_keys": [
      "omit_gradient",
      "episode_text_font_size"
    ],
    "extra_values": [
      "false",
      "0.9"
    ]
  },
  "fonts": [
    {
      "name": "Shrinking",
      "file": "BostonSemiBold.otf",
      "size": 1.2,
      "stroke_width": 1.1,
      "replacements_in": [
        "i",
        "I"
      ],
      "replacements_out": [
        "¡",
        "¡"
      ],
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/6d20655b-33ce-457b-9926-4a914ceeb940)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17398553/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! looks good. /create-blueprint
