### ISSUE TITLE
[Blueprint] RuPaul's Drag Race

### ISSUE THREAD

**Issue by stripedew** [TitleCardMaker/Blueprints#929]
### Series Name

RuPaul's Drag Race

### Series Year

2009

### Series Database IDs

imdb:tt1353056,tmdb:8514, tvdb:85002

### Creator Username

stripedew

### Blueprint Description

Tinted Frame with the closest-matching font. Can be easily applied to all the other franchises (All Stars, UK, Germany, France, etc.) with just a logo change. Includes the logo file.

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "tinted frame",
      "extra_keys": [
        "episode_text_font_size",
        "frame_width",
        "top_element",
        "middle_element",
        "bottom_element",
        "logo_size"
      ],
      "extra_values": [
        "2",
        "3",
        "logo",
        "omit",
        "title",
        "1.3"
      ],
      "name": "Drag Race",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Drag Race",
      "file": "Drag Race.ttf",
      "kerning": 0.7,
      "interword_spacing": 40,
      "size": 1.35,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/e3825a20-c6df-418e-809f-3bcb0b7ca007)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17507533/fonts.zip)

### Zip of Source Files

[source.zip](https://github.com/user-attachments/files/17507551/source.zip)

**Comment by CollinHeist** [comment]
Thanks! looks great. /create-blueprint
