### ISSUE TITLE
[Blueprint] Brassic

### ISSUE THREAD

**Issue by PJGitHub9** [TitleCardMaker/Blueprints#930]
### Series Name

Brassic

### Series Year

2019

### Series Database IDs

imdb:tt9174582,tmdb:92621,tvdb:351960

### Creator Username

PJ

### Blueprint Description

Notification style with font/color match

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "notification",
    "extra_keys": [
      "glass_color"
    ],
    "extra_values": [
      "rgb(248, 1, 56)"
    ]
  },
  "fonts": [
    {
      "name": "Brassic",
      "color": "rgb(248, 245, 223)",
      "file": "Helvetica Neue LT Std 83 Heavy Extended.otf",
      "interword_spacing": 40,
      "size": 1.1,
      "stroke_width": 0.8,
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/dfbf8083-ca94-4076-a644-72cfaca7fa89)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17557734/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks great /create-blueprint
