### ISSUE TITLE
[Blueprint] What We Do in the Shadows

### ISSUE THREAD

**Issue by foux** [TitleCardMaker/Blueprints#931]
### Series Name

What We Do in the Shadows

### Series Year

2019

### Series Database IDs

imdb:tt7908628,tmdb:83631,tvdb:358211

### Creator Username

foux

### Blueprint Description

Tinted frame with logo on top and title on the bottom with the series font and the same color as the logo

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "What We Do in the Shadows",
      "color": "#6EEC47",
      "file": "Halja Illuminated.ttf",
      "replacements_in": [
        "\u00c2",
        "\u00ca"
      ],
      "replacements_out": [
        "A",
        "E"
      ],
      "size": 1.35,
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/1f7448b2-c28b-4a58-b342-aa53cc5c83f0)
![preview2](https://github.com/user-attachments/assets/4c27ccef-4cba-4ef2-8706-a4ba616ca47d)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17558834/fonts.zip)

### Zip of Source Files
[sources.zip](https://github.com/user-attachments/files/17560129/sources.zip)

**Comment by CollinHeist** [comment]
@foux Yes, looks like you submitted the issue before the source files were finished uploading (it says "Uploading sources.zip.." when it should just say "sources.zip" when finished)

**Comment by CollinHeist** [comment]
I still see the "bad" zip, but you don't have to remove them you can just re-upload the zip and let it finish this time
