### ISSUE TITLE
[Blueprint] Sentinelles

### ISSUE THREAD

**Issue by foux** [TitleCardMaker/Blueprints#933]
### Series Name

Sentinelles

### Series Year

2022

### Series Database IDs

imdb:tt18549982,tmdb:195657,tvdb:414229

### Creator Username

foux

### Blueprint Description

Logo card with text in the color of the logo. Season and episode text are translated into French, as it is a French series.

### Blueprint

```json
{
  "series": {
    "card_type": "logo",
    "font_color": "rgb(243, 190, 118)",
    "episode_text_format": "\u00c9pisode {episode_number}",
    "season_title_ranges": [
      "s1e1-s30e89"
    ],
    "season_title_values": [
      "Saison {season_number}"
    ]
  }
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/bf634ca4-db1a-4f5c-815a-96c4c0730b88)

### Zip of Source Files

[sources.zip](https://github.com/user-attachments/files/17561809/sources.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
