### ISSUE TITLE
[Blueprint] Star Trek (1966)

### ISSUE THREAD

**Issue by TheChrisK** [TitleCardMaker/Blueprints#935]
### Series Name

Star Trek

### Series Year

1966

### Series Database IDs

imdb:tt0060028

### Creator Username

TheChrisK

### Blueprint Description

Standard card type using the "Edge of the Galaxy" font. The color scheme matches this poster by RedHeadJedi https://theposterdb.com/poster/21375

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "extra_keys": [
      "episode_text_color",
      "episode_text_font_size"
    ],
    "extra_values": [
      "#F7A9AC",
      "1.2"
    ],
    "font_id": 0,
    "source_files": []
  },
  "fonts": [
    {
      "name": "Star Trek",
      "color": "#F7A9AC",
      "file": "EdgeOfTheGalaxyRegular-OVEa6.otf",
      "size": 1.25
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/133be263-3171-4e2c-9162-76e920bc1124)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17759050/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great, thanks! /create-blueprint
