### ISSUE TITLE
[Blueprint] Asia

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#938]
### Series Name

Asia

### Series Year

2024

### Series Database IDs

imdb:tt32869282,tmdb:271144,tvdb:455395

### Creator Username

Reicha7

### Blueprint Description

Landscape documentary-style template

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/c8cc1dd5-7412-4272-ab92-503ef1709d58)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17891546/fonts.zip)

### Set IDs

10

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
