### ISSUE TITLE
[Blueprint] Frozen Planet

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#939]
### Series Name

Frozen Planet

### Series Year

2011

### Series Database IDs

imdb:tt2092588,tmdb:8724,tvdb:251418

### Creator Username

Reicha7

### Blueprint Description

Landscape documentary-style template

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/12900fc9-38cd-4cfb-9bed-442b4f398f54)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17891551/fonts.zip)

### Set IDs

10

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
