### ISSUE TITLE
[Blueprint] Frozen Planet II

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#940]
### Series Name

Frozen Planet II

### Series Year

2022

### Series Database IDs

imdb:tt9805678,tmdb:116155,tvdb:417395

### Creator Username

Reicha7

### Blueprint Description

Landscape documentary-style template

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/608239da-f928-42d9-88a2-c7f114942407)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17891554/fonts.zip)

### Set IDs

10

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
