### ISSUE TITLE
[Blueprint] Africa

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#941]
### Series Name

Africa

### Series Year

2013

### Series Database IDs

imdb:tt2571774,tmdb:46664,tvdb:265145

### Creator Username

Reicha7

### Blueprint Description

Landscape documentary-style template

### Blueprint

```json
{
  "series": {
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "landscape",
      "name": "Documentary"
    }
  ],
  "fonts": [
    {
      "name": "Helvetica_Documentary",
      "file": "Helvetica.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/6304461f-a090-44a5-bd6d-e8be9f4c7f2f)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17891556/fonts.zip)

### Set IDs

10

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
