### ISSUE TITLE
[Blueprint] Dune: Prophecy

### ISSUE THREAD

**Issue by Sproglet** [TitleCardMaker/Blueprints#944]
### Series Name

Dune: Prophecy

### Series Year

2024

### Series Database IDs

imdb:tt10466872,tmdb:90228,tvdb:367118

### Creator Username

Sproglet

### Blueprint Description

A Negative Space based Blueprint with the Dune Rise Font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "negative space",
    "extra_keys": [
      "episode_text_color",
      "text_side"
    ],
    "extra_values": [
      "white",
      "random"
    ]
  },
  "fonts": [
    {
      "name": "Dune Rise",
      "file": "Dune_Rise.otf",
      "title_case": "upper",
      "size": 1.1,
      "kerning": 2.0,
      "interline_spacing": 32
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/f2285828-0b06-4cc5-9ead-36961314cea9)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/17897028/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks /create-blueprint
