### ISSUE TITLE
[Blueprint] Chuck

### ISSUE THREAD

**Issue by Sproglet** [TitleCardMaker/Blueprints#950]
### Series Name

Chuck

### Series Year

2007

### Series Database IDs

imdb:tt0934814,tmdb:1404,tvdb:80348

### Creator Username

Sproglet

### Blueprint Description

Chuck series based on the Comic Book using a custom font similar to the series font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "comic book",
    "extra_keys": [
      "text_box_edge_color",
      "title_text_rotation_angle"
    ],
    "extra_values": [
      "White",
      "random[-4, 4] "
    ]
  },
  "fonts": [
    {
      "name": "Chuck",
      "file": "Embossed.otf",
      "color": "red",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/aa7c13a4-bf6a-4134-9246-477a72bb2180)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18016786/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks great /create-blueprint
