### ISSUE TITLE
[Blueprint] Stargate SG-1

### ISSUE THREAD

**Issue by Sproglet** [TitleCardMaker/Blueprints#951]
### Series Name

Stargate SG-1

### Series Year

1997

### Series Database IDs

imdb:tt0118480,tmdb:4629,tvdb:72449

### Creator Username

Sproglet

### Blueprint Description

Stargate SG-1 blueprint using the Stargate font and replacements for some titles.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "azuravian/TitleColorMatch",
    "font_color": "#C0C0C0"
  },
  "fonts": [
    {
      "name": "Stargate",
      "file": "stargate.ttf",
      "kerning": 0.9,
      "interline_spacing": 25,
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)"
      ],
      "replacements_out": [
        ": Part 1",
        ": Part 2",
        ": Part 3"
      ],
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards
![preview](https://github.com/user-attachments/assets/51272890-94b9-4b5a-9f9a-e217976b6ec9)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18017223/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks so much, looks great! /create-blueprint
