### ISSUE TITLE
[Blueprint] Stargate Atlantis

### ISSUE THREAD

**Issue by Sproglet** [TitleCardMaker/Blueprints#952]
### Series Name

Stargate Atlantis

### Series Year

2004

### Series Database IDs

imdb:tt0374455,tmdb:2290,tvdb:70851

### Blueprint Description

Stargate Atlantis blueprint with the Stargate font and some title changes.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "azuravian/TitleColorMatch"
  },
  "fonts": [
    {
      "name": "Stargate",
      "file": "stargate.ttf",
      "kerning": 0.9,
      "interline_spacing": 25,
      "replacements_in": [
        "(1)",
        "(2)",
        "(3)"
      ],
      "replacements_out": [
        ": Part 1",
        ": Part 2",
        ": Part 3"
      ],
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/fc783402-7b97-4e0e-831c-01f532a577cd)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18017274/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good /create-blueprint
