### ISSUE TITLE
[Blueprint] Rescue: HI-Surf

### ISSUE THREAD

**Issue by Archigos** [TitleCardMaker/Blueprints#953]
### Series Name

Rescue: HI-Surf

### Series Year

2024

### Series Database IDs

imdb:tt27629382,tmdb:227854,tvdb:434419

### Creator Username

Archigos

### Blueprint Description

Using Tinted Frame Plus card type with a Font called 'Airbourne' (from fontzillion) and colors tweaked to roughly match the logo/color theme.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "KHthe8th/TintedFramePlus",
    "extra_keys": [
      "episode_text_color",
      "logo_size"
    ],
    "extra_values": [
      "Gold",
      "1.2"
    ]
  },
  "fonts": [
    {
      "name": "Rescue Hi-Surf",
      "file": "airborne.ttf",
      "color": "red",
      "stroke_width": 0.0
    }
  ]
}
```

### Preview Title Cards

![Rescue - HI-Surf (2024) - S01E01 - Pilot-thumb](https://github.com/user-attachments/assets/e383a02a-5fba-48ec-a59e-c0ea5e3befde)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18018066/fonts.zip)

### Zip of Source Files

[logo.zip](https://github.com/user-attachments/files/18018101/logo.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good /create-blueprint
