### ISSUE TITLE
[Blueprint] Three-Body

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#958]
### Series Name

Three-Body

### Series Year

2023

### Series Database IDs

imdb:tt20242042,tmdb:204541,tvdb:421555

### Creator Username

Reicha7

### Blueprint Description

Standard card with some custom title override to use cardinal numbering to match the show title.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0,
    "extra_keys": [
      "title_text_format"
    ],
    "extra_values": [
      "EPISODE  {to_cardinal(episode_number)}"
    ],
    "hide_season_text": true,
    "hide_episode_text": true
  },
  "fonts": [
    {
      "name": "TV_Large",
      "file": "impact.ttf",
      "color": "rgb(223, 215, 202)",
      "size": 2.0,
      "title_case": "upper",
      "vertical_shift": -200
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/d253ed64-4820-41d1-b0a2-12703e3330ed)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18050259/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
