### ISSUE TITLE
[Blueprint] Our Flag Means Death

### ISSUE THREAD

**Issue by archieyates** [TitleCardMaker/Blueprints#959]
### Series Name

Our Flag Means Death

### Series Year

2022

### Series Database IDs

imdb:tt11000902,tmdb:109939,tvdb:390093

### Creator Username

Reicha7, rtgurley

### Blueprint Description

Shape style card with semi-uniform bars (to represent planks of wood) using rtgurley's font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "striped",
    "extra_keys": [
      "episode_text_color",
      "overlay_color",
      "polygons"
    ],
    "extra_values": [
      "rgb(255, 10, 149)",
      "black",
      "random[m]"
    ],
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Our Flag Means Death",
      "color": "#FF0C95",
      "file": "Seagram tfb.ttf",
      "title_case": "source"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/2d514ba8-7c1e-485d-8243-3cf17deed3b5)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18050339/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Thanks /create-blueprint
