### ISSUE TITLE
[Blueprint] Metalocalypse

### ISSUE THREAD

**Issue by Chrisophogus** [TitleCardMaker/Blueprints#962]
### Series Name

Metalocalypse

### Series Year

2006

### Series Database IDs

imdb:tt0839,tvdb:79563,tmdb:653

### Creator Username

Chris

### Blueprint Description

A modification of the Cutout card to use the show title and have episode title in show font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "cutout",
    "hide_season_text": true,
    "episode_text_format": "{series_name}",
    "match_titles": false,
    "extra_keys": [
      "overlay_transparency"
    ],
    "extra_values": [
      "0.1"
    ]
  },
  "episodes": {
    "s1e3": {
      "title": "Happy Dethday (a.k.a. Birthdayface)"
    },
    "s1e8": {
      "title": "Snakes N' Barrels"
    },
    "s1e10": {
      "title": "Fat Kid at the Detharmonic (a.k.a. FatKlok)"
    }
  },
  "fonts": [
    {
      "name": "Metalocalypse",
      "file": "BlackCastleMF.ttf",
      "title_case": "upper"
    }
  ]
}
```

### Preview Title Cards

![Preview 01](https://github.com/user-attachments/assets/6ae76021-7fd2-4762-b32a-934c1ea8d283)
![Preview 02](https://github.com/user-attachments/assets/80beea2f-79f2-4bde-a060-dd38d2b11acc)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18126053/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks great. /create-blueprint
