### ISSUE TITLE
[Blueprint] Cyberpunk: Edgerunners

### ISSUE THREAD

**Issue by l33xu** [TitleCardMaker/Blueprints#966]
### Series Name

Cyberpunk: Edgerunners

### Series Year

2022

### Series Database IDs

imdb:tt12590266,tmdb:105248,tvdb:384541

### Blueprint Description

Azuravian's TitleColorMatch card using a cyberpunk-looking font, with the logo in top left corner.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "azuravian/TitleColorMatch",
    "hide_season_text": true
  },
  "fonts": [
    {
      "name": "Cyberpunk Edgerunners",
      "color": "yellow",
      "file": "CyberwayRiders-lg97d.ttf",
      "interline_spacing": 9,
      "interword_spacing": 4,
      "title_case": "lower",
      "vertical_shift": 8
    }
  ]
}
```

### Preview Title Cards

![card-unique](https://github.com/user-attachments/assets/e828ea74-989c-4495-a3e7-10211cb1abfe)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18138276/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Nice job /create-blueprint
