### ISSUE TITLE
[Blueprint] Dexter: Original Sin

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#971]
### Series Name

Dexter: Original Sin

### Series Year

2024

### Series Database IDs

imdb:tt32252772,tmdb:219937,tvdb:430780

### Creator Username

Cwavs, CollinHeist

### Blueprint Description

 Overline card type using the Series Font and a "blood" red coloring for the line - re-uses the Template and Font from the original Dexter Blueprint. Season 1 is replaced with the series subtitle.

### Blueprint

```json
{
  "series": {
    "season_title_ranges": [
      "1"
    ],
    "season_title_values": [
      "Original Sin"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "overline",
      "extra_keys": [
        "line_color",
        "line_width"
      ],
      "extra_values": [
        "rgb(210,45,31)",
        "10"
      ],
      "name": "Dexter",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Dexter",
      "file": "dexter.ttf",
      "interline_spacing": -30,
      "interword_spacing": -15
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/da311dc1-6c62-4747-86e7-c3075619ef7a)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18156955/fonts.zip)

**Comment by CollinHeist** [comment]
@Cwavs Do you mind updating the preview card to reflect the actual cards? Looks like the one that's uploaded is for a Standard card. And what's the difference between this one and #972?

**Comment by CollinHeist** [comment]
Oh and if you want a longer description you can, you just have to split it into multiple paragraphs/lines. There is a 250 character limit on each paragraph (for legibility)

**Comment by Cwavs** [comment]
Ah it's fine, to be honest I prefer it in it's current state!

**Comment by CollinHeist** [comment]
Looks great! Thanks /create-blueprint
