### ISSUE TITLE
[Blueprint] Dexter: Original Sin

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#972]
### Series Name

Dexter: Original Sin

### Series Year

2024

### Series Database IDs

imdb:tt32252772,tmdb:219937,tvdb:430780

### Creator Username

CollinHeist, Cwavs

### Blueprint Description

Collin's Dexter and Dexter: New Blood blueprints but for Original Sin. Overline card type using the Series Font and a "blood" red coloring for the line - re-uses the Template and Font from the original Dexter Blueprint.

### Blueprint

```json
{
  "series": {
    "hide_season_text": true,
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "overline",
      "extra_keys": [
        "line_color",
        "line_width"
      ],
      "extra_values": [
        "rgb(210,45,31)",
        "10"
      ],
      "name": "Dexter",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Dexter",
      "file": "dexter.ttf",
      "interline_spacing": -30,
      "interword_spacing": -15
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/f8ad5bde-c9a4-49ae-9b4f-d6a489cd75e2)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18156990/fonts.zip)

**Comment by CollinHeist** [comment]
@Cwavs Did you want this one deleted / closed?

**Comment by Cwavs** [comment]
Nope, it is slightly different, I've just updated the preview to match.

**Comment by CollinHeist** [comment]
Ah I see, thanks! /create-blueprint

**Comment by Cwavs** [comment]
Thanks!
