### ISSUE TITLE
[Blueprint] Dexter: New Blood

### ISSUE THREAD

**Issue by Cwavs** [TitleCardMaker/Blueprints#974]
### Series Name

Dexter: New Blood

### Series Year

2021

### Series Database IDs

imdb:tt14164730,tmdb:131927,tvdb:412366

### Creator Username

Cwavs, CollinHeist

### Blueprint Description

Overline card type using the Series Font and a "blood" red coloring for the line - re-uses the Template and Font from the original Dexter Blueprint. Season 1 is replaced with the series subtitle.

### Blueprint

```json
{
  "series": {
    "season_title_ranges": [
      "1"
    ],
    "season_title_values": [
      "New Blood"
    ],
    "template_ids": [
      0
    ],
    "source_files": []
  },
  "templates": [
    {
      "font_id": 0,
      "card_type": "overline",
      "extra_keys": [
        "line_color",
        "line_width"
      ],
      "extra_values": [
        "rgb(210,45,31)",
        "10"
      ],
      "name": "Dexter",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Dexter",
      "file": "dexter.ttf",
      "interline_spacing": -30,
      "interword_spacing": -15
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/188c7807-150a-4ae6-b000-86309f9f7219)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18157072/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good - thanks! /create-blueprint

**Comment by Cwavs** [comment]
Thanks!
