### ISSUE TITLE
[Blueprint] What We Do in the Shadows

### ISSUE THREAD

**Issue by Chrisophogus** [TitleCardMaker/Blueprints#977]
### Series Name

What We Do in the Shadows

### Series Year

2019

### Series Database IDs

imdb:tt7908628,tmdb:83631,tvdb:358211

### Creator Username

Chris

### Blueprint Description

Minor modification of the Olivier Card type with the Series font in a thematic green color.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "extra_keys": [
      "episode_text_vertical_shift",
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "-20",
      "logo",
      "title"
    ]
  },
  "fonts": [
    {
      "name": "What We Do in the Shadows",
      "color": "#6EEC47",
      "size": 1.25,
      "kerning": 10.0,
      "stroke_width": 0.5,
      "file": "Halja Illuminated.ttf",
      "replacements_in": [
        "\u00c2",
        "\u00ca"
      ],
      "replacements_out": [
        "A",
        "E"
      ],
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![What We Do in the Shadows (2019) - S06E01](https://github.com/user-attachments/assets/8621f926-3db4-4da4-a73a-766d5446e6a6)
![What We Do in the Shadows (2019) - S06E02](https://github.com/user-attachments/assets/d7edf0a0-f252-4fb5-84e0-4bad103f195f)
![What We Do in the Shadows (2019) - S06E03](https://github.com/user-attachments/assets/cd0ad3f6-1f3c-4c1b-811c-fa36fa385406)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18172021/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great! Nice job /create-blueprint
