### ISSUE TITLE
[Blueprint] Stan Against Evil

### ISSUE THREAD

**Issue by Supremicus** [TitleCardMaker/Blueprints#978]
### Series Name

Stan Against Evil

### Series Year

2016

### Series Database IDs

imdb:tt5722214,tmdb:67832,tvdb:315153

### Blueprint Description

Dawn title card with custom font I made to match the show. Text colored to match show poster. Uses season format override to display cardinal. Has a title override to fit more evenly.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "Supremicus/DawnTitleCard",
    "extra_keys": [
      "season_text_format",
      "episode_text_vertical_shift",
      "episode_text_font",
      "episode_text_font_size",
      "episode_text_kerning",
      "omit_gradient"
    ],
    "extra_values": [
      "SEASON {to_cardinal(season_number)}",
      "60",
      "{title_font}",
      "0.9",
      "1",
      "False"
    ]
  },
  "episodes": {
    "s3e4": {
      "extra_keys": [
        "episode_text_vertical_shift"
      ],
      "extra_values": [
        "90"
      ],
      "template_ids": [],
      "auto_split_title": false,
      "title": "The Demon Who\\nCame in From the Heat",
      "match_title": false
    }
  },
  "fonts": [
    {
      "name": "Stan Against Evil",
      "color": "rgb(196, 212, 124)",
      "interline_spacing": 30,
      "file": "StanAgainstEvil.otf",
      "replacements_in": [
        "(1)",
        "(2)",
        "\u2019"
      ],
      "replacements_out": [
        ": Part 1",
        ": Part 2",
        "'"
      ],
      "size": 1.3
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/e69c6e03-dd4f-4d7d-9f3a-5c0f0fa715b3)
![preview1](https://github.com/user-attachments/assets/2664047a-fc72-451a-948e-e35b631926e7)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18203243/fonts.zip)

**Comment by Supremicus** [comment]
Worked out why kerning pairs wasn't working. Updated font and previews.

**Comment by CollinHeist** [comment]
@Supremicus Looks great! Nice job on the font, it looks awesome. /create-blueprint
