### ISSUE TITLE
[Blueprint] Reba

### ISSUE THREAD

**Issue by Sproglet** [TitleCardMaker/Blueprints#980]
### Series Name

Reba

### Series Year

2001

### Series Database IDs

imdb:tt0284722,tmdb:654,tvdb:71550

### Creator Username

Sproglet

### Blueprint Description

Reba template using the overfine card, the TV show font and the font in the logo colour

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "overline",
    "template_ids": [],
    "source_files": []
  },
  "fonts": [
    {
      "name": "Reba (Textile)",
      "color": "#3E96F7",
      "file": "Textile Regular.ttf",
      "title_case": "lower"
    }
  ]
}
```

### Preview Title Cards

![preview](https://github.com/user-attachments/assets/f1a00c6e-86a0-42d5-a428-4189c03a438a)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/18237986/fonts.zip)

**Comment by CollinHeist** [comment]
Looks great - thanks! /create-blueprint
